// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com>
// GENERATED by `omx-contract render --target ts` from FreeMixer/omx-contract's data/ — do not edit.

/**
 * The PAN travel — −1 (hard left) … 0 (center) … +1 (hard right). A property of the pan law itself, not of any desk, so it is declared once. Continuous: a pan position has no quantum, and panGains clamps to these bounds.
 * @see data/kernels/balance.json
 */
export declare const PAN_RANGE: {
  readonly min: -1;
  readonly max: 1;
  readonly step: 0;
  readonly unit: "";
};

/**
 * The side of the threshold the band acts on. Above acts when the band is loud, taming a resonance that only rings when pushed; below acts when it is quiet, lifting a band that drops out. The order is the integer the kernel reads: above is 0, below is 1.
 * @see data/kernels/band_dyn.json
 */
export declare const BAND_DYN_MODES: readonly ["above", "below"];

/**
 * The soft knee of the band's gain computer, in dB. One knee for the one band-dynamics word, shared by every stage that runs it, the de-esser included: a second spelling of 6 would be a second place where the reduction starts.
 * @see data/kernels/band_dyn.json
 */
export declare const BAND_DYN_KNEE_DB: 6;

/**
 * How many dynamic bands a channel may hold. A dynamic band is an operator band, so the capacity is the operator's reserve, read and not typed again.
 * @see data/kernels/band_dyn.json
 */
export declare const BAND_DYN_MAX_BANDS: 9;

/**
 * The shortest attack, in ms, at which the compressor's detector does not alias. Below it the compressor engages its 4x control path, which adds 72 samples of latency; a zero-latency band has no such path, so its attack travel stops at this floor.
 * @see data/kernels/band_dyn.json
 */
export declare const DETECTOR_OVERSAMPLE_AUTO_MS: 0.5;

/**
 * Where the band starts to act, in dB of the band's own level and not the strip's. It is the same fact the de-esser's threshold is, so it carries the same travel.
 * @see data/kernels/band_dyn.json
 */
export declare const BAND_DYN_THRESHOLD_RANGE: {
  readonly min: -60;
  readonly max: 0;
  readonly step: 0.5;
  readonly unit: "dB";
  readonly default: -30;
  readonly defaultFrom: "desk";
};

/**
 * How hard the band is held once it is past its threshold. 2:1 rather than the de-esser's 4:1, because a dynamic band is corrective, not a limiter for a sibilant.
 * @see data/kernels/band_dyn.json
 */
export declare const BAND_DYN_RATIO_RANGE: {
  readonly min: 1;
  readonly max: 20;
  readonly step: 0.1;
  readonly unit: "";
  readonly default: 2;
  readonly defaultFrom: "desk";
};

/**
 * The most the band may add to its static gain, signed: below zero the deepest cut, above zero the largest boost. The ceiling of +12 keeps static plus dynamic inside the EQ's own travel. Zero makes the band inert without switching it off.
 * @see data/kernels/band_dyn.json
 */
export declare const BAND_DYN_RANGE_RANGE: {
  readonly min: -24;
  readonly max: 12;
  readonly step: 0.5;
  readonly unit: "dB";
  readonly default: -6;
  readonly defaultFrom: "desk";
};

/**
 * The detector's attack, in ms. The travel stops at the oversampling floor, below which the band would need the compressor's delayed control path.
 * @see data/kernels/band_dyn.json
 */
export declare const BAND_DYN_ATTACK_RANGE: {
  readonly min: 0.5;
  readonly max: 100;
  readonly step: 0.1;
  readonly unit: "ms";
  readonly default: 5;
  readonly defaultFrom: "desk";
};

/**
 * The detector's release, in ms. 100 ms is long enough not to modulate a 40 Hz band inside four cycles.
 * @see data/kernels/band_dyn.json
 */
export declare const BAND_DYN_RELEASE_RANGE: {
  readonly min: 5;
  readonly max: 3000;
  readonly step: 1;
  readonly unit: "ms";
  readonly default: 100;
  readonly defaultFrom: "desk";
};

/**
 * The chorus's right-leg phase offset, in TURNS of its one oscillator (§2, §3a; the native-FX catalogue's M32 Dimension row). The right leg's voice k reads the LFO at k/N + spread: 0 is both legs one phase (the stage without the field, bit for bit), 0.25 quadrature, 0.5 the Dimension's opposed sweep. A fraction of a cycle carries no engineering symbol, so the unit is ''.
 * @see data/kernels/chorus.json
 */
export declare const CHORUS_SPREAD_RANGE: {
  readonly min: 0;
  readonly max: 0.5;
  readonly step: 0.01;
  readonly unit: "";
  readonly default: 0;
  readonly defaultFrom: "desk";
};

/**
 * The chorus sweep's speed (§3a). Above ~3 Hz it stops being a chorus and becomes a vibrato.
 * @see data/kernels/chorus.json
 */
export declare const CHORUS_RATE_RANGE: {
  readonly min: 0.05;
  readonly max: 8;
  readonly step: 0.01;
  readonly unit: "Hz";
  readonly default: 0.6;
  readonly defaultFrom: "desk";
};

/**
 * The chorus's peak-to-peak excursion above its declared 10 ms base (§3a).
 * @see data/kernels/chorus.json
 */
export declare const CHORUS_DEPTH_RANGE: {
  readonly min: 0;
  readonly max: 12;
  readonly step: 0.1;
  readonly unit: "ms";
  readonly default: 4;
  readonly defaultFrom: "desk";
};

/**
 * The chorus's tap count — one oscillator read at k/N (§3a).
 * @see data/kernels/chorus.json
 */
export declare const CHORUS_VOICES_RANGE: {
  readonly min: 1;
  readonly max: 4;
  readonly step: 1;
  readonly unit: "";
  readonly default: 3;
  readonly defaultFrom: "desk";
};

/**
 * The chorus's wet/dry, as an instance of DRIVE_MIX_RANGE — the same percent travel, its own come-up value: 35 %, a colour under the dry on a strip (§3a). The REVERB_LOWCUT_RANGE-over- REVERB_CUT_RANGE shape: one travel, one declared default per field that reads it.
 * @see data/kernels/chorus.json
 */
export declare const CHORUS_MIX_RANGE: {
  readonly min: 0;
  readonly max: 100;
  readonly step: 0.1;
  readonly unit: "%";
  readonly default: 35;
  readonly defaultFrom: "desk";
};

/**
 * The chorus's base delay, ms: the voices swing around it by up to the depth.
 * @see data/kernels/chorus.json
 */
export declare const CHORUS_BASE_MS: 10;

/**
 * The longest delay a chorus voice reaches, rounded up to whole ms: the base delay plus the depth maximum. The delay line is sized from it.
 * @see data/kernels/chorus.json
 */
export declare const CHORUS_MAX_MS: 22;

/**
 * The legal range of each compressor field (engineering units). The widget clamps drags to these, `normalizeComp` enforces them, the row's codec refuses by them and the travel sheet publishes them. `default`/`defaultFrom` are the come-up values `defaultCompState` seeds a fresh strip with, read BACK from here rather than restated there.
 * @see data/kernels/comp.json
 */
export declare const COMP_LIMITS: {
  readonly thresholdDb: {
    readonly min: -60;
    readonly max: 0;
    readonly step: 1;
    readonly unit: "dB";
    readonly default: -18;
    readonly defaultFrom: "desk";
  };
  readonly ratio: {
    readonly min: 1;
    readonly max: 20;
    readonly step: 0.5;
    readonly unit: "";
    readonly default: 4;
    readonly defaultFrom: "desk";
  };
  readonly kneeDb: {
    readonly min: 0;
    readonly max: 24;
    readonly step: 0.5;
    readonly unit: "dB";
    readonly default: 6;
    readonly defaultFrom: "desk";
  };
  readonly attackMs: {
    readonly min: 0.1;
    readonly max: 100;
    readonly step: 1;
    readonly unit: "ms";
    readonly default: 5;
    readonly defaultFrom: "desk";
  };
  readonly releaseMs: {
    readonly min: 5;
    readonly max: 3000;
    readonly step: 10;
    readonly unit: "ms";
    readonly default: 200;
    readonly defaultFrom: "desk";
  };
  readonly makeupDb: {
    readonly min: 0;
    readonly max: 24;
    readonly step: 0.5;
    readonly unit: "dB";
    readonly default: 0;
    readonly defaultFrom: "desk";
  };
  readonly mixPct: {
    readonly min: 0;
    readonly max: 100;
    readonly step: 5;
    readonly unit: "%";
    readonly default: 100;
    readonly defaultFrom: "desk";
  };
};

/**
 * The program-dependent release's model constants — the LA-2A's opto cell as DATA (`docs/design/specs/2026-09-26-compressor-models.md` §3b). `chargeMs`/`dischargeMs` are the word's memory constants, shared by every profile; each profile's `fastMs`, `slowMinMs`, `slowMaxMs` and `share` fit the unit's published two-stage recovery. Not operator controls: generated into `omx_contract_limits.h` as `OMX_PROGRAM_RELEASE_*`, which libomxdsp's `omx_env_program_release` reads.
 * @see data/kernels/comp.json
 */
export declare const PROGRAM_RELEASE: {
  readonly chargeMs: 1000;
  readonly dischargeMs: 5000;
  readonly profiles: {
    readonly opto: {
      readonly fastMs: 70;
      readonly slowMinMs: 110;
      readonly slowMaxMs: 1100;
      readonly share: 0.5;
    };
  };
};

/**
 * The detector band's CENTRE, in Hz. Sibilance lives at 5–10 kHz on most voices; 7 kHz with the default width covers 4 950–9 900 Hz, which is where an "s" and a "t" sit on a close vocal mic. The travel is wider than the come-up on both sides on purpose: a bright female vocal wants the band up near 9 kHz and a chesty male one down at 5, and a surface narrower than the row removes reach the console genuinely has (the same reasoning core's `REVERB_CUT_RANGE` records).
 * @see data/kernels/deesser.json
 */
export declare const DEESS_FREQ_RANGE: {
  readonly min: 2000;
  readonly max: 16000;
  readonly step: 10;
  readonly unit: "Hz";
  readonly default: 7000;
  readonly defaultFrom: "desk";
};

/**
 * The band's WIDTH, in OCTAVES around the centre: the edges are `f / 2^(w/2)` and `f · 2^(w/2)`, which is what makes the centre the geometric middle at every width. Octaves and not a Q, because a Q is a property of one section and this band is TWO (a highpass and a lowpass, `mix_deesser.h`) — an operator asked to dial a Q would be dialling a number neither filter carries. One octave is the classic de-esser band: wide enough for a sibilant that moves with the vowel, narrow enough that a 1 kHz vowel sits 27.8 dB down the skirt.
 * @see data/kernels/deesser.json
 */
export declare const DEESS_WIDTH_RANGE: {
  readonly min: 0.25;
  readonly max: 4;
  readonly step: 0.05;
  readonly unit: "oct";
  readonly default: 1;
  readonly defaultFrom: "desk";
};

/**
 * Where reduction starts — the level of the BAND, not of the strip, which is why the come-up is so much lower than the compressor's. A vocal peaking −12 dBFS carries roughly −30 dBFS in a one-octave band at 7 kHz on its sibilants and under −40 on its vowels, so −30 sits between the two and the stage opens on an "s" and stays shut on an "ah".
 * @see data/kernels/deesser.json
 */
export declare const DEESS_THRESHOLD_RANGE: {
  readonly min: -60;
  readonly max: 0;
  readonly step: 0.5;
  readonly unit: "dB";
  readonly default: -30;
  readonly defaultFrom: "desk";
};

/**
 * How hard the band is held once it is over the threshold. 4:1 is the textbook de-esser ratio: firm on the "s", short of a limiter.
 * @see data/kernels/deesser.json
 */
export declare const DEESS_RATIO_RANGE: {
  readonly min: 1;
  readonly max: 20;
  readonly step: 0.1;
  readonly unit: "";
  readonly default: 4;
  readonly defaultFrom: "desk";
};

/**
 * The FLOOR on the reduction, in dB and never positive — the deepest cut the stage may reach however loud the sibilant is (`mix_deesser.h`'s clamp, §4c). 12 dB tames a hard sibilant; past that a voice starts to lisp, and a de-esser with NO floor turns a shouted "s" into a hole. The ceiling is 0, which switches the reduction off without switching the stage off — a legitimate thing to want while dialling the band in by ear.
 * @see data/kernels/deesser.json
 */
export declare const DEESS_RANGE_RANGE: {
  readonly min: -24;
  readonly max: 0;
  readonly step: 0.5;
  readonly unit: "dB";
  readonly default: -12;
  readonly defaultFrom: "desk";
};

/**
 * The detector's ATTACK, in ms. A sibilant's onset is a few milliseconds; 1 ms catches it without the detector chattering on the band's own waveform.
 * @see data/kernels/deesser.json
 */
export declare const DEESS_ATTACK_RANGE: {
  readonly min: 0.1;
  readonly max: 50;
  readonly step: 0.1;
  readonly unit: "ms";
  readonly default: 1;
  readonly defaultFrom: "desk";
};

/**
 * The detector's RELEASE, in ms. 60 ms is long enough not to modulate inside one "s" and short enough to be open again for the next syllable.
 * @see data/kernels/deesser.json
 */
export declare const DEESS_RELEASE_RANGE: {
  readonly min: 5;
  readonly max: 500;
  readonly step: 1;
  readonly unit: "ms";
  readonly default: 60;
  readonly defaultFrom: "desk";
};

/**
 * The knee, in dB — a CONSTANT of the stage and not a row field (`2026-09-22-native-deesser-stage.md` §4b): a de-esser without a soft knee latches audibly on the first sibilant of a phrase, and no other value of this number is a de-esser anyone would dial. The controller pushes it to the node and this is the same number; a second spelling would be a picture that disagrees with the audio about where the reduction starts.
 * @see data/kernels/deesser.json
 */
export declare const DEESS_KNEE_DB: 6;

/**
 * The de-esser's modes, in the order of the integer the kernel reads: split attenuates the detected band only, wideband the whole signal while the sibilance lasts.
 * @see data/kernels/deesser.json
 */
export declare const DEESS_MODES: readonly ["split", "wideband"];

/**
 * The FX delay's time travel. `max` is the NATIVE ring's ceiling — the same number as `OMX_FXDELAY_MAX_MS` in `omx_delay.h`, pinned to it by `output-delay-ceiling.test.ts`. Distinct from the per-route ALIGNMENT delay (`OUTPUT_DELAY_RANGE`, 1 s, `OMX_DELAY_MAX_MS`): one is a musical echo with feedback and mix, the other is a pure latency. Two facts, two rings, two ceilings — sharing the word "delay" is why they keep being confused for each other.
 * @see data/kernels/delay.json
 */
export declare const FX_DELAY_TIME_RANGE: {
  readonly min: 0;
  readonly max: 2000;
  readonly step: 1;
  readonly unit: "ms";
  readonly default: 300;
  readonly defaultFrom: "desk";
};

/**
 * The FX delay's REGENERATION travel — how much of the wet tail feeds back in. Stops short of 1: unity feedback is a runaway the kernel hard-clamps anyway, so offering it would draw travel the DSP refuses. Not NORMALIZED_RANGE for exactly that reason — it is a 0..1 quantity whose top the DSP does not accept, and a control must not offer a value its actuator will eat.
 * @see data/kernels/delay.json
 */
export declare const FX_DELAY_FEEDBACK_RANGE: {
  readonly min: 0;
  readonly max: 0.99;
  readonly step: 0;
  readonly unit: "";
  readonly default: 0.3;
  readonly defaultFrom: "desk";
};

/**
 * The FX delay's TONE — a NORMALIZED_RANGE instance with its own come-up value, matching `DEFAULT_DELAY_STATE.tone`. See REVERB_SIZE_RANGE for why this is a named constant rather than a default on the shared shape.
 * @see data/kernels/delay.json
 */
export declare const DELAY_TONE_RANGE: {
  readonly min: 0;
  readonly max: 1;
  readonly step: 0;
  readonly unit: "";
  readonly default: 0.3;
  readonly defaultFrom: "desk";
};

/**
 * The FX DELAY's wet/dry — the same split as REVERB_MIX_RANGE, its own declaration.
 * @see data/kernels/delay.json
 */
export declare const DELAY_MIX_RANGE: {
  readonly min: 0;
  readonly max: 1;
  readonly step: 0;
  readonly unit: "";
  readonly default: 0.3;
  readonly defaultFrom: "desk";
  readonly byKind: {
    readonly fxReturn: 1;
  };
};

/**
 * The FX delay's PING-PONG come-up value — a toggle, so it has no travel, only this. Declared here rather than as a literal in the server's `DEFAULT_DELAY_STATE` (which now reads it) so the DPF plugin generator (`packages/omx-plugins/tools/params-gen.mjs`, `2026-09-25-omx-plugins-dpf.md` §3a) reads the same fact the desk seeds a fresh strip with.
 * @see data/kernels/delay.json
 */
export declare const FX_DELAY_PINGPONG_DEFAULT: false;

/**
 * The bias at `character = +1`, in the SHAPER's own input units — `OMX_DRIVE_BIAS_MAX`. DERIVED, not chosen (§4b). In the saturating limit every knee tends to `sgn`, the output is a rectangular wave of duty `d = ½ + asin(b)/π`, and its `n`th harmonic goes as `sin(nπd)/n` — so `|H2|` is maximal at `d = ¾`, which is `b = sin(π/4) = 1/√2` exactly. Measured too: the H2-maximising bias for a full-scale sine at unity drive is 0.712 (soft), 0.658 (tape), 0.645 (tube), and this one value costs 0.000 / 0.035 / 0.088 dB of H2 against each curve's own optimum. ONE normalised bias for all three knees, not three.
 * @see data/kernels/drive.json
 */
export declare const DRIVE_BIAS_MAX: 0.7071067811865476;

/**
 * The PRE-CURVE gain, in dB. 0 dB is unity into the curve, so a stage switched on at its defaults changes almost nothing — which is what an `on` switch should mean. The ceiling is where every curve is saturating hard on any signal a console carries.
 * @see data/kernels/drive.json
 */
export declare const DRIVE_AMOUNT_RANGE: {
  readonly min: 0;
  readonly max: 36;
  readonly step: 0.1;
  readonly unit: "dB";
  readonly default: 0;
  readonly defaultFrom: "desk";
};

/**
 * The EVEN/ODD harmonic balance. −1 is pure odd (the curve itself), +1 is pure even, 0 an equal blend — the kernel splits its own distortion residue into an odd and an even half and fades between them, so the two ends are exact rather than approximate (`mix_drive.h`, measured: H2 at −317 dBc at −1, H3 at −118 dBc at +1). Unitless, and signed by construction. NOT NORMALIZED_RANGE: this is a BALANCE with a meaningful centre, and a 0..1 travel would put its centre at 0.5 and its neutral nowhere.
 * @see data/kernels/drive.json
 */
export declare const DRIVE_CHARACTER_RANGE: {
  readonly min: -1;
  readonly max: 1;
  readonly step: 0.01;
  readonly unit: "";
  readonly default: 0;
  readonly defaultFrom: "desk";
};

/**
 * The band split / tilt corner, in Hz. ONE travel for all three band modes, because the C imposes one constraint on all of them: it is the corner of a single biquad, and the split's other half is `x − LP(x)`. The full audio band, not the channel filters' narrower HPF/LPF pair — the same reasoning REVERB_CUT_RANGE records: a surface narrower than the row removes reach the console genuinely has.
 * @see data/kernels/drive.json
 */
export declare const DRIVE_BAND_FREQ_RANGE: {
  readonly min: 20;
  readonly max: 20000;
  readonly step: 1;
  readonly unit: "Hz";
  readonly default: 2000;
  readonly defaultFrom: "desk";
};

/**
 * The wet/dry, as a PERCENT — the unit a drive control is read in on every desk that has one. Deliberately not NORMALIZED_RANGE (which is unitless 0..1): a mix a surface must label "0.35" when the operator thinks in "35 %" is a control whose declaration is fighting its reader. The kernel divides by 100 where it resolves the atom, in one place. The come-up is 100 %, not the reverb's modest 30: a saturator's insert use is IN the path. The `exciter` curve seeds itself lower (DRIVE_EXCITER_SEED), because that is a property of the TOPOLOGY and not of the travel.
 * @see data/kernels/drive.json
 */
export declare const DRIVE_MIX_RANGE: {
  readonly min: 0;
  readonly max: 100;
  readonly step: 0.1;
  readonly unit: "%";
  readonly default: 100;
  readonly defaultFrom: "desk";
};

/**
 * The POST-stage make-up, in dB. Symmetric enough either way that an operator can null the stage in and out against the bypass, which is how a colour stage is actually judged.
 * @see data/kernels/drive.json
 */
export declare const DRIVE_TRIM_RANGE: {
  readonly min: -24;
  readonly max: 12;
  readonly step: 0.1;
  readonly unit: "dB";
  readonly default: 0;
  readonly defaultFrom: "desk";
};

/**
 * The drive's shaper curves, in the order of the integer the kernel reads. Exciter runs the soft shape in a parallel-sum topology.
 * @see data/kernels/drive.json
 */
export declare const DRIVE_CURVES: readonly ["soft", "tape", "tube", "exciter"];

/**
 * Which part of the spectrum the drive's curve is fed, in the order of the integer the kernel reads. The split is complementary, so mix 0 stays bit-identical to the dry signal.
 * @see data/kernels/drive.json
 */
export declare const DRIVE_BANDS: readonly ["full", "low", "high", "tilt"];

/**
 * The maximum number of parametric bands a channel EQ may hold — the operator can add up to this many. Generated into `omx_contract_limits.h` as `OMX_EQ_MAX_BANDS`, which `omx_biquad.h` reads (`output-delay-ceiling.test.ts` reads the header): the native lane allocates exactly this many biquad slots per channel and silently clamps above it, so the model, the wire, and the DSP agree by test, not by memory.
 * @see data/kernels/eq.json
 */
export declare const EQ_MAX_BANDS: 24;

/**
 * The standard ISO 266 one-third-octave centre frequencies, 20 Hz–20 kHz (31 bands) — the classic 31-band graphic-EQ layout's centres.
 * @see data/kernels/eq.json
 */
export declare const ISO_THIRD_OCTAVE_CENTRES_HZ: readonly [20, 25, 31.5, 40, 50, 63, 80, 100, 125, 160, 200, 250, 315, 400, 500, 630, 800, 1000, 1250, 1600, 2000, 2500, 3150, 4000, 5000, 6300, 8000, 10000, 12500, 16000, 20000];

/**
 * The graphic EQ's section count: DERIVED from ISO_THIRD_OCTAVE_CENTRES_HZ, never a second literal. Generated into `omx_contract_limits.h` as `OMX_GEQ_BANDS`, which sizes `mix_geq.h`'s section array — its OWN budget, never a claimant on EQ_MAX_BANDS (graphic-eq-31 spec §3, roster ruling 3).
 * @see data/kernels/eq.json
 */
export declare const GEQ_BANDS: 31;

/**
 * The frequency band a parametric band can be dragged across.
 * @see data/kernels/eq.json
 */
export declare const EQ_FREQ_RANGE: {
  readonly min: 20;
  readonly max: 20000;
  readonly step: 10;
  readonly unit: "Hz";
};

/**
 * The parametric-band gain travel, in dB. The ± scalar `clampEqGain` enforces is READ off this (`core/src/eq.ts` derives `EQ_GAIN_LIMIT_DB` from `max`), so the bound is stated once and a surface cannot draw a wider knob than the clamp will honour.
 * @see data/kernels/eq.json
 */
export declare const EQ_GAIN_RANGE: {
  readonly min: -15;
  readonly max: 15;
  readonly step: 0.5;
  readonly unit: "dB";
};

/**
 * The Q (resonance) extent of a parametric band.
 * @see data/kernels/eq.json
 */
export declare const EQ_Q_RANGE: {
  readonly min: 0.3;
  readonly max: 8;
  readonly step: 0.1;
  readonly unit: "";
};

/**
 * The Q extent of a NOTCH band. Wider than EQ_Q_RANGE on purpose (#116, operator decision): an ultra-narrow surgical cut is the notch shape's whole point — the FBS ring-out pool plants dbx-AFS-style ring killers at Q ≈ 116 (~1/80 octave), inaudible on program yet fatal to a single ringing frequency. Gain-carrying shapes stay bounded at EQ_Q_RANGE — a Q-116 bell is a resonator, not an EQ move.
 * @see data/kernels/eq.json
 */
export declare const EQ_NOTCH_Q_RANGE: {
  readonly min: 0.3;
  readonly max: 116;
  readonly step: 1;
  readonly unit: "";
};

/**
 * Where the HPF cutoff can sit (low end); mirrors the drawn low-frequency handle.
 * @see data/kernels/eq.json
 */
export declare const HPF_FREQ_RANGE: {
  readonly min: 20;
  readonly max: 1000;
  readonly step: 10;
  readonly unit: "Hz";
};

/**
 * Where the LPF cutoff can sit (high end).
 * @see data/kernels/eq.json
 */
export declare const LPF_FREQ_RANGE: {
  readonly min: 1000;
  readonly max: 20000;
  readonly step: 10;
  readonly unit: "Hz";
};

/**
 * The band slots kept for the operator's own hand: the reserve the feedback suppressor and the ring correction may never eat into. Nine is the working set a live EQ actually holds. The budget OPERATOR_EQ_BANDS_RESERVE + FBS_DEFAULT_MAX_AUTO_BANDS + HRP_DEFAULT_MAX_AUTO_BANDS (9 + 6 + 8 = 23) must fit EQ_MAX_BANDS, and `omx-contract validate` refuses data where it does not.
 * @see data/kernels/eq.json
 */
export declare const OPERATOR_EQ_BANDS_RESERVE: 9;

/**
 * The generic EQ band shapes, in the order a picker offers them and in the order of the integer a plugin host sees on a band type port. The id is the name; the position is the value. A bell is the shape a band added by the operator starts as.
 * @see data/kernels/eq.json
 */
export declare const EQ_BAND_TYPES: readonly ["bell", "lowShelf", "highShelf", "notch", "allpass1", "allpass2"];

/**
 * The pass-filter slopes the EQ offers, in dB per octave. The id is the slope: 12 is one maximally flat section, 24 the two-section Butterworth.
 * @see data/kernels/eq.json
 */
export declare const FILTER_SLOPES: readonly [12, 24];

/**
 * How many bands each strip type's EQ starts with (`default`) and may hold (`max`). `channel` is the console's channel strip: it starts with four and the operator adds bands up to EQ_MAX_BANDS (a band added takes the frequency it is added at, so no default is declared for it). `strip` is the omx-strip plugin's EQ and `eq8`, `eq16` and `eq32` the omx-eq plugins, whose bands are fixed. A default may never exceed its maximum, and the default centres of any count come from the one default rule, whatever the strip.
 * @see data/kernels/eq.json
 */
export declare const EQ_BAND_COUNTS: {
  readonly channel: {
    readonly default: 4;
    readonly max: 24;
  };
  readonly strip: {
    readonly default: 4;
    readonly max: 4;
  };
  readonly eq8: {
    readonly default: 8;
    readonly max: 8;
  };
  readonly eq16: {
    readonly default: 16;
    readonly max: 16;
  };
  readonly eq32: {
    readonly default: 32;
    readonly max: 32;
  };
};

/**
 * What every band of a fresh EQ comes up at, whatever its type and its strip: flat (0 dB) and Q 1. The band frequencies and types come from the default rule.
 * @see data/kernels/eq.json
 */
export declare const EQ_BAND_DEFAULTS: {
  readonly gainDb: 0;
  readonly q: 1;
};

/**
 * The corners the high-pass and low-pass filters of a fresh EQ are parked at, whatever the strip. Both come up off.
 * @see data/kernels/eq.json
 */
export declare const EQ_PASS_FILTER_DEFAULTS: {
  readonly hpfFreqHz: 80;
  readonly lpfFreqHz: 18000;
};

/**
 * The default band centres of a four-band EQ, Hz: ISO 266 preferred values, two to two and a half octaves apart. The default rule gives every other band count its centres from the preferred series; four bands start here.
 * @see data/kernels/eq.json
 */
export declare const EQ_DEFAULT_CENTRES_FOUR_BAND_HZ: readonly [100, 400, 2000, 8000];

/**
 * The ISO 266 R20 preferred frequencies from 20 Hz to 20 kHz (61 values, sixth-octave spacing): the finer series the default band rule falls back to where R10 (ISO_THIRD_OCTAVE_CENTRES_HZ, 31 values) has too few to give every band its own centre. R10 is a subset of it.
 * @see data/kernels/eq.json
 */
export declare const EQ_CENTRE_SERIES_R20_HZ: readonly [20, 22.4, 25, 28, 31.5, 35.5, 40, 45, 50, 56, 63, 71, 80, 90, 100, 112, 125, 140, 160, 180, 200, 224, 250, 280, 315, 355, 400, 450, 500, 560, 630, 710, 800, 900, 1000, 1120, 1250, 1400, 1600, 1800, 2000, 2240, 2500, 2800, 3150, 3550, 4000, 4500, 5000, 5600, 6300, 7100, 8000, 9000, 10000, 11200, 12500, 14000, 16000, 18000, 20000];

/**
 * How far (bins) around bin/2 and bin/3 PSHR (`omx_fbs_pshr`) scans for a sub-harmonic line. A true half/third partial lands mid-bin in the worst case (bin/2 and bin/3 are rarely integers) and spectral leakage smears it one bin further; ±2 covers both. Measured on the #116 live-music corpus: every false positive's sub-line sat inside this window. Deliberately NOT wider — at low bins the window is already a large fraction of an octave, and widening it would start reading unrelated program lines as "sub-harmonics" of real feedback.
 * @see data/kernels/fbs.json
 */
export declare const SUBHARMONIC_RADIUS_BINS: 2;

/**
 * PAPR's guard band: bins either side of the peak left out of the floor average (its own skirt).
 * @see data/kernels/fbs.json
 */
export declare const FBS_PAPR_GUARD_BINS: 2;

/**
 * PNPR's neighbourhood radius in bins, and the guard inside it that belongs to the peak's own skirt: a pure tone is compared with bins 2 and 3 away on each side.
 * @see data/kernels/fbs.json
 */
export declare const FBS_PNPR_RADIUS_BINS: 3;

/**
 * The guard inside PNPR's neighbourhood radius that belongs to the peak's own skirt, in bins.
 * @see data/kernels/fbs.json
 */
export declare const FBS_PNPR_GUARD_BINS: 1;

/**
 * How many harmonics PHPR reads above the candidate: 2f, 3f and 4f.
 * @see data/kernels/fbs.json
 */
export declare const FBS_PHPR_HARMONICS: 3;

/**
 * PSHR skips sub-window bins within this many of the candidate, so a low bin never measures its own skirt as a sub-harmonic.
 * @see data/kernels/fbs.json
 */
export declare const FBS_PSHR_SELF_SKIP_BINS: 3;

/**
 * The magnitude floor of every detector dB reading (−240 dB): a zero bin stays finite.
 * @see data/kernels/fbs.json
 */
export declare const FBS_FLOOR_LIN: 1e-12;

/**
 * Tracked candidate bins per armed channel. A candidate that finds no free slot is COUNTED and reported, never dropped silently; the identity corpus peaks at 34.
 * @see data/kernels/fbs.json
 */
export declare const FBS_TRACK_SLOTS: 512;

/**
 * Minimum PSHR (`omx_fbs_pshr`) (dB) for a candidate frame to count as sub-harmonic-CLEAN. Evidence-set on the #116 corpus, margin on both sides: the four live false positives (musical overtones at 1 869.1 / 832.0 / 263.7 / 228.5 Hz) read PSHR between −10.2 and +8.8 dB across their windows — never a 5-frame sub-clean stretch, and the single closest approach (+8.8) is isolated between frames at ≈ −1 and −10 — while the committed #106 injected ramp reads ≥ +12.2 dB from its second frame on (its frame 0 sits at +9.4, costing exactly one frame of confirm latency, pinned in the corpus test). A static program line at f/2 of REAL feedback also clears this fast: the runaway gains several dB per hop on anything static, so the deferral is transient.
 * @see data/kernels/fbs.json
 */
export declare const PSHR_MIN_DB: 10;

/**
 * How many of a candidate bin's most recent dB readings feed the growth-slope estimate (the engine's least-squares slope) — set equal to DEFAULT_THRESHOLDS's `persistFrames` so growth is judged over the SAME window persistence already demands (the full run since the bin became a candidate, not a shorter or longer slice of it). Long enough that a couple of noisy/vibrato frames can't fake a trend by themselves.
 * @see data/kernels/fbs.json
 */
export declare const GROWTH_WINDOW_FRAMES: 5;

/**
 * The DEEP plateau tier's dwell: ~2 s at the watcher's 10 Hz — the TIME that buys the deeper floor its music safety (see DetectThresholds.deepPlateauFloorDb).
 * @see data/kernels/fbs.json
 */
export declare const DEEP_PLATEAU_FRAMES: 20;

/**
 * Minimum least-squares slope, in dB PER FRAME, over GROWTH_WINDOW_FRAMES for a bin to count as "running away" rather than merely holding level. Set with real margin on BOTH sides — comfortably above measurement jitter on a held tone or a quiet/broadband mix (well under 0.2 dB/frame in practice) and comfortably below a genuine feedback ramp, which climbs several dB across a handful of ~20 ms hops as it heads toward clipping. Issue #91's acceptance bar is "arming must never burst-alarm on non-growing content", so this errs conservative (under-fire a marginal ramp) rather than tight (risk a false alarm) — the ramp gate (`omx_fbs_is_growing`) also requires the window's end to sit above its start, a cheap belt-and-braces check against a fit dragged positive by one mid-window wobble.
 * @see data/kernels/fbs.json
 */
export declare const GROWTH_MIN_DB_PER_FRAME: 0.8;

/**
 * Largest single-frame DIP (dB) a run-away window may contain. Real feedback climbs every hop; a small allowance covers measurement jitter and the −0.3 dB-ish wobble frames seen on live captures, while any real drop (a note ending, tremolo) breaks the run.
 * @see data/kernels/fbs.json
 */
export declare const GROWTH_MAX_DIP_DB: 0.5;

/**
 * Minimum END-TO-END rise (dB) across the window. The live-music corpus (issue #106) showed sustained melody notes drifting up ~4–5 dB over a window without ever being feedback; a loop past unity gains several dB per hop and clears 6 dB in a window trivially. Below this the tone is holding level, not running away.
 * @see data/kernels/fbs.json
 */
export declare const GROWTH_MIN_TOTAL_RISE_DB: 6;

/**
 * Cap on the share of the window's total rise a SINGLE frame may carry. Feedback is exponential in amplitude ⇒ linear in dB ⇒ its rise is distributed roughly evenly across the window; a musical attack / re-articulation puts almost the whole rise in one hop (the exact shape behind every one of issue #106's 72 live false positives). One half is generous to real ramps (an even N-frame ramp puts 1/(N−1) per hop) and fatal to steps. A side effect worth knowing: a 2-sample window can never pass (one hop IS the whole rise), so confirmation always rests on at least three frames of actual ramp evidence.
 * @see data/kernels/fbs.json
 */
export declare const GROWTH_MAX_SINGLE_FRAME_SHARE: 0.5;

/**
 * How many CONSECUTIVE frames the ramp gate (`omx_fbs_is_growing`) must hold before a bin confirms — the time-domain tiebreak for the one shape a single window cannot judge (issue #106): a smooth musical crescendo. Within one window a +6 dB swell (live corpus: a C6 at 1 049 Hz, `[-53.7, -51.4, -50.4, -48, -47.3]`) is indistinguishable from slow feedback — the difference is only visible on the NEXT hop, where a crescendo peaks and plateaus (the window's rise collapses) while feedback keeps climbing. Requiring the gate to hold twice in a row costs a clean ramp nothing — its gate is already true while persistence is still arming — and blocks the swell that peaks the very frame it would have confirmed.
 * @see data/kernels/fbs.json
 */
export declare const GROWTH_CONFIRM_FRAMES: 2;

/**
 * The corpus-tuned SAFE DEFAULT — today's exact gates, assembled byte-for-byte from the exported consts above (which stay the authoritative literal source, so the corpus test's import type { MagnitudeSeries } from './spectrum-bands.js'; imports remain the single truth). This is the ANCHOR the whole sensitivity mapping pins to: thresholdsFor`(0, 'live')` and `(0, 'fixed')` both deep-equal this object, so an untouched channel runs the identical detector it does now. `plateauFloorDb` is omitted ⇒ the #140 plateau route is OFF at the default.
 * @see data/kernels/fbs.json
 */
export declare const DEFAULT_THRESHOLDS: {
  readonly paprDb: 18;
  readonly pnprDb: 12;
  readonly phprDb: 9;
  readonly persistFrames: 5;
  readonly growthConfirmFrames: 2;
  readonly subCleanFrames: 5;
  readonly growthMinTotalRiseDb: 6;
  readonly growthMaxSingleFrameShare: 0.5;
  readonly growthMinDbPerFrame: 0.8;
  readonly growthMaxDipDb: 0.5;
  readonly pshrMinDb: 10;
};

/**
 * THE NOTCH DEPTH LAW: the deepest cut any machine planter may propose from one reading, in dB. A number, not a literal at the call site, because two planters now lean on it. FBS derives a candidate's depth from the peak-to-average ratio around its bin and stops here; Room Analysis derives a mode's depth from its height above the median curve and is held to the SAME ceiling (2026-09-08-room-analysis.md §4 — "never more than the FBS notch depth law"). Written twice as `18` those two bounds would be equal by coincidence and could drift apart in silence. It is a CEILING ON THE PROPOSAL, not the final gain: a band that lands as a rampable BELL is bounded again by `EQ_GAIN_RANGE`, which is tighter. A planter must honour both and REPORT when either bit, never quietly deliver a shallower cut than it was asked for.
 * @see data/kernels/fbs.json
 */
export declare const FBS_MAX_NOTCH_DEPTH_DB: 18;

/**
 * Default planted-notch width (Q) — the dbx-AFS-style ultra-narrow notch the corrector plants. `addBand`'s per-shape clamp holds it at 116 for a fixed notch and narrows it to 8 for a live bell, so this is the declared starting point rather than the width every notch ends up with.
 * @see data/kernels/fbs.json
 */
export declare const FBS_DEFAULT_NOTCH_Q: 116;

/**
 * Default per-channel cap on auto-planted bands — a full pool plants nothing and raises a pool-full alert instead (predictability over silent eviction).
 * @see data/kernels/fbs.json
 */
export declare const FBS_DEFAULT_MAX_AUTO_BANDS: 6;

/**
 * The flanger's jet sweep (§3b).
 * @see data/kernels/flanger.json
 */
export declare const FLANGER_RATE_RANGE: {
  readonly min: 0.05;
  readonly max: 5;
  readonly step: 0.01;
  readonly unit: "Hz";
  readonly default: 0.25;
  readonly defaultFrom: "desk";
};

/**
 * The flanger's peak-to-peak excursion above its declared 0.5 ms base (§3b).
 * @see data/kernels/flanger.json
 */
export declare const FLANGER_DEPTH_RANGE: {
  readonly min: 0;
  readonly max: 5;
  readonly step: 0.1;
  readonly unit: "ms";
  readonly default: 2;
  readonly defaultFrom: "desk";
};

/**
 * The flanger's SIGNED resonance (§3b). The ±0.95 clamp is DECLARED here — a PATCH asking for 1.0 is answered by this travel — and the kernel's own clamp is the enforcement half.
 * @see data/kernels/flanger.json
 */
export declare const FLANGER_FEEDBACK_RANGE: {
  readonly min: -0.95;
  readonly max: 0.95;
  readonly step: 0.01;
  readonly unit: "";
  readonly default: 0.6;
  readonly defaultFrom: "desk";
};

/**
 * The flanger's wet/dry, as an instance of DRIVE_MIX_RANGE: 50 %, equal dry and wet, where the comb is deepest (§3b).
 * @see data/kernels/flanger.json
 */
export declare const FLANGER_MIX_RANGE: {
  readonly min: 0;
  readonly max: 100;
  readonly step: 0.1;
  readonly unit: "%";
  readonly default: 50;
  readonly defaultFrom: "desk";
};

/**
 * The flanger's base delay, ms: the sweep rides on it up to the depth.
 * @see data/kernels/flanger.json
 */
export declare const FLANGER_BASE_MS: 0.5;

/**
 * The longest delay a flanger sweep reaches, rounded up to whole ms: the base delay plus the depth maximum. The delay line is sized from it.
 * @see data/kernels/flanger.json
 */
export declare const FLANGER_MAX_MS: 6;

/**
 * The legal range of each gate field (engineering units). The widget clamps drags to these, `normalizeGate` enforces them, the row's codec refuses by them and the travel sheet publishes them — one source of truth. `rangeDb` reaches GATE_RANGE_FLOOR_DB, shown as "−∞" in readouts (a gate fully closed is silence).
 * @see data/kernels/gate.json
 */
export declare const GATE_LIMITS: {
  readonly thresholdDb: {
    readonly min: -80;
    readonly max: 0;
    readonly step: 1;
    readonly unit: "dB";
    readonly default: -40;
    readonly defaultFrom: "desk";
  };
  readonly rangeDb: {
    readonly min: -90;
    readonly max: 0;
    readonly step: 1;
    readonly unit: "dB";
    readonly default: -90;
    readonly defaultFrom: "desk";
  };
  readonly kneeStartDb: {
    readonly min: -80;
    readonly max: 0;
    readonly step: 1;
    readonly unit: "dB";
    readonly default: -43;
    readonly defaultFrom: "desk";
  };
  readonly kneeEndDb: {
    readonly min: -80;
    readonly max: 0;
    readonly step: 1;
    readonly unit: "dB";
    readonly default: -37;
    readonly defaultFrom: "desk";
  };
  readonly attackMs: {
    readonly min: 0;
    readonly max: 500;
    readonly step: 0.5;
    readonly unit: "ms";
    readonly default: 1;
    readonly defaultFrom: "desk";
  };
  readonly holdMs: {
    readonly min: 0;
    readonly max: 2000;
    readonly step: 5;
    readonly unit: "ms";
    readonly default: 10;
    readonly defaultFrom: "desk";
  };
  readonly releaseMs: {
    readonly min: 0;
    readonly max: 5000;
    readonly step: 10;
    readonly unit: "ms";
    readonly default: 100;
    readonly defaultFrom: "desk";
  };
  readonly hysteresisDb: {
    readonly min: 0;
    readonly max: 24;
    readonly step: 0.5;
    readonly unit: "dB";
    readonly default: 3;
    readonly defaultFrom: "desk";
  };
  readonly ratio: {
    readonly min: 1;
    readonly max: 100;
    readonly step: 1;
    readonly unit: "";
    readonly default: 16;
    readonly defaultFrom: "desk";
  };
};

/**
 * Where the gate listens: its own input (self), or the key it is handed (sidechain), in the order of the integer the key port carries.
 * @see data/kernels/gate.json
 */
export declare const GATE_KEY_SOURCES: readonly ["self", "sidechain"];

/**
 * One graphic-EQ fader's travel: EQ_GAIN_RANGE by reference (a graphic fader is an EQ gain), with the come-up value it needs as a row field — flat, 0 dB (graphic-eq-31 spec §3).
 * @see data/kernels/geq.json
 */
export declare const GEQ_BAND_RANGE: {
  readonly min: -15;
  readonly max: 15;
  readonly step: 0.5;
  readonly unit: "dB";
  readonly default: 0;
  readonly defaultFrom: "desk";
};

/**
 * The graphic EQ's band Q: the ISO third-octave bandwidth, `2^(1/6)/(2^(1/3) − 1) ≈ 4.318`, to one decimal as the M32 GEQ carries it. Read by the `geq31` preset and the graphic EQ's section design (graphic-eq-31 spec §3).
 * @see data/kernels/geq.json
 */
export declare const GEQ_BAND_Q: 4.3;

/**
 * The prototype gain the `true` solve's first interaction matrix is evaluated at (spec §2, §3): the middle of the travel's magnitude, where a matched-Z section's dB response per dB of gain is closest to its average.
 * @see data/kernels/geq.json
 */
export declare const GEQ_PROTO_DB: 12;

/**
 * The ceiling on a section gain the `true` solve may ask for (spec §3): above the travel's worst case (26.0 dB, the alternating ±15 set) with margin. A solve past it clamps and the row says so (`designClamped`), never silently.
 * @see data/kernels/geq.json
 */
export declare const GEQ_DESIGN_GAIN_MAX_DB: 30;

/**
 * The largest automatic cut HRP may place on one harmonic, as a POSITIVE dB magnitude. Well inside the ±15 dB an operator band may hold (core's `EQ_GAIN_LIMIT_DB`): an automatic correction the operator did not ask for gets far less authority than one they dialled themselves.
 * @see data/kernels/hrp.json
 */
export declare const HRP_MAX_CUT_DB: 6;

/**
 * How many simultaneous musical voices the detector may report on one channel. PINNED to `OMX_HRP_MAX_VOICES` in `pipewire-native/src/hrp_pitch.h` — the C voice set is a FIXED-SIZE array, so a TS number above the macro promises voices the analyser structurally cannot return, and one below it silently drops notes the C already found. `core/src/output-delay-ceiling.test.ts` reads the header and holds the pair equal. EIGHT (operator sizing, 2026-09-01): a guitar sounds six strings, a piano or string-section voicing sits at eight. It is a SEARCH ceiling, not a cost — the detector abandons a round as soon as no credible candidate remains, so monophonic material costs what it always did.
 * @see data/kernels/hrp.json
 */
export declare const HRP_MAX_VOICES: 8;

/**
 * The Q of an HRP correction band — one declared number, operator-adjustable later. A musical cut, not a ring killer: FBS's default notch Q is ~116 because a howl is a single frequency, whereas a partial that is too loud is a note an instrument is playing and a surgical null on it would be heard as a hole. 5 sits mid-band in the 4…6 range a musical subtractive cut occupies, and inside EQ_Q_RANGE — the gain-carrying shapes' extent — so it survives the store's clamp unchanged. Deliberately NOT derived from the harmonic index. A derivation invented with no measurement behind it is a second declaration wearing a formula; this is revisited when the analyse-only surface shows what real corrections look like.
 * @see data/kernels/hrp.json
 */
export declare const HRP_BAND_Q: 5;

/**
 * How far a partial must stand above its LEARNED BASELINE before HRP calls it a resonance (increment 8, §23–§24: `deviation = measured − baseline[note][harmonic]`). A partial level tells you nothing on its own; what marks a resonance is a partial louder than THIS instrument normally measures at THIS note. Three decibels is the same order as the feedback detector's peak-to-neighbour gate and for the same reason: below it, an ordinary performance's variation — a bow dug in, a verse sung harder — would be flattened, and flattening expression is not correcting a room. (Before the learned model existed this same threshold gated the placeholder neighbour rule; the number and its reasoning carried over.)
 * @see data/kernels/hrp.json
 */
export declare const HRP_EXCESS_THRESHOLD_DB: 3;

/**
 * How far ONE reconcile pass may move an HRP band's gain, in dB — §48's gain smoothing, done at the control level because the native cascade applies pushed coefficients verbatim and §48 forbids interpolating there. An unbounded gain step is a waveform discontinuity — the click heard when a correction entered or left at full depth (found live, 2026-08-20, the evening increment 9 raised the enter/leave rate). Bounded, a correction ENTERS by deepening from silence and LEAVES by walking to exactly 0 dB — the provable parked identity (`eqBandIsIdentity`) — from which removal is bit-identical. Two decibels per pass at the corrector's 10 Hz cadence walks the full HRP_MAX_CUT_DB travel in ~300 ms: the same order as the tracker's stability hold and FBS's lift steps, while each individual move stays below audibility on a Q-5 bell.
 * @see data/kernels/hrp.json
 */
export declare const HRP_GAIN_STEP_DB: 2;

/**
 * How close two correction candidates must sit, in cents, to count as the SAME spectral region (§30): within it, the stronger candidate is selected and the weaker discarded rather than two near-identical filters being planted. One semitone, and the number follows from HRP_BAND_Q: a Q-5 bell's −3 dB half-width is ~170 cents, so two cuts a semitone apart overlap over most of their travel — the second one deepens the first far more than it shapes anything of its own. The spec orders the threshold configurable and tested (§30's last line): declared once here, a parameter everywhere below.
 * @see data/kernels/hrp.json
 */
export declare const HRP_COLLISION_CENTS: 100;

/**
 * The ATTRIBUTION window (§11): two partials closer than this are one spectral event as far as the desk can tell — the same ±1 bin `omx_hrp_bin_peak` reads over, expressed musically so it holds across the range. A different law from HRP_COLLISION_CENTS (§30's SELECTION window, which stays above it): this one is the analyser's resolution, that one the corrector's. Generated into `omx_contract_limits.h` as `OMX_HRP_ATTRIBUTION_CENTS`; `hrp_attribute.h` reads it.
 * @see data/kernels/hrp.json
 */
export declare const HRP_ATTRIBUTION_CENTS: 60;

/**
 * How many bands HRP may plant on ONE channel — its half of the machine budget, and the number that makes the budget FORECASTABLE rather than emergent. Without it the count is whatever the material happens to provoke: the placement law is sparse, so a clean note plants two bands and a resonant room plants nine, and nobody can answer "will this fit?" until it does not. With FBS senior (§9.3(b)) that discovery would happen at showtime, to the junior planter, silently. Declared instead, the whole sum is arithmetic an operator can read before a note is played: operator bands + FBS maxAutoBands + HRP maxAutoBands <= EQ_MAX_BANDS EIGHT — ONE CORRECTION PER VOICE at full polyphony (operator sizing, 2026-09-01). The detector's ceiling is HRP_MAX_VOICES voices, a guitar's six strings and a piano/string voicing's eight, and a budget below the voice count would decide by arithmetic which of the notes actually sounding may be corrected — a limit nobody could read off the desk. Scarcity is handled where it belongs instead: the candidates from every voice meet in ONE globally ranked list (spec §29) and the head of it is what gets planted. It is NOT a claim to seniority, and it is larger than FBS's six. Seniority is the ALLOCATION ORDER — `HrpPlanter` takes only `EQ_MAX_BANDS − others.length`, the remainder after the operator and every other machine — so a bigger junior default cannot reach a senior slot; it only means HRP asks for more of what is left. `eq-budget-fits.test.ts` asserts both halves. The per-channel DEFAULT; the row's travel is HRP_AUTO_BANDS_RANGE, so a channel that needs more can have more, as an explicit decision with a visible cost.
 * @see data/kernels/hrp.json
 */
export declare const HRP_DEFAULT_MAX_AUTO_BANDS: 8;

/**
 * How much of the computed correction HRP applies: 0 = analyse only, 1 = the full cut. It comes up at 0.5, half the computed cut.
 * @see data/kernels/hrp.json
 */
export declare const HRP_AMOUNT_RANGE: {
  readonly min: 0;
  readonly max: 1;
  readonly step: 0;
  readonly unit: "";
  readonly default: 0.5;
  readonly defaultFrom: "desk";
};

/**
 * The precision limiter's travels (`2026-09-27-precision-limiter.md` §2), rendered into `omx_contract_limits.h` as `OMX_LIMITER_*` by `harness/contract-limits-gen.mjs`, so `mix_limiter.h` reads them and never restates one (R-094). The ceiling is a TRUE peak in dBFS (the ×4 detector); the look-ahead sets the declared latency; the release is the envelope's time constant on the gain depth.
 * @see data/kernels/limiter.json
 */
export declare const LIMITER_LIMITS: {
  readonly ceilingDb: {
    readonly min: -12;
    readonly max: 0;
    readonly step: 0.1;
    readonly unit: "dBFS";
    readonly default: -1;
    readonly defaultFrom: "desk";
  };
  readonly lookaheadMs: {
    readonly min: 0.5;
    readonly max: 5;
    readonly step: 0.1;
    readonly unit: "ms";
    readonly default: 1.5;
    readonly defaultFrom: "desk";
  };
  readonly releaseMs: {
    readonly min: 1;
    readonly max: 1000;
    readonly step: 1;
    readonly unit: "ms";
    readonly default: 50;
    readonly defaultFrom: "desk";
  };
};

/**
 * The input cap a summing bus can be sized to — **the engine's declared input ceiling**, read from `@freemixer/declarations` rather than re-typed here. A gig with more than this many inputs needs more than one engine node; below it a bus is sized to `min(N, BUS_INPUT_CAP)`. It was a literal 64 until 2026-09-15, said to mirror the engine's `MAX_BUS_INPUTS` — and it did, but that 64 was the PipeWire builtin mixer's single-tier fan-in (8 × 8), never the engine's bound: the native node has allocated `OMX_MAX_STRIPS` (128) strips all along. Two literals agreeing by hand is how the console came to refuse a 96-channel desk it could carry. `native-input-ceiling.test.ts` holds this to the C header; spec `docs/design/specs/2026-09-14-console-allocation.md` §9 carries the ruling and the measured cost of width.
 * @see data/kernels/mixmatrix.json
 */
export declare const BUS_INPUT_CAP: 128;

/**
 * The phaser's sweep speed (§3). `omx_lfo_inc` freezes at Nyquist; this travel stays far below.
 * @see data/kernels/phaser.json
 */
export declare const PHASER_RATE_RANGE: {
  readonly min: 0.05;
  readonly max: 5;
  readonly step: 0.01;
  readonly unit: "Hz";
  readonly default: 0.5;
  readonly defaultFrom: "desk";
};

/**
 * The phaser's lowest centre frequency; the sweep runs upward from it (§3).
 * @see data/kernels/phaser.json
 */
export declare const PHASER_BASE_RANGE: {
  readonly min: 50;
  readonly max: 2000;
  readonly step: 1;
  readonly unit: "Hz";
  readonly default: 200;
  readonly defaultFrom: "desk";
};

/**
 * The sweep's span above `base`, in octaves; 0 is a static phaser at `base` (§3).
 * @see data/kernels/phaser.json
 */
export declare const PHASER_DEPTH_RANGE: {
  readonly min: 0;
  readonly max: 6;
  readonly step: 0.1;
  readonly unit: "oct";
  readonly default: 4;
  readonly defaultFrom: "desk";
};

/**
 * The phaser's section count per leg — EVEN, 2 … 12 (§2: two sections per notch). Its ends are the kernel's state capacity (`OMX_PHASER_MAX_STAGES` reads `OMX_PHASER_STAGES_RANGE_MAX`); the row moves it through the closed member set PHASER_STAGE_COUNTS, which is derived from it.
 * @see data/kernels/phaser.json
 */
export declare const PHASER_STAGES_RANGE: {
  readonly min: 2;
  readonly max: 12;
  readonly step: 2;
  readonly unit: "";
  readonly default: 6;
  readonly defaultFrom: "desk";
};

/**
 * The member set the `stages` field accepts: PHASER_STAGES_RANGE walked by its step.
 * @see data/kernels/phaser.json
 */
export declare const PHASER_STAGE_COUNTS: readonly [2, 4, 6, 8, 10, 12];

/**
 * The phaser's SIGNED resonance (§3). ±0.9, tighter than the flanger's ±0.95: the loop runs through a time-varying chain. Declared here (the refusal half); the kernel's clamp is the enforcement half.
 * @see data/kernels/phaser.json
 */
export declare const PHASER_FEEDBACK_RANGE: {
  readonly min: -0.9;
  readonly max: 0.9;
  readonly step: 0.01;
  readonly unit: "";
  readonly default: 0.4;
  readonly defaultFrom: "desk";
};

/**
 * The phaser's wet/dry, as an instance of DRIVE_MIX_RANGE: 50 %, where the notch is complete (§3).
 * @see data/kernels/phaser.json
 */
export declare const PHASER_MIX_RANGE: {
  readonly min: 0;
  readonly max: 100;
  readonly step: 0.1;
  readonly unit: "%";
  readonly default: 50;
  readonly defaultFrom: "desk";
};

/**
 * The phaser's continuous travels by row field — the ONE map its control bounds and its row travels both read (§3). `stages` is not here: it moves through PHASER_STAGE_COUNTS.
 * @see data/kernels/phaser.json
 */
export declare const PHASER_TRAVELS: {
  readonly rateHz: {
    readonly min: 0.05;
    readonly max: 5;
    readonly step: 0.01;
    readonly unit: "Hz";
    readonly default: 0.5;
    readonly defaultFrom: "desk";
  };
  readonly baseHz: {
    readonly min: 50;
    readonly max: 2000;
    readonly step: 1;
    readonly unit: "Hz";
    readonly default: 200;
    readonly defaultFrom: "desk";
  };
  readonly depthOct: {
    readonly min: 0;
    readonly max: 6;
    readonly step: 0.1;
    readonly unit: "oct";
    readonly default: 4;
    readonly defaultFrom: "desk";
  };
  readonly feedback: {
    readonly min: -0.9;
    readonly max: 0.9;
    readonly step: 0.01;
    readonly unit: "";
    readonly default: 0.4;
    readonly defaultFrom: "desk";
  };
  readonly mix: {
    readonly min: 0;
    readonly max: 100;
    readonly step: 0.1;
    readonly unit: "%";
    readonly default: 50;
    readonly defaultFrom: "desk";
  };
};

/**
 * The highest frequency the phaser's all-pass sweep reaches, Hz.
 * @see data/kernels/phaser.json
 */
export declare const PHASER_F_TOP_HZ: 16000;

/**
 * PITCH_LIMITS, moved from openmixer.
 * @see data/kernels/pitch.json
 */
export declare const PITCH_LIMITS: {
  readonly semitones: {
    readonly min: -12;
    readonly max: 12;
    readonly default: 0;
  };
  readonly cents: {
    readonly min: -50;
    readonly max: 50;
    readonly default: 0;
  };
  readonly mix: {
    readonly min: 0;
    readonly max: 100;
    readonly default: 100;
  };
};

/**
 * PITCH_KERNEL, moved from openmixer.
 * @see data/kernels/pitch.json
 */
export declare const PITCH_KERNEL: {
  readonly windowMs: 40;
  readonly prefilterCeilingHz: 20000;
  readonly prefilterQ: 0.7071067811865476;
};

/**
 * PLATE's tank MODULATION DEPTH, in percent of Dattorro's own excursion (±8 samples at his 29 761 Hz tuning rate, scaled to the live rate the way the tank lengths are). 100 is the depth the plate has always run at, so the come-up is bit-identical to the plate before the field; 0 brings back the unmodulated tank's ring; 400 is the wide, chorused EMT-style swing. The rate stays 1 Hz. Only PLATE reads it (`2026-09-26-native-fx-catalogue.md` §2, Reverb).
 * @see data/kernels/reverb.json
 */
export declare const REVERB_PLATE_MOD_DEPTH_RANGE: {
  readonly min: 0;
  readonly max: 400;
  readonly step: 1;
  readonly unit: "%";
  readonly default: 100;
  readonly defaultFrom: "desk";
};

/**
 * The REVERB's wet/dry. An insert keeps the dry signal (0.3); an `fxReturn` is wet-only (1), so the return carries only the effect. Both numbers live HERE and nowhere else: the row's `mix` limit, `ReverbController`'s seed and its fresh state read them through limitForKind.
 * @see data/kernels/reverb.json
 */
export declare const REVERB_MIX_RANGE: {
  readonly min: 0;
  readonly max: 1;
  readonly step: 0;
  readonly unit: "";
  readonly default: 0.3;
  readonly defaultFrom: "desk";
  readonly byKind: {
    readonly fxReturn: 1;
  };
};

/**
 * The reverb's SIZE/DAMPING/WIDTH — each a NORMALIZED_RANGE instance with its own come-up value, matching `DEFAULT_REVERB_STATE`. Three separate constants rather than one shared default on `NORMALIZED_RANGE`: that range is the bare 0..1 REPRESENTATION, reused by fields across the whole console whose come-up values disagree (a fader position is not a reverb's damping), so a default belongs on the NAMED field, never on the shape it borrows.
 * @see data/kernels/reverb.json
 */
export declare const REVERB_SIZE_RANGE: {
  readonly min: 0;
  readonly max: 1;
  readonly step: 0;
  readonly unit: "";
  readonly default: 0.7;
  readonly defaultFrom: "desk";
};

/**
 * The reverb's DAMPING — a NORMALIZED_RANGE instance with its own come-up value, matching `DEFAULT_REVERB_STATE`. Declared with SIZE and WIDTH (see REVERB_SIZE_RANGE for why each is a named constant rather than a default on the shared 0..1 shape).
 * @see data/kernels/reverb.json
 */
export declare const REVERB_DAMPING_RANGE: {
  readonly min: 0;
  readonly max: 1;
  readonly step: 0;
  readonly unit: "";
  readonly default: 0.5;
  readonly defaultFrom: "desk";
};

/**
 * The reverb's stereo WIDTH — a NORMALIZED_RANGE instance with its own come-up value, matching `DEFAULT_REVERB_STATE`. Declared with SIZE and DAMPING (see REVERB_SIZE_RANGE for why each is a named constant rather than a default on the shared 0..1 shape).
 * @see data/kernels/reverb.json
 */
export declare const REVERB_WIDTH_RANGE: {
  readonly min: 0;
  readonly max: 1;
  readonly step: 0;
  readonly unit: "";
  readonly default: 1;
  readonly defaultFrom: "desk";
};

/**
 * The reverb's PRE-DELAY travel — the gap before the first reflection, in milliseconds. Declared here so the unit crosses with the bounds: a `finiteNumber(0, 100)` codec publishes `unit: ''`, and a surface binding that draws a millisecond control it cannot label. The panel knowing better than the wire is the wrong way round.
 * @see data/kernels/reverb.json
 */
export declare const REVERB_PREDELAY_RANGE: {
  readonly min: 0;
  readonly max: 100;
  readonly step: 1;
  readonly unit: "ms";
  readonly default: 0;
  readonly defaultFrom: "desk";
};

/**
 * The reverb's LOW cut, as an instance of REVERB_CUT_RANGE — same bounds, its own come-up value. `0` reads as "none" (`mix_reverb.h`), which is also `DEFAULT_REVERB_STATE`'s seed, so a fresh reverb's low cut and its declared default are the same fact stated once. Split from REVERB_CUT_RANGE rather than adding `default` there: the low and high cut share ONE travel (the C imposes one constraint on both) but do NOT share one come-up value, and a `default` on the shared range could only be honest for one of the two fields that read it.
 * @see data/kernels/reverb.json
 */
export declare const REVERB_LOWCUT_RANGE: {
  readonly min: 0;
  readonly max: 20000;
  readonly step: 10;
  readonly unit: "Hz";
  readonly default: 0;
  readonly defaultFrom: "desk";
};

/**
 * The reverb's HIGH cut, as an instance of REVERB_CUT_RANGE — same bounds, its own come-up value. The top of the travel reads as "open" (`mix_reverb.h`), matching `DEFAULT_REVERB_STATE`'s seed.
 * @see data/kernels/reverb.json
 */
export declare const REVERB_HIGHCUT_RANGE: {
  readonly min: 0;
  readonly max: 20000;
  readonly step: 10;
  readonly unit: "Hz";
  readonly default: 20000;
  readonly defaultFrom: "desk";
};

/**
 * REVERSE's MIRROR WINDOW — how long a slice of the wet is played backward, in milliseconds (`2026-07-15-native-delay-reverb.md`, Amendment 2026-09-17 §B). A DECLARED travel and never derived from `size`'s RT60: an RT60 of seconds cannot be buffered at 192 kHz, and a window silently clamped to fit is the silent-clamp defect. The ceiling is what `mix_reverb.h`'s pool budgets a ring for (`OMX_REVERB_REVERSE_MAX_MS`), so the console offers exactly the travel the kernel accepts — nothing wider, nothing narrower.
 * @see data/kernels/reverb.json
 */
export declare const REVERB_REVERSE_RANGE: {
  readonly min: 50;
  readonly max: 500;
  readonly step: 10;
  readonly unit: "ms";
  readonly default: 300;
  readonly defaultFrom: "desk";
};

/**
 * GATED's HOLD — how long the wet stays at full level after the key falls away, in milliseconds. The Phil-Collins tail is cut where the operator puts the cut, so this is the control that decides the effect's length; `size` still decides what is being cut off.
 * @see data/kernels/reverb.json
 */
export declare const REVERB_HOLD_RANGE: {
  readonly min: 10;
  readonly max: 2000;
  readonly step: 10;
  readonly unit: "ms";
  readonly default: 120;
  readonly defaultFrom: "desk";
};

/**
 * GATED's RELEASE — how long the held wet takes to reach zero, in milliseconds. A straight line down, short by design: a long release is a reverb tail again, which is the thing a gated reverb exists to remove.
 * @see data/kernels/reverb.json
 */
export declare const REVERB_RELEASE_RANGE: {
  readonly min: 1;
  readonly max: 500;
  readonly step: 1;
  readonly unit: "ms";
  readonly default: 20;
  readonly defaultFrom: "desk";
};

/**
 * GATED's ARM THRESHOLD — the level the reverb's own mono feed must reach to arm the hold, in dBFS. Declared, because the alternative is a hidden onset detector: the kernel compares `|input|` against exactly this number and nothing else.
 * @see data/kernels/reverb.json
 */
export declare const REVERB_GATE_THRESHOLD_RANGE: {
  readonly min: -80;
  readonly max: 0;
  readonly step: 1;
  readonly unit: "dBFS";
  readonly default: -40;
  readonly defaultFrom: "desk";
};

/**
 * The reverb's algorithms, in the order of the integer the kernel reads. Reverse and gated are the room network handed a window and a gate.
 * @see data/kernels/reverb.json
 */
export declare const REVERB_ALGORITHMS: readonly ["room", "plate", "hall", "reverse", "gated"];

/**
 * The gated reverb's gate attack, ms: the time the gate takes to open on a hit.
 * @see data/kernels/reverb.json
 */
export declare const REVERB_GATE_ATTACK_MS: 1.5;

/**
 * The horn's chorale (slow) rate, Hz.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_HORN_SLOW_RANGE: {
  readonly min: 0.1;
  readonly max: 2;
  readonly step: 0.01;
  readonly unit: "Hz";
  readonly default: 0.8;
  readonly defaultFrom: "desk";
};

/**
 * The horn's tremolo (fast) rate, Hz.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_HORN_FAST_RANGE: {
  readonly min: 3;
  readonly max: 10;
  readonly step: 0.01;
  readonly unit: "Hz";
  readonly default: 6.8;
  readonly defaultFrom: "desk";
};

/**
 * The drum's chorale (slow) rate, Hz.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_DRUM_SLOW_RANGE: {
  readonly min: 0.1;
  readonly max: 2;
  readonly step: 0.01;
  readonly unit: "Hz";
  readonly default: 0.7;
  readonly defaultFrom: "desk";
};

/**
 * The drum's tremolo (fast) rate, Hz.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_DRUM_FAST_RANGE: {
  readonly min: 3;
  readonly max: 10;
  readonly step: 0.01;
  readonly unit: "Hz";
  readonly default: 5.9;
  readonly defaultFrom: "desk";
};

/**
 * The scale on every speed-change time constant (`ROTARY_*_ACCEL_MS`/`_DECEL_MS`): 2 is twice as slow.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_ACCEL_RANGE: {
  readonly min: 0.25;
  readonly max: 4;
  readonly step: 0.01;
  readonly unit: "x";
  readonly default: 1;
  readonly defaultFrom: "desk";
};

/**
 * The drum/horn balance, percent: −100 drum only, +100 horn only; the law attenuates, never boosts.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_BALANCE_RANGE: {
  readonly min: -100;
  readonly max: 100;
  readonly step: 1;
  readonly unit: "%";
  readonly default: 0;
  readonly defaultFrom: "desk";
};

/**
 * The rotary's wet/dry, as an instance of DRIVE_MIX_RANGE: 100 %, because a rotary on an insert IS the sound (it replaces the cabinet) and an `fxReturn` wants it wet too (§3).
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_MIX_RANGE: {
  readonly min: 0;
  readonly max: 100;
  readonly step: 0.1;
  readonly unit: "%";
  readonly default: 100;
  readonly defaultFrom: "desk";
};

/**
 * The rotary's numeric travels, field → declaration: the ONE map the row's state, its bounds, its OPTIONS and its controller read (`speed` is a member set, ROTARY_SPEEDS, beside it).
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_TRAVELS: {
  readonly hornSlowHz: {
    readonly min: 0.1;
    readonly max: 2;
    readonly step: 0.01;
    readonly unit: "Hz";
    readonly default: 0.8;
    readonly defaultFrom: "desk";
  };
  readonly hornFastHz: {
    readonly min: 3;
    readonly max: 10;
    readonly step: 0.01;
    readonly unit: "Hz";
    readonly default: 6.8;
    readonly defaultFrom: "desk";
  };
  readonly drumSlowHz: {
    readonly min: 0.1;
    readonly max: 2;
    readonly step: 0.01;
    readonly unit: "Hz";
    readonly default: 0.7;
    readonly defaultFrom: "desk";
  };
  readonly drumFastHz: {
    readonly min: 3;
    readonly max: 10;
    readonly step: 0.01;
    readonly unit: "Hz";
    readonly default: 5.9;
    readonly defaultFrom: "desk";
  };
  readonly accel: {
    readonly min: 0.25;
    readonly max: 4;
    readonly step: 0.01;
    readonly unit: "x";
    readonly default: 1;
    readonly defaultFrom: "desk";
  };
  readonly balance: {
    readonly min: -100;
    readonly max: 100;
    readonly step: 1;
    readonly unit: "%";
    readonly default: 0;
    readonly defaultFrom: "desk";
  };
  readonly mix: {
    readonly min: 0;
    readonly max: 100;
    readonly step: 0.1;
    readonly unit: "%";
    readonly default: 100;
    readonly defaultFrom: "desk";
  };
};

/**
 * The complementary split's low-pass corner, Hz: the Leslie 122's passive crossover.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_CROSSOVER_HZ: 800;

/**
 * The shortest Doppler read, ms — above the order-3 read's one-sample reach at every rate.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_BASE_MS: 0.1;

/**
 * The horn's Doppler excursion `D_horn`, ms: a 0.15 m radius over 343 m/s.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_HORN_DOPPLER_MS: 0.44;

/**
 * The drum's Doppler excursion `D_drum`, ms: its baffle turns over a fixed woofer.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_DRUM_DOPPLER_MS: 0.29;

/**
 * The horn's amplitude swing `m_horn` (a −6 dB directivity dip), a ratio.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_HORN_AM: 0.5;

/**
 * The drum baffle's amplitude swing `m_drum`, a ratio.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_DRUM_AM: 0.3;

/**
 * The horn rotor's speed-up time constant, ms (at `accel` 1).
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_HORN_ACCEL_MS: 330;

/**
 * The horn rotor's slow-down time constant, ms (at `accel` 1).
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_HORN_DECEL_MS: 500;

/**
 * The drum rotor's speed-up time constant, ms (at `accel` 1).
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_DRUM_ACCEL_MS: 1700;

/**
 * The drum rotor's slow-down time constant, ms (at `accel` 1).
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_DRUM_DECEL_MS: 1800;

/**
 * Below this rate, Hz, a rotor coasting toward `stop` is snapped to exactly 0.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_STOP_EPS: 0.0001;

/**
 * One inline ring per rotor per leg, floats — at least the 192 kHz need of the horn's sweep.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_RING_FLOATS: 256;

/**
 * The rotary speaker's speed settings, in the order of the integer the kernel reads: the rotors stopped, at their chorale (slow) rate, or at their tremolo (fast) rate.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_SPEEDS: readonly ["stop", "slow", "fast"];

/**
 * The RTA's target bin resolution — generated into `omx_contract_limits.h` as `OMX_RTA_TARGET_BIN_HZ`, which `mix_dsp.h` reads; `rta-window-derivation.test.ts` reads it back from the header.
 * @see data/kernels/rta.json
 */
export declare const RTA_TARGET_BIN_HZ: 5.9;

/**
 * The largest RTA FFT the native ring holds — generated into `omx_contract_limits.h` as `OMX_RTA_FFT_SIZE_MAX`.
 * @see data/kernels/rta.json
 */
export declare const RTA_FFT_SIZE_MAX: 32768;

/**
 * The legal range of each transient-designer field (engineering units), transient spec §3. Every kind comes up flat: no per-kind default differs. `harness/contract-limits-gen.mjs` emits each as `OMX_TRANSIENT_<FIELD>_{MIN,MAX,DEFAULT}` for `mix_transient.h`'s resolve; the row publishes them on OPTIONS when it lands (issue #921).
 * @see data/kernels/transient.json
 */
export declare const TRANSIENT_LIMITS: {
  readonly attackDb: {
    readonly min: -24;
    readonly max: 24;
    readonly step: 0.1;
    readonly unit: "dB";
    readonly default: 0;
    readonly defaultFrom: "desk";
  };
  readonly sustainDb: {
    readonly min: -24;
    readonly max: 24;
    readonly step: 0.1;
    readonly unit: "dB";
    readonly default: 0;
    readonly defaultFrom: "desk";
  };
  readonly attackTimeMs: {
    readonly min: 2;
    readonly max: 50;
    readonly step: 0.1;
    readonly unit: "ms";
    readonly default: 10;
    readonly defaultFrom: "desk";
  };
  readonly sustainTimeMs: {
    readonly min: 50;
    readonly max: 2000;
    readonly step: 1;
    readonly unit: "ms";
    readonly default: 250;
    readonly defaultFrom: "desk";
  };
  readonly outputDb: {
    readonly min: -24;
    readonly max: 12;
    readonly step: 0.1;
    readonly unit: "dB";
    readonly default: 0;
    readonly defaultFrom: "desk";
  };
};

/**
 * The fast follower's attack, ms: exactly the dynamics detector's no-oversampling line (transient spec §3, L7).
 * @see data/kernels/transient.json
 */
export declare const TRANSIENT_FAST_ATTACK_MS: 0.5;

/**
 * The fast follower's release, ms: one 50 Hz cycle held, a 180 bpm sixteenth forgotten (transient spec §3).
 * @see data/kernels/transient.json
 */
export declare const TRANSIENT_FAST_RELEASE_MS: 20;

/**
 * The contrast, dB, at which a knob reaches its full value (transient spec §2, §3).
 * @see data/kernels/transient.json
 */
export declare const TRANSIENT_REF_DB: 6;

/**
 * The detector floor, linear (−100 dBFS): below it both envelopes read the floor and the stage is unity (transient spec §3).
 * @see data/kernels/transient.json
 */
export declare const TRANSIENT_FLOOR_LIN: 0.00001;

/**
 * The tremolo's LFO rate (the catalogue row's 0.1..20 Hz); 4 Hz is the classic amp tremolo.
 * @see data/kernels/tremolo.json
 */
export declare const TREMOLO_RATE_RANGE: {
  readonly min: 0.1;
  readonly max: 20;
  readonly step: 0.01;
  readonly unit: "Hz";
  readonly default: 4;
  readonly defaultFrom: "desk";
};

/**
 * The tremolo's modulation depth: the gain's trough is `1 − mix·depth`.
 * @see data/kernels/tremolo.json
 */
export declare const TREMOLO_DEPTH_RANGE: {
  readonly min: 0;
  readonly max: 100;
  readonly step: 0.1;
  readonly unit: "%";
  readonly default: 50;
  readonly defaultFrom: "desk";
};

/**
 * The tremolo's wet/dry, as an instance of DRIVE_MIX_RANGE: 100 %. The kernel folds the wet/dry into its one gain, so a strip tremolo IS the sound (as the rotary's mix 100 % is).
 * @see data/kernels/tremolo.json
 */
export declare const TREMOLO_MIX_RANGE: {
  readonly min: 0;
  readonly max: 100;
  readonly step: 0.1;
  readonly unit: "%";
  readonly default: 100;
  readonly defaultFrom: "desk";
};

/**
 * The tremolo's numeric travels, field → declaration: the ONE map the row's state, its bounds, its OPTIONS and its controller read (`mode` is a member set, TREMOLO_MODES, beside it).
 * @see data/kernels/tremolo.json
 */
export declare const TREMOLO_TRAVELS: {
  readonly rateHz: {
    readonly min: 0.1;
    readonly max: 20;
    readonly step: 0.01;
    readonly unit: "Hz";
    readonly default: 4;
    readonly defaultFrom: "desk";
  };
  readonly depth: {
    readonly min: 0;
    readonly max: 100;
    readonly step: 0.1;
    readonly unit: "%";
    readonly default: 50;
    readonly defaultFrom: "desk";
  };
  readonly mix: {
    readonly min: 0;
    readonly max: 100;
    readonly step: 0.1;
    readonly unit: "%";
    readonly default: 100;
    readonly defaultFrom: "desk";
  };
};

/**
 * What the tremolo's one oscillator modulates, in the order of the integer the kernel reads: the level of both legs in phase (tremolo), or the balance law's position with the legs in opposition (pan).
 * @see data/kernels/tremolo.json
 */
export declare const TREMOLO_MODES: readonly ["tremolo", "pan"];

/**
 * The Q of a second-order Butterworth section, 1/√2 — maximally flat, the one value every Butterworth biquad in the tree designs at: the LR4 crossover section, the pitch pre-filter and the drive's tilt / band / HF sections, in TS and (as `OMX_BUTTERWORTH_Q`) in C (§7, the scalar door).
 * @see data/primitives.json
 */
export declare const BUTTERWORTH_Q: 0.7071067811865476;

/**
 * ALLPASS_LIMITS, moved from openmixer.
 * @see data/primitives.json
 */
export declare const ALLPASS_LIMITS: {
  readonly unityTolerance: 0.0001;
};

/**
 * XOVER_LIMITS, moved from openmixer.
 * @see data/primitives.json
 */
export declare const XOVER_LIMITS: {
  readonly lr2SectionQ: 0.5;
  readonly lr4SectionQ: 0.7071067811865476;
  readonly partitionTolerance: 0.00001;
};

/**
 * The order the chorus and flanger construct their lines with (four taps; the fdelay spec §1).
 * @see data/primitives.json
 */
export declare const FDELAY_MOD_READ_ORDER: 3;

/**
 * `Λ` for the chorus/flanger read — ONE value; the header and every law read this.
 * @see data/primitives.json
 */
export declare const FDELAY_READ_L1_NORM: 1.25;

/**
 * The gate's threshold, range, release and ratio as a plugin host draws them: GATE_LIMITS' bounds, units and defaults with no step. The console's row quantises these four to whole steps (1 dB, 10 ms, 1:1), and a travel whose step is 1 or more reads as an integer control; the omx-strip plugin has always offered them continuous, so it reads this table instead. Every number but the step is GATE_LIMITS', held equal by test/continuous-travels.test.mjs. Not rendered to C: no C reader needs a second spelling of the gate's bounds.
 * @see data/primitives.json
 */
export declare const GATE_CONTINUOUS_TRAVELS: {
  readonly thresholdDb: {
    readonly min: -80;
    readonly max: 0;
    readonly step: 0;
    readonly unit: "dB";
    readonly default: -40;
    readonly defaultFrom: "desk";
  };
  readonly rangeDb: {
    readonly min: -90;
    readonly max: 0;
    readonly step: 0;
    readonly unit: "dB";
    readonly default: -90;
    readonly defaultFrom: "desk";
  };
  readonly releaseMs: {
    readonly min: 0;
    readonly max: 5000;
    readonly step: 0;
    readonly unit: "ms";
    readonly default: 100;
    readonly defaultFrom: "desk";
  };
  readonly ratio: {
    readonly min: 1;
    readonly max: 100;
    readonly step: 0;
    readonly unit: "";
    readonly default: 16;
    readonly defaultFrom: "desk";
  };
};

/**
 * The compressor's threshold and release as a plugin host draws them: COMP_LIMITS' bounds, units and defaults with no step. The console's row quantises them to whole steps (1 dB, 10 ms), and a travel whose step is 1 or more reads as an integer control; the omx-strip plugin has always offered them continuous, so it reads this table instead. Every number but the step is COMP_LIMITS', held equal by test/continuous-travels.test.mjs. Not rendered to C: no C reader needs a second spelling of the compressor's bounds.
 * @see data/primitives.json
 */
export declare const COMP_CONTINUOUS_TRAVELS: {
  readonly thresholdDb: {
    readonly min: -60;
    readonly max: 0;
    readonly step: 0;
    readonly unit: "dB";
    readonly default: -18;
    readonly defaultFrom: "desk";
  };
  readonly releaseMs: {
    readonly min: 5;
    readonly max: 3000;
    readonly step: 0;
    readonly unit: "ms";
    readonly default: 200;
    readonly defaultFrom: "desk";
  };
};

/**
 * The digital input trim as a travel: openmixer's TRIM_RANGE (packages/declarations, -24..+24 dB in 0.1 dB steps, spelled minDb/maxDb/stepDb there and OMX_TRIM_RANGE_*_DB in omx-dsp's header), coming up at 0 dB, the trim a channel has when none is set. The omx-strip plugin's trim reads it. A table with the one field `trimDb`, the name the trim row and the plugin store; not rendered to C, which already spells TRIM_RANGE its own way.
 * @see data/primitives.json
 */
export declare const TRIM_TRAVELS: {
  readonly trimDb: {
    readonly min: -24;
    readonly max: 24;
    readonly step: 0.1;
    readonly unit: "dB";
    readonly default: 0;
    readonly defaultFrom: "desk";
  };
};

/**
 * How a host draws a parameter: linear, logarithmic (a frequency, a time) or in discrete steps. The words omx-plugins' declarations and plugin-hostd's protocol use; a travel names its own with `scale`.
 * @see data/primitives.json
 */
export declare const PARAM_SCALES: readonly ["linear", "log", "stepped"];

/**
 * The EQ's three frequency travels as a host draws them: the band frequency, the high-pass corner and the low-pass corner, EQ_FREQ_RANGE's, HPF_FREQ_RANGE's and LPF_FREQ_RANGE's bounds with no step and a logarithmic scale. The console's EQ quantises frequency to 10 Hz; a frequency drags continuously on a log axis, which is how every host draws it, so this is the form the omx-plugins read. Every number but the step is the source's, held equal by test/continuous-travels.test.mjs. Not rendered to C: no C reader needs a second spelling of the EQ's bounds.
 * @see data/primitives.json
 */
export declare const EQ_CONTINUOUS_TRAVELS: {
  readonly freqHz: {
    readonly min: 20;
    readonly max: 20000;
    readonly step: 0;
    readonly unit: "Hz";
    readonly scale: "log";
  };
  readonly hpfFreqHz: {
    readonly min: 20;
    readonly max: 1000;
    readonly step: 0;
    readonly unit: "Hz";
    readonly scale: "log";
  };
  readonly lpfFreqHz: {
    readonly min: 1000;
    readonly max: 20000;
    readonly step: 0;
    readonly unit: "Hz";
    readonly scale: "log";
  };
};

/**
 * The standard sample rates (Hz) the desk recognises — the pro-audio superset. One source of truth for the clock controller's `clock.allowed-rates` seed, the force row's validation ceiling and the device-rate probe fallback. What the operator is OFFERED is always the DEVICE's own `supportedRates` (`2026-07-15-clock-rate-honest-force-rate.md`) — this is the ceiling a write is refused by, never a menu.
 * @see data/rates.json
 */
export declare const STANDARD_SAMPLE_RATES: readonly [44100, 48000, 88200, 96000, 176400, 192000];

/**
 * THE declaration: 192 kHz at quantum 128.
 * @see data/rates.json
 */
export declare const RT_HARD_TARGET: {
  readonly rate: 192000;
  readonly quantum: 128;
};

/**
 * The rate a unit-range DSP knob is quoted at (R-058): the rate this desk runs (ruling 2026-09-14). A kernel raises the knob to `REF / sr`, so at this rate the exponent is exactly 1 and the response is bit-for-bit the one cut before the law. Emitted to C as `OMX_DSP_KNOB_REFERENCE_RATE`; the reverb damping and FX-delay tone references `#define` from it.
 * @see data/rates.json
 */
export declare const DSP_KNOB_REFERENCE_RATE: 96000;

/**
 * The four rates every kernel oracle runs at, whatever STANDARD_SAMPLE_RATES says: a declared list missing one of them stops a suite instead of testing less (omx-dsp, omx-plugins and omx-clap-host run their oracles at these).
 * @see data/rates.json
 */
export declare const ORACLE_FLOOR_RATES: readonly [44100, 48000, 96000, 192000];

/**
 * The nine rates an RME interface clocks at, 32 to 192 kHz. STANDARD_SAMPLE_RATES is a subset of them; an oracle that runs here also covers 32, 64 and 128 kHz, where a kernel still has to meet its closed form even though the console never asks for them.
 * @see data/rates.json
 */
export declare const RME_RATES: readonly [32000, 44100, 48000, 64000, 88200, 96000, 128000, 176400, 192000];

/** The default band centres (Hz) of an EQ with `count` bands: THE one rule, for every strip, host and count. */
export declare function eqDefaultCentres(count: number): number[];
/** The default band types, by EQ_BAND_TYPES id: a low shelf, bells, a high shelf (a single band is a bell). */
export declare function eqDefaultTypes(count: number): string[];
/** Every default band of an EQ with `count` bands: type, centre, gain and Q. */
export declare function eqDefaultBands(count: number): { type: string; freqHz: number; gainDb: number; q: number }[];
