// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com>
// GENERATED by `omx-contract render --target ts` from FreeMixer/omx-contract's data/ — do not edit.

/**
 * The chorus's right-leg phase offset, in TURNS of its one oscillator (§2, §3a; the native-FX catalogue's M32 Dimension row). The right leg's voice k reads the LFO at k/N + spread: 0 is both legs one phase (the stage without the field, bit for bit), 0.25 quadrature, 0.5 the Dimension's opposed sweep. A fraction of a cycle carries no engineering symbol, so the unit is ''.
 * @see data/kernels/chorus.json
 */
export declare const CHORUS_SPREAD_RANGE: {
  readonly min: 0;
  readonly max: 0.5;
  readonly step: 0.01;
  readonly unit: "";
  readonly default: 0;
  readonly defaultFrom: "desk";
};

/**
 * The legal range of each compressor field (engineering units). The widget clamps drags to these, `normalizeComp` enforces them, the row's codec refuses by them and the travel sheet publishes them. `default`/`defaultFrom` are the come-up values `defaultCompState` seeds a fresh strip with, read BACK from here rather than restated there.
 * @see data/kernels/comp.json
 */
export declare const COMP_LIMITS: {
  readonly thresholdDb: {
    readonly min: -60;
    readonly max: 0;
    readonly step: 1;
    readonly unit: "dB";
    readonly default: -18;
    readonly defaultFrom: "desk";
  };
  readonly ratio: {
    readonly min: 1;
    readonly max: 20;
    readonly step: 0.5;
    readonly unit: "";
    readonly default: 4;
    readonly defaultFrom: "desk";
  };
  readonly kneeDb: {
    readonly min: 0;
    readonly max: 24;
    readonly step: 0.5;
    readonly unit: "dB";
    readonly default: 6;
    readonly defaultFrom: "desk";
  };
  readonly attackMs: {
    readonly min: 0.1;
    readonly max: 100;
    readonly step: 1;
    readonly unit: "ms";
    readonly default: 5;
    readonly defaultFrom: "desk";
  };
  readonly releaseMs: {
    readonly min: 5;
    readonly max: 3000;
    readonly step: 10;
    readonly unit: "ms";
    readonly default: 200;
    readonly defaultFrom: "desk";
  };
  readonly makeupDb: {
    readonly min: 0;
    readonly max: 24;
    readonly step: 0.5;
    readonly unit: "dB";
    readonly default: 0;
    readonly defaultFrom: "desk";
  };
  readonly mixPct: {
    readonly min: 0;
    readonly max: 100;
    readonly step: 5;
    readonly unit: "%";
    readonly default: 100;
    readonly defaultFrom: "desk";
  };
};

/**
 * The program-dependent release's model constants — the LA-2A's opto cell as DATA (`docs/design/specs/2026-09-26-compressor-models.md` §3b). `chargeMs`/`dischargeMs` are the word's memory constants, shared by every profile; each profile's `fastMs`, `slowMinMs`, `slowMaxMs` and `share` fit the unit's published two-stage recovery. Not operator controls: generated into `omx_contract_limits.h` as `OMX_PROGRAM_RELEASE_*`, which libomxdsp's `omx_env_program_release` reads.
 * @see data/kernels/comp.json
 */
export declare const PROGRAM_RELEASE: {
  readonly chargeMs: 1000;
  readonly dischargeMs: 5000;
  readonly profiles: {
    readonly opto: {
      readonly fastMs: 70;
      readonly slowMinMs: 110;
      readonly slowMaxMs: 1100;
      readonly share: 0.5;
    };
  };
};

/**
 * The detector band's CENTRE, in Hz. Sibilance lives at 5–10 kHz on most voices; 7 kHz with the default width covers 4 950–9 900 Hz, which is where an "s" and a "t" sit on a close vocal mic. The travel is wider than the come-up on both sides on purpose: a bright female vocal wants the band up near 9 kHz and a chesty male one down at 5, and a surface narrower than the row removes reach the console genuinely has (the same reasoning core's `REVERB_CUT_RANGE` records).
 * @see data/kernels/deesser.json
 */
export declare const DEESS_FREQ_RANGE: {
  readonly min: 2000;
  readonly max: 16000;
  readonly step: 10;
  readonly unit: "Hz";
  readonly default: 7000;
  readonly defaultFrom: "desk";
};

/**
 * The band's WIDTH, in OCTAVES around the centre: the edges are `f / 2^(w/2)` and `f · 2^(w/2)`, which is what makes the centre the geometric middle at every width. Octaves and not a Q, because a Q is a property of one section and this band is TWO (a highpass and a lowpass, `mix_deesser.h`) — an operator asked to dial a Q would be dialling a number neither filter carries. One octave is the classic de-esser band: wide enough for a sibilant that moves with the vowel, narrow enough that a 1 kHz vowel sits 27.8 dB down the skirt.
 * @see data/kernels/deesser.json
 */
export declare const DEESS_WIDTH_RANGE: {
  readonly min: 0.25;
  readonly max: 4;
  readonly step: 0.05;
  readonly unit: "oct";
  readonly default: 1;
  readonly defaultFrom: "desk";
};

/**
 * Where reduction starts — the level of the BAND, not of the strip, which is why the come-up is so much lower than the compressor's. A vocal peaking −12 dBFS carries roughly −30 dBFS in a one-octave band at 7 kHz on its sibilants and under −40 on its vowels, so −30 sits between the two and the stage opens on an "s" and stays shut on an "ah".
 * @see data/kernels/deesser.json
 */
export declare const DEESS_THRESHOLD_RANGE: {
  readonly min: -60;
  readonly max: 0;
  readonly step: 0.5;
  readonly unit: "dB";
  readonly default: -30;
  readonly defaultFrom: "desk";
};

/**
 * How hard the band is held once it is over the threshold. 4:1 is the textbook de-esser ratio: firm on the "s", short of a limiter.
 * @see data/kernels/deesser.json
 */
export declare const DEESS_RATIO_RANGE: {
  readonly min: 1;
  readonly max: 20;
  readonly step: 0.1;
  readonly unit: "";
  readonly default: 4;
  readonly defaultFrom: "desk";
};

/**
 * The FLOOR on the reduction, in dB and never positive — the deepest cut the stage may reach however loud the sibilant is (`mix_deesser.h`'s clamp, §4c). 12 dB tames a hard sibilant; past that a voice starts to lisp, and a de-esser with NO floor turns a shouted "s" into a hole. The ceiling is 0, which switches the reduction off without switching the stage off — a legitimate thing to want while dialling the band in by ear.
 * @see data/kernels/deesser.json
 */
export declare const DEESS_RANGE_RANGE: {
  readonly min: -24;
  readonly max: 0;
  readonly step: 0.5;
  readonly unit: "dB";
  readonly default: -12;
  readonly defaultFrom: "desk";
};

/**
 * The detector's ATTACK, in ms. A sibilant's onset is a few milliseconds; 1 ms catches it without the detector chattering on the band's own waveform.
 * @see data/kernels/deesser.json
 */
export declare const DEESS_ATTACK_RANGE: {
  readonly min: 0.1;
  readonly max: 50;
  readonly step: 0.1;
  readonly unit: "ms";
  readonly default: 1;
  readonly defaultFrom: "desk";
};

/**
 * The detector's RELEASE, in ms. 60 ms is long enough not to modulate inside one "s" and short enough to be open again for the next syllable.
 * @see data/kernels/deesser.json
 */
export declare const DEESS_RELEASE_RANGE: {
  readonly min: 5;
  readonly max: 500;
  readonly step: 1;
  readonly unit: "ms";
  readonly default: 60;
  readonly defaultFrom: "desk";
};

/**
 * The knee, in dB — a CONSTANT of the stage and not a row field (`2026-09-22-native-deesser-stage.md` §4b): a de-esser without a soft knee latches audibly on the first sibilant of a phrase, and no other value of this number is a de-esser anyone would dial. The controller pushes it to the node and this is the same number; a second spelling would be a picture that disagrees with the audio about where the reduction starts.
 * @see data/kernels/deesser.json
 */
export declare const DEESS_KNEE_DB: 6;

/**
 * The FX delay's time travel. `max` is the NATIVE ring's ceiling — the same number as `OMX_FXDELAY_MAX_MS` in `omx_delay.h`, pinned to it by `output-delay-ceiling.test.ts`. Distinct from the per-route ALIGNMENT delay (`OUTPUT_DELAY_RANGE`, 1 s, `OMX_DELAY_MAX_MS`): one is a musical echo with feedback and mix, the other is a pure latency. Two facts, two rings, two ceilings — sharing the word "delay" is why they keep being confused for each other.
 * @see data/kernels/delay.json
 */
export declare const FX_DELAY_TIME_RANGE: {
  readonly min: 0;
  readonly max: 2000;
  readonly step: 1;
  readonly unit: "ms";
  readonly default: 300;
  readonly defaultFrom: "desk";
};

/**
 * The FX delay's REGENERATION travel — how much of the wet tail feeds back in. Stops short of 1: unity feedback is a runaway the kernel hard-clamps anyway, so offering it would draw travel the DSP refuses. Not NORMALIZED_RANGE for exactly that reason — it is a 0..1 quantity whose top the DSP does not accept, and a control must not offer a value its actuator will eat.
 * @see data/kernels/delay.json
 */
export declare const FX_DELAY_FEEDBACK_RANGE: {
  readonly min: 0;
  readonly max: 0.99;
  readonly step: 0;
  readonly unit: "";
  readonly default: 0.3;
  readonly defaultFrom: "desk";
};

/**
 * The FX delay's TONE — a NORMALIZED_RANGE instance with its own come-up value, matching `DEFAULT_DELAY_STATE.tone`. See REVERB_SIZE_RANGE for why this is a named constant rather than a default on the shared shape.
 * @see data/kernels/delay.json
 */
export declare const DELAY_TONE_RANGE: {
  readonly min: 0;
  readonly max: 1;
  readonly step: 0;
  readonly unit: "";
  readonly default: 0.3;
  readonly defaultFrom: "desk";
};

/**
 * The FX DELAY's wet/dry — the same split as REVERB_MIX_RANGE, its own declaration.
 * @see data/kernels/delay.json
 */
export declare const DELAY_MIX_RANGE: {
  readonly min: 0;
  readonly max: 1;
  readonly step: 0;
  readonly unit: "";
  readonly default: 0.3;
  readonly defaultFrom: "desk";
  readonly byKind: {
    readonly fxReturn: 1;
  };
};

/**
 * The FX delay's PING-PONG come-up value — a toggle, so it has no travel, only this. Declared here rather than as a literal in the server's `DEFAULT_DELAY_STATE` (which now reads it) so the DPF plugin generator (`packages/omx-plugins/tools/params-gen.mjs`, `2026-09-25-omx-plugins-dpf.md` §3a) reads the same fact the desk seeds a fresh strip with.
 * @see data/kernels/delay.json
 */
export declare const FX_DELAY_PINGPONG_DEFAULT: false;

/**
 * The bias at `character = +1`, in the SHAPER's own input units — `OMX_DRIVE_BIAS_MAX`. DERIVED, not chosen (§4b). In the saturating limit every knee tends to `sgn`, the output is a rectangular wave of duty `d = ½ + asin(b)/π`, and its `n`th harmonic goes as `sin(nπd)/n` — so `|H2|` is maximal at `d = ¾`, which is `b = sin(π/4) = 1/√2` exactly. Measured too: the H2-maximising bias for a full-scale sine at unity drive is 0.712 (soft), 0.658 (tape), 0.645 (tube), and this one value costs 0.000 / 0.035 / 0.088 dB of H2 against each curve's own optimum. ONE normalised bias for all three knees, not three.
 * @see data/kernels/drive.json
 */
export declare const DRIVE_BIAS_MAX: 0.7071067811865476;

/**
 * The maximum number of parametric bands a channel EQ may hold — the operator can add up to this many. Generated into `omx_contract_limits.h` as `OMX_EQ_MAX_BANDS`, which `omx_biquad.h` reads (`output-delay-ceiling.test.ts` reads the header): the native lane allocates exactly this many biquad slots per channel and silently clamps above it, so the model, the wire, and the DSP agree by test, not by memory.
 * @see data/kernels/eq.json
 */
export declare const EQ_MAX_BANDS: 24;

/**
 * The standard ISO 266 one-third-octave centre frequencies, 20 Hz–20 kHz (31 bands) — the classic 31-band graphic-EQ layout's centres.
 * @see data/kernels/eq.json
 */
export declare const ISO_THIRD_OCTAVE_CENTRES_HZ: readonly [20, 25, 31.5, 40, 50, 63, 80, 100, 125, 160, 200, 250, 315, 400, 500, 630, 800, 1000, 1250, 1600, 2000, 2500, 3150, 4000, 5000, 6300, 8000, 10000, 12500, 16000, 20000];

/**
 * The graphic EQ's section count: DERIVED from ISO_THIRD_OCTAVE_CENTRES_HZ, never a second literal. Generated into `omx_contract_limits.h` as `OMX_GEQ_BANDS`, which sizes `mix_geq.h`'s section array — its OWN budget, never a claimant on EQ_MAX_BANDS (graphic-eq-31 spec §3, roster ruling 3).
 * @see data/kernels/eq.json
 */
export declare const GEQ_BANDS: 31;

/**
 * The flanger's jet sweep (§3b).
 * @see data/kernels/flanger.json
 */
export declare const FLANGER_RATE_RANGE: {
  readonly min: 0.05;
  readonly max: 5;
  readonly step: 0.01;
  readonly unit: "Hz";
  readonly default: 0.25;
  readonly defaultFrom: "desk";
};

/**
 * The flanger's peak-to-peak excursion above its declared 0.5 ms base (§3b).
 * @see data/kernels/flanger.json
 */
export declare const FLANGER_DEPTH_RANGE: {
  readonly min: 0;
  readonly max: 5;
  readonly step: 0.1;
  readonly unit: "ms";
  readonly default: 2;
  readonly defaultFrom: "desk";
};

/**
 * The flanger's SIGNED resonance (§3b). The ±0.95 clamp is DECLARED here — a PATCH asking for 1.0 is answered by this travel — and the kernel's own clamp is the enforcement half.
 * @see data/kernels/flanger.json
 */
export declare const FLANGER_FEEDBACK_RANGE: {
  readonly min: -0.95;
  readonly max: 0.95;
  readonly step: 0.01;
  readonly unit: "";
  readonly default: 0.6;
  readonly defaultFrom: "desk";
};

/**
 * The flanger's wet/dry, as an instance of DRIVE_MIX_RANGE: 50 %, equal dry and wet, where the comb is deepest (§3b).
 * @see data/kernels/flanger.json
 */
export declare const FLANGER_MIX_RANGE: {
  readonly min: 0;
  readonly max: 100;
  readonly step: 0.1;
  readonly unit: "%";
  readonly default: 50;
  readonly defaultFrom: "desk";
};

/**
 * The legal range of each gate field (engineering units). The widget clamps drags to these, `normalizeGate` enforces them, the row's codec refuses by them and the travel sheet publishes them — one source of truth. `rangeDb` reaches GATE_RANGE_FLOOR_DB, shown as "−∞" in readouts (a gate fully closed is silence).
 * @see data/kernels/gate.json
 */
export declare const GATE_LIMITS: {
  readonly thresholdDb: {
    readonly min: -80;
    readonly max: 0;
    readonly step: 1;
    readonly unit: "dB";
    readonly default: -40;
    readonly defaultFrom: "desk";
  };
  readonly rangeDb: {
    readonly min: -90;
    readonly max: 0;
    readonly step: 1;
    readonly unit: "dB";
    readonly default: -90;
    readonly defaultFrom: "desk";
  };
  readonly kneeStartDb: {
    readonly min: -80;
    readonly max: 0;
    readonly step: 1;
    readonly unit: "dB";
    readonly default: -43;
    readonly defaultFrom: "desk";
  };
  readonly kneeEndDb: {
    readonly min: -80;
    readonly max: 0;
    readonly step: 1;
    readonly unit: "dB";
    readonly default: -37;
    readonly defaultFrom: "desk";
  };
  readonly attackMs: {
    readonly min: 0;
    readonly max: 500;
    readonly step: 0.5;
    readonly unit: "ms";
    readonly default: 1;
    readonly defaultFrom: "desk";
  };
  readonly holdMs: {
    readonly min: 0;
    readonly max: 2000;
    readonly step: 5;
    readonly unit: "ms";
    readonly default: 10;
    readonly defaultFrom: "desk";
  };
  readonly releaseMs: {
    readonly min: 0;
    readonly max: 5000;
    readonly step: 10;
    readonly unit: "ms";
    readonly default: 100;
    readonly defaultFrom: "desk";
  };
  readonly hysteresisDb: {
    readonly min: 0;
    readonly max: 24;
    readonly step: 0.5;
    readonly unit: "dB";
    readonly default: 3;
    readonly defaultFrom: "desk";
  };
  readonly ratio: {
    readonly min: 1;
    readonly max: 100;
    readonly step: 1;
    readonly unit: "";
    readonly default: 16;
    readonly defaultFrom: "desk";
  };
};

/**
 * One graphic-EQ fader's travel: EQ_GAIN_RANGE by reference (a graphic fader is an EQ gain), with the come-up value it needs as a row field — flat, 0 dB (graphic-eq-31 spec §3).
 * @see data/kernels/geq.json
 */
export declare const GEQ_BAND_RANGE: {
  readonly min: -15;
  readonly max: 15;
  readonly step: 0.5;
  readonly unit: "dB";
  readonly default: 0;
  readonly defaultFrom: "desk";
};

/**
 * The graphic EQ's band Q: the ISO third-octave bandwidth, `2^(1/6)/(2^(1/3) − 1) ≈ 4.318`, to one decimal as the M32 GEQ carries it. Read by the `geq31` preset and the graphic EQ's section design (graphic-eq-31 spec §3).
 * @see data/kernels/geq.json
 */
export declare const GEQ_BAND_Q: 4.3;

/**
 * The prototype gain the `true` solve's first interaction matrix is evaluated at (spec §2, §3): the middle of the travel's magnitude, where a matched-Z section's dB response per dB of gain is closest to its average.
 * @see data/kernels/geq.json
 */
export declare const GEQ_PROTO_DB: 12;

/**
 * The ceiling on a section gain the `true` solve may ask for (spec §3): above the travel's worst case (26.0 dB, the alternating ±15 set) with margin. A solve past it clamps and the row says so (`designClamped`), never silently.
 * @see data/kernels/geq.json
 */
export declare const GEQ_DESIGN_GAIN_MAX_DB: 30;

/**
 * The precision limiter's travels (`2026-09-27-precision-limiter.md` §2), rendered into `omx_contract_limits.h` as `OMX_LIMITER_*` by `harness/contract-limits-gen.mjs`, so `mix_limiter.h` reads them and never restates one (R-094). The ceiling is a TRUE peak in dBFS (the ×4 detector); the look-ahead sets the declared latency; the release is the envelope's time constant on the gain depth.
 * @see data/kernels/limiter.json
 */
export declare const LIMITER_LIMITS: {
  readonly ceilingDb: {
    readonly min: -12;
    readonly max: 0;
    readonly step: 0.1;
    readonly unit: "dBFS";
    readonly default: -1;
    readonly defaultFrom: "desk";
  };
  readonly lookaheadMs: {
    readonly min: 0.5;
    readonly max: 5;
    readonly step: 0.1;
    readonly unit: "ms";
    readonly default: 1.5;
    readonly defaultFrom: "desk";
  };
  readonly releaseMs: {
    readonly min: 1;
    readonly max: 1000;
    readonly step: 1;
    readonly unit: "ms";
    readonly default: 50;
    readonly defaultFrom: "desk";
  };
};

/**
 * The phaser's sweep speed (§3). `omx_lfo_inc` freezes at Nyquist; this travel stays far below.
 * @see data/kernels/phaser.json
 */
export declare const PHASER_RATE_RANGE: {
  readonly min: 0.05;
  readonly max: 5;
  readonly step: 0.01;
  readonly unit: "Hz";
  readonly default: 0.5;
  readonly defaultFrom: "desk";
};

/**
 * The phaser's lowest centre frequency; the sweep runs upward from it (§3).
 * @see data/kernels/phaser.json
 */
export declare const PHASER_BASE_RANGE: {
  readonly min: 50;
  readonly max: 2000;
  readonly step: 1;
  readonly unit: "Hz";
  readonly default: 200;
  readonly defaultFrom: "desk";
};

/**
 * The sweep's span above `base`, in octaves; 0 is a static phaser at `base` (§3).
 * @see data/kernels/phaser.json
 */
export declare const PHASER_DEPTH_RANGE: {
  readonly min: 0;
  readonly max: 6;
  readonly step: 0.1;
  readonly unit: "oct";
  readonly default: 4;
  readonly defaultFrom: "desk";
};

/**
 * The phaser's section count per leg — EVEN, 2 … 12 (§2: two sections per notch). Its ends are the kernel's state capacity (`OMX_PHASER_MAX_STAGES` reads `OMX_PHASER_STAGES_RANGE_MAX`); the row moves it through the closed member set PHASER_STAGE_COUNTS, which is derived from it.
 * @see data/kernels/phaser.json
 */
export declare const PHASER_STAGES_RANGE: {
  readonly min: 2;
  readonly max: 12;
  readonly step: 2;
  readonly unit: "";
  readonly default: 6;
  readonly defaultFrom: "desk";
};

/**
 * The member set the `stages` field accepts: PHASER_STAGES_RANGE walked by its step.
 * @see data/kernels/phaser.json
 */
export declare const PHASER_STAGE_COUNTS: readonly [2, 4, 6, 8, 10, 12];

/**
 * The phaser's SIGNED resonance (§3). ±0.9, tighter than the flanger's ±0.95: the loop runs through a time-varying chain. Declared here (the refusal half); the kernel's clamp is the enforcement half.
 * @see data/kernels/phaser.json
 */
export declare const PHASER_FEEDBACK_RANGE: {
  readonly min: -0.9;
  readonly max: 0.9;
  readonly step: 0.01;
  readonly unit: "";
  readonly default: 0.4;
  readonly defaultFrom: "desk";
};

/**
 * The phaser's wet/dry, as an instance of DRIVE_MIX_RANGE: 50 %, where the notch is complete (§3).
 * @see data/kernels/phaser.json
 */
export declare const PHASER_MIX_RANGE: {
  readonly min: 0;
  readonly max: 100;
  readonly step: 0.1;
  readonly unit: "%";
  readonly default: 50;
  readonly defaultFrom: "desk";
};

/**
 * The phaser's continuous travels by row field — the ONE map its control bounds and its row travels both read (§3). `stages` is not here: it moves through PHASER_STAGE_COUNTS.
 * @see data/kernels/phaser.json
 */
export declare const PHASER_TRAVELS: {
  readonly rateHz: {
    readonly min: 0.05;
    readonly max: 5;
    readonly step: 0.01;
    readonly unit: "Hz";
    readonly default: 0.5;
    readonly defaultFrom: "desk";
  };
  readonly baseHz: {
    readonly min: 50;
    readonly max: 2000;
    readonly step: 1;
    readonly unit: "Hz";
    readonly default: 200;
    readonly defaultFrom: "desk";
  };
  readonly depthOct: {
    readonly min: 0;
    readonly max: 6;
    readonly step: 0.1;
    readonly unit: "oct";
    readonly default: 4;
    readonly defaultFrom: "desk";
  };
  readonly feedback: {
    readonly min: -0.9;
    readonly max: 0.9;
    readonly step: 0.01;
    readonly unit: "";
    readonly default: 0.4;
    readonly defaultFrom: "desk";
  };
  readonly mix: {
    readonly min: 0;
    readonly max: 100;
    readonly step: 0.1;
    readonly unit: "%";
    readonly default: 50;
    readonly defaultFrom: "desk";
  };
};

/**
 * PITCH_LIMITS, moved from openmixer.
 * @see data/kernels/pitch.json
 */
export declare const PITCH_LIMITS: {
  readonly semitones: {
    readonly min: -12;
    readonly max: 12;
    readonly default: 0;
  };
  readonly cents: {
    readonly min: -50;
    readonly max: 50;
    readonly default: 0;
  };
  readonly mix: {
    readonly min: 0;
    readonly max: 100;
    readonly default: 100;
  };
};

/**
 * PITCH_KERNEL, moved from openmixer.
 * @see data/kernels/pitch.json
 */
export declare const PITCH_KERNEL: {
  readonly windowMs: 40;
  readonly prefilterCeilingHz: 20000;
  readonly prefilterQ: 0.7071067811865476;
};

/**
 * PLATE's tank MODULATION DEPTH, in percent of Dattorro's own excursion (±8 samples at his 29 761 Hz tuning rate, scaled to the live rate the way the tank lengths are). 100 is the depth the plate has always run at, so the come-up is bit-identical to the plate before the field; 0 brings back the unmodulated tank's ring; 400 is the wide, chorused EMT-style swing. The rate stays 1 Hz. Only PLATE reads it (`2026-09-26-native-fx-catalogue.md` §2, Reverb).
 * @see data/kernels/reverb.json
 */
export declare const REVERB_PLATE_MOD_DEPTH_RANGE: {
  readonly min: 0;
  readonly max: 400;
  readonly step: 1;
  readonly unit: "%";
  readonly default: 100;
  readonly defaultFrom: "desk";
};

/**
 * The horn's chorale (slow) rate, Hz.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_HORN_SLOW_RANGE: {
  readonly min: 0.1;
  readonly max: 2;
  readonly step: 0.01;
  readonly unit: "Hz";
  readonly default: 0.8;
  readonly defaultFrom: "desk";
};

/**
 * The horn's tremolo (fast) rate, Hz.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_HORN_FAST_RANGE: {
  readonly min: 3;
  readonly max: 10;
  readonly step: 0.01;
  readonly unit: "Hz";
  readonly default: 6.8;
  readonly defaultFrom: "desk";
};

/**
 * The drum's chorale (slow) rate, Hz.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_DRUM_SLOW_RANGE: {
  readonly min: 0.1;
  readonly max: 2;
  readonly step: 0.01;
  readonly unit: "Hz";
  readonly default: 0.7;
  readonly defaultFrom: "desk";
};

/**
 * The drum's tremolo (fast) rate, Hz.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_DRUM_FAST_RANGE: {
  readonly min: 3;
  readonly max: 10;
  readonly step: 0.01;
  readonly unit: "Hz";
  readonly default: 5.9;
  readonly defaultFrom: "desk";
};

/**
 * The scale on every speed-change time constant (`ROTARY_*_ACCEL_MS`/`_DECEL_MS`): 2 is twice as slow.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_ACCEL_RANGE: {
  readonly min: 0.25;
  readonly max: 4;
  readonly step: 0.01;
  readonly unit: "x";
  readonly default: 1;
  readonly defaultFrom: "desk";
};

/**
 * The drum/horn balance, percent: −100 drum only, +100 horn only; the law attenuates, never boosts.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_BALANCE_RANGE: {
  readonly min: -100;
  readonly max: 100;
  readonly step: 1;
  readonly unit: "%";
  readonly default: 0;
  readonly defaultFrom: "desk";
};

/**
 * The rotary's wet/dry, as an instance of DRIVE_MIX_RANGE: 100 %, because a rotary on an insert IS the sound (it replaces the cabinet) and an `fxReturn` wants it wet too (§3).
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_MIX_RANGE: {
  readonly min: 0;
  readonly max: 100;
  readonly step: 0.1;
  readonly unit: "%";
  readonly default: 100;
  readonly defaultFrom: "desk";
};

/**
 * The rotary's numeric travels, field → declaration: the ONE map the row's state, its bounds, its OPTIONS and its controller read (`speed` is a member set, ROTARY_SPEEDS, beside it).
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_TRAVELS: {
  readonly hornSlowHz: {
    readonly min: 0.1;
    readonly max: 2;
    readonly step: 0.01;
    readonly unit: "Hz";
    readonly default: 0.8;
    readonly defaultFrom: "desk";
  };
  readonly hornFastHz: {
    readonly min: 3;
    readonly max: 10;
    readonly step: 0.01;
    readonly unit: "Hz";
    readonly default: 6.8;
    readonly defaultFrom: "desk";
  };
  readonly drumSlowHz: {
    readonly min: 0.1;
    readonly max: 2;
    readonly step: 0.01;
    readonly unit: "Hz";
    readonly default: 0.7;
    readonly defaultFrom: "desk";
  };
  readonly drumFastHz: {
    readonly min: 3;
    readonly max: 10;
    readonly step: 0.01;
    readonly unit: "Hz";
    readonly default: 5.9;
    readonly defaultFrom: "desk";
  };
  readonly accel: {
    readonly min: 0.25;
    readonly max: 4;
    readonly step: 0.01;
    readonly unit: "x";
    readonly default: 1;
    readonly defaultFrom: "desk";
  };
  readonly balance: {
    readonly min: -100;
    readonly max: 100;
    readonly step: 1;
    readonly unit: "%";
    readonly default: 0;
    readonly defaultFrom: "desk";
  };
  readonly mix: {
    readonly min: 0;
    readonly max: 100;
    readonly step: 0.1;
    readonly unit: "%";
    readonly default: 100;
    readonly defaultFrom: "desk";
  };
};

/**
 * The complementary split's low-pass corner, Hz: the Leslie 122's passive crossover.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_CROSSOVER_HZ: 800;

/**
 * The shortest Doppler read, ms — above the order-3 read's one-sample reach at every rate.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_BASE_MS: 0.1;

/**
 * The horn's Doppler excursion `D_horn`, ms: a 0.15 m radius over 343 m/s.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_HORN_DOPPLER_MS: 0.44;

/**
 * The drum's Doppler excursion `D_drum`, ms: its baffle turns over a fixed woofer.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_DRUM_DOPPLER_MS: 0.29;

/**
 * The horn's amplitude swing `m_horn` (a −6 dB directivity dip), a ratio.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_HORN_AM: 0.5;

/**
 * The drum baffle's amplitude swing `m_drum`, a ratio.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_DRUM_AM: 0.3;

/**
 * The horn rotor's speed-up time constant, ms (at `accel` 1).
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_HORN_ACCEL_MS: 330;

/**
 * The horn rotor's slow-down time constant, ms (at `accel` 1).
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_HORN_DECEL_MS: 500;

/**
 * The drum rotor's speed-up time constant, ms (at `accel` 1).
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_DRUM_ACCEL_MS: 1700;

/**
 * The drum rotor's slow-down time constant, ms (at `accel` 1).
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_DRUM_DECEL_MS: 1800;

/**
 * Below this rate, Hz, a rotor coasting toward `stop` is snapped to exactly 0.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_STOP_EPS: 0.0001;

/**
 * One inline ring per rotor per leg, floats — at least the 192 kHz need of the horn's sweep.
 * @see data/kernels/rotary.json
 */
export declare const ROTARY_RING_FLOATS: 256;

/**
 * The legal range of each transient-designer field (engineering units), transient spec §3. Every kind comes up flat: no per-kind default differs. `harness/contract-limits-gen.mjs` emits each as `OMX_TRANSIENT_<FIELD>_{MIN,MAX,DEFAULT}` for `mix_transient.h`'s resolve; the row publishes them on OPTIONS when it lands (issue #921).
 * @see data/kernels/transient.json
 */
export declare const TRANSIENT_LIMITS: {
  readonly attackDb: {
    readonly min: -24;
    readonly max: 24;
    readonly step: 0.1;
    readonly unit: "dB";
    readonly default: 0;
    readonly defaultFrom: "desk";
  };
  readonly sustainDb: {
    readonly min: -24;
    readonly max: 24;
    readonly step: 0.1;
    readonly unit: "dB";
    readonly default: 0;
    readonly defaultFrom: "desk";
  };
  readonly attackTimeMs: {
    readonly min: 2;
    readonly max: 50;
    readonly step: 0.1;
    readonly unit: "ms";
    readonly default: 10;
    readonly defaultFrom: "desk";
  };
  readonly sustainTimeMs: {
    readonly min: 50;
    readonly max: 2000;
    readonly step: 1;
    readonly unit: "ms";
    readonly default: 250;
    readonly defaultFrom: "desk";
  };
  readonly outputDb: {
    readonly min: -24;
    readonly max: 12;
    readonly step: 0.1;
    readonly unit: "dB";
    readonly default: 0;
    readonly defaultFrom: "desk";
  };
};

/**
 * The fast follower's attack, ms: exactly the dynamics detector's no-oversampling line (transient spec §3, L7).
 * @see data/kernels/transient.json
 */
export declare const TRANSIENT_FAST_ATTACK_MS: 0.5;

/**
 * The fast follower's release, ms: one 50 Hz cycle held, a 180 bpm sixteenth forgotten (transient spec §3).
 * @see data/kernels/transient.json
 */
export declare const TRANSIENT_FAST_RELEASE_MS: 20;

/**
 * The contrast, dB, at which a knob reaches its full value (transient spec §2, §3).
 * @see data/kernels/transient.json
 */
export declare const TRANSIENT_REF_DB: 6;

/**
 * The detector floor, linear (−100 dBFS): below it both envelopes read the floor and the stage is unity (transient spec §3).
 * @see data/kernels/transient.json
 */
export declare const TRANSIENT_FLOOR_LIN: 0.00001;

/**
 * The tremolo's LFO rate (the catalogue row's 0.1..20 Hz); 4 Hz is the classic amp tremolo.
 * @see data/kernels/tremolo.json
 */
export declare const TREMOLO_RATE_RANGE: {
  readonly min: 0.1;
  readonly max: 20;
  readonly step: 0.01;
  readonly unit: "Hz";
  readonly default: 4;
  readonly defaultFrom: "desk";
};

/**
 * The tremolo's modulation depth: the gain's trough is `1 − mix·depth`.
 * @see data/kernels/tremolo.json
 */
export declare const TREMOLO_DEPTH_RANGE: {
  readonly min: 0;
  readonly max: 100;
  readonly step: 0.1;
  readonly unit: "%";
  readonly default: 50;
  readonly defaultFrom: "desk";
};

/**
 * The tremolo's wet/dry, as an instance of DRIVE_MIX_RANGE: 100 %. The kernel folds the wet/dry into its one gain, so a strip tremolo IS the sound (as the rotary's mix 100 % is).
 * @see data/kernels/tremolo.json
 */
export declare const TREMOLO_MIX_RANGE: {
  readonly min: 0;
  readonly max: 100;
  readonly step: 0.1;
  readonly unit: "%";
  readonly default: 100;
  readonly defaultFrom: "desk";
};

/**
 * The tremolo's numeric travels, field → declaration: the ONE map the row's state, its bounds, its OPTIONS and its controller read (`mode` is a member set, TREMOLO_MODES, beside it).
 * @see data/kernels/tremolo.json
 */
export declare const TREMOLO_TRAVELS: {
  readonly rateHz: {
    readonly min: 0.1;
    readonly max: 20;
    readonly step: 0.01;
    readonly unit: "Hz";
    readonly default: 4;
    readonly defaultFrom: "desk";
  };
  readonly depth: {
    readonly min: 0;
    readonly max: 100;
    readonly step: 0.1;
    readonly unit: "%";
    readonly default: 50;
    readonly defaultFrom: "desk";
  };
  readonly mix: {
    readonly min: 0;
    readonly max: 100;
    readonly step: 0.1;
    readonly unit: "%";
    readonly default: 100;
    readonly defaultFrom: "desk";
  };
};

/**
 * The delay plugin's parameters, in append-only order: DPF's parameter index is the CLAP param id and the LV2 port order (omx-plugins-dpf §3b). Moved from openmixer's packages/omx-plugins/tools/params-gen.mjs PLUGINS.delay.
 *
 * Why: mix is per instance on the desk (insert or fxReturn); a plugin racked in a foreign host is an INSERT, so it reads the input kind's default (omx-plugins-dpf §3a).
 * @see data/plugins/delay.json
 */
export declare const DELAY_PLUGIN: {
  readonly plugin: "delay";
  readonly header: "omx_delay_params.h";
  readonly prefix: "OMX_DELAY";
  readonly params: readonly [{
    readonly symbol: "timeMs";
    readonly min: 0;
    readonly max: 2000;
    readonly def: 300;
    readonly step: 1;
    readonly unit: "ms";
    readonly toggle: false;
  }, {
    readonly symbol: "feedback";
    readonly min: 0;
    readonly max: 0.99;
    readonly def: 0.3;
    readonly step: 0;
    readonly unit: "";
    readonly toggle: false;
  }, {
    readonly symbol: "mix";
    readonly min: 0;
    readonly max: 1;
    readonly def: 0.3;
    readonly step: 0;
    readonly unit: "";
    readonly toggle: false;
  }, {
    readonly symbol: "tone";
    readonly min: 0;
    readonly max: 1;
    readonly def: 0.3;
    readonly step: 0;
    readonly unit: "";
    readonly toggle: false;
  }, {
    readonly symbol: "pingpong";
    readonly min: 0;
    readonly max: 1;
    readonly def: 0;
    readonly step: 1;
    readonly unit: "";
    readonly toggle: true;
  }];
};

/**
 * The Q of a second-order Butterworth section, 1/√2 — maximally flat, the one value every Butterworth biquad in the tree designs at: the LR4 crossover section, the pitch pre-filter and the drive's tilt / band / HF sections, in TS and (as `OMX_BUTTERWORTH_Q`) in C (§7, the scalar door).
 * @see data/primitives.json
 */
export declare const BUTTERWORTH_Q: 0.7071067811865476;

/**
 * ALLPASS_LIMITS, moved from openmixer.
 * @see data/primitives.json
 */
export declare const ALLPASS_LIMITS: {
  readonly unityTolerance: 0.0001;
};

/**
 * XOVER_LIMITS, moved from openmixer.
 * @see data/primitives.json
 */
export declare const XOVER_LIMITS: {
  readonly lr2SectionQ: 0.5;
  readonly lr4SectionQ: 0.7071067811865476;
  readonly partitionTolerance: 0.00001;
};

/**
 * The order the chorus and flanger construct their lines with (four taps; the fdelay spec §1).
 * @see data/primitives.json
 */
export declare const FDELAY_MOD_READ_ORDER: 3;

/**
 * `Λ` for the chorus/flanger read — ONE value; the header and every law read this.
 * @see data/primitives.json
 */
export declare const FDELAY_READ_L1_NORM: 1.25;

/**
 * The standard sample rates (Hz) the desk recognises — the pro-audio superset. One source of truth for the clock controller's `clock.allowed-rates` seed, the force row's validation ceiling and the device-rate probe fallback. What the operator is OFFERED is always the DEVICE's own `supportedRates` (`2026-07-15-clock-rate-honest-force-rate.md`) — this is the ceiling a write is refused by, never a menu.
 * @see data/rates.json
 */
export declare const STANDARD_SAMPLE_RATES: readonly [44100, 48000, 88200, 96000, 176400, 192000];

/**
 * THE declaration: 192 kHz at quantum 128.
 * @see data/rates.json
 */
export declare const RT_HARD_TARGET: {
  readonly rate: 192000;
  readonly quantum: 128;
};

/**
 * The rate a unit-range DSP knob is quoted at (R-058): the rate this desk runs (ruling 2026-09-14). A kernel raises the knob to `REF / sr`, so at this rate the exponent is exactly 1 and the response is bit-for-bit the one cut before the law. Emitted to C as `OMX_DSP_KNOB_REFERENCE_RATE`; the reverb damping and FX-delay tone references `#define` from it.
 * @see data/rates.json
 */
export declare const DSP_KNOB_REFERENCE_RATE: 96000;
