// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com>
// GENERATED by `omx-contract render --target ts` from FreeMixer/omx-contract's data/ — do not edit.

/**
 * The chorus's right-leg phase offset, in TURNS of its one oscillator (§2, §3a; the native-FX catalogue's M32 Dimension row). The right leg's voice k reads the LFO at k/N + spread: 0 is both legs one phase (the stage without the field, bit for bit), 0.25 quadrature, 0.5 the Dimension's opposed sweep. A fraction of a cycle carries no engineering symbol, so the unit is ''.
 * @see data/kernels/chorus.json
 */
export declare const CHORUS_SPREAD_RANGE: {
  readonly min: 0;
  readonly max: 0.5;
  readonly step: 0.01;
  readonly unit: "";
  readonly default: 0;
  readonly defaultFrom: "desk";
};

/**
 * The legal range of each compressor field (engineering units). The widget clamps drags to these, `normalizeComp` enforces them, the row's codec refuses by them and the travel sheet publishes them. `default`/`defaultFrom` are the come-up values `defaultCompState` seeds a fresh strip with, read BACK from here rather than restated there.
 * @see data/kernels/comp.json
 */
export declare const COMP_LIMITS: {
  readonly thresholdDb: {
    readonly min: -60;
    readonly max: 0;
    readonly step: 1;
    readonly unit: "dB";
    readonly default: -18;
    readonly defaultFrom: "desk";
  };
  readonly ratio: {
    readonly min: 1;
    readonly max: 20;
    readonly step: 0.5;
    readonly unit: "";
    readonly default: 4;
    readonly defaultFrom: "desk";
  };
  readonly kneeDb: {
    readonly min: 0;
    readonly max: 24;
    readonly step: 0.5;
    readonly unit: "dB";
    readonly default: 6;
    readonly defaultFrom: "desk";
  };
  readonly attackMs: {
    readonly min: 0.1;
    readonly max: 100;
    readonly step: 1;
    readonly unit: "ms";
    readonly default: 5;
    readonly defaultFrom: "desk";
  };
  readonly releaseMs: {
    readonly min: 5;
    readonly max: 3000;
    readonly step: 10;
    readonly unit: "ms";
    readonly default: 200;
    readonly defaultFrom: "desk";
  };
  readonly makeupDb: {
    readonly min: 0;
    readonly max: 24;
    readonly step: 0.5;
    readonly unit: "dB";
    readonly default: 0;
    readonly defaultFrom: "desk";
  };
  readonly mixPct: {
    readonly min: 0;
    readonly max: 100;
    readonly step: 5;
    readonly unit: "%";
    readonly default: 100;
    readonly defaultFrom: "desk";
  };
};

/**
 * The program-dependent release's model constants — the LA-2A's opto cell as DATA (`docs/design/specs/2026-09-26-compressor-models.md` §3b). `chargeMs`/`dischargeMs` are the word's memory constants, shared by every profile; each profile's `fastMs`, `slowMinMs`, `slowMaxMs` and `share` fit the unit's published two-stage recovery. Not operator controls: generated into `omx_contract_limits.h` as `OMX_PROGRAM_RELEASE_*`, which libomxdsp's `omx_env_program_release` reads.
 * @see data/kernels/comp.json
 */
export declare const PROGRAM_RELEASE: {
  readonly chargeMs: 1000;
  readonly dischargeMs: 5000;
  readonly profiles: {
    readonly opto: {
      readonly fastMs: 70;
      readonly slowMinMs: 110;
      readonly slowMaxMs: 1100;
      readonly share: 0.5;
    };
  };
};

/**
 * The FX delay's time travel. `max` is the NATIVE ring's ceiling — the same number as `OMX_FXDELAY_MAX_MS` in `omx_delay.h`, pinned to it by `output-delay-ceiling.test.ts`. Distinct from the per-route ALIGNMENT delay (`OUTPUT_DELAY_RANGE`, 1 s, `OMX_DELAY_MAX_MS`): one is a musical echo with feedback and mix, the other is a pure latency. Two facts, two rings, two ceilings — sharing the word "delay" is why they keep being confused for each other.
 * @see data/kernels/delay.json
 */
export declare const FX_DELAY_TIME_RANGE: {
  readonly min: 0;
  readonly max: 2000;
  readonly step: 1;
  readonly unit: "ms";
  readonly default: 300;
  readonly defaultFrom: "desk";
};

/**
 * The FX delay's REGENERATION travel — how much of the wet tail feeds back in. Stops short of 1: unity feedback is a runaway the kernel hard-clamps anyway, so offering it would draw travel the DSP refuses. Not NORMALIZED_RANGE for exactly that reason — it is a 0..1 quantity whose top the DSP does not accept, and a control must not offer a value its actuator will eat.
 * @see data/kernels/delay.json
 */
export declare const FX_DELAY_FEEDBACK_RANGE: {
  readonly min: 0;
  readonly max: 0.99;
  readonly step: 0;
  readonly unit: "";
  readonly default: 0.3;
  readonly defaultFrom: "desk";
};

/**
 * The FX delay's TONE — a NORMALIZED_RANGE instance with its own come-up value, matching `DEFAULT_DELAY_STATE.tone`. See REVERB_SIZE_RANGE for why this is a named constant rather than a default on the shared shape.
 * @see data/kernels/delay.json
 */
export declare const DELAY_TONE_RANGE: {
  readonly min: 0;
  readonly max: 1;
  readonly step: 0;
  readonly unit: "";
  readonly default: 0.3;
  readonly defaultFrom: "desk";
};

/**
 * The FX DELAY's wet/dry — the same split as REVERB_MIX_RANGE, its own declaration.
 * @see data/kernels/delay.json
 */
export declare const DELAY_MIX_RANGE: {
  readonly min: 0;
  readonly max: 1;
  readonly step: 0;
  readonly unit: "";
  readonly default: 0.3;
  readonly defaultFrom: "desk";
  readonly byKind: {
    readonly fxReturn: 1;
  };
};

/**
 * The FX delay's PING-PONG come-up value — a toggle, so it has no travel, only this. Declared here rather than as a literal in the server's `DEFAULT_DELAY_STATE` (which now reads it) so the DPF plugin generator (`packages/omx-plugins/tools/params-gen.mjs`, `2026-09-25-omx-plugins-dpf.md` §3a) reads the same fact the desk seeds a fresh strip with.
 * @see data/kernels/delay.json
 */
export declare const FX_DELAY_PINGPONG_DEFAULT: false;

/**
 * The bias at `character = +1`, in the SHAPER's own input units — `OMX_DRIVE_BIAS_MAX`. DERIVED, not chosen (§4b). In the saturating limit every knee tends to `sgn`, the output is a rectangular wave of duty `d = ½ + asin(b)/π`, and its `n`th harmonic goes as `sin(nπd)/n` — so `|H2|` is maximal at `d = ¾`, which is `b = sin(π/4) = 1/√2` exactly. Measured too: the H2-maximising bias for a full-scale sine at unity drive is 0.712 (soft), 0.658 (tape), 0.645 (tube), and this one value costs 0.000 / 0.035 / 0.088 dB of H2 against each curve's own optimum. ONE normalised bias for all three knees, not three.
 * @see data/kernels/drive.json
 */
export declare const DRIVE_BIAS_MAX: 0.7071067811865476;

/**
 * The maximum number of parametric bands a channel EQ may hold — the operator can add up to this many. Generated into `omx_contract_limits.h` as `OMX_EQ_MAX_BANDS`, which `omx_biquad.h` reads (`output-delay-ceiling.test.ts` reads the header): the native lane allocates exactly this many biquad slots per channel and silently clamps above it, so the model, the wire, and the DSP agree by test, not by memory.
 * @see data/kernels/eq.json
 */
export declare const EQ_MAX_BANDS: 24;

/**
 * The standard ISO 266 one-third-octave centre frequencies, 20 Hz–20 kHz (31 bands) — the classic 31-band graphic-EQ layout's centres.
 * @see data/kernels/eq.json
 */
export declare const ISO_THIRD_OCTAVE_CENTRES_HZ: readonly [20, 25, 31.5, 40, 50, 63, 80, 100, 125, 160, 200, 250, 315, 400, 500, 630, 800, 1000, 1250, 1600, 2000, 2500, 3150, 4000, 5000, 6300, 8000, 10000, 12500, 16000, 20000];

/**
 * The graphic EQ's section count: DERIVED from ISO_THIRD_OCTAVE_CENTRES_HZ, never a second literal. Generated into `omx_contract_limits.h` as `OMX_GEQ_BANDS`, which sizes `mix_geq.h`'s section array — its OWN budget, never a claimant on EQ_MAX_BANDS (graphic-eq-31 spec §3, roster ruling 3).
 * @see data/kernels/eq.json
 */
export declare const GEQ_BANDS: 31;

/**
 * The legal range of each gate field (engineering units). The widget clamps drags to these, `normalizeGate` enforces them, the row's codec refuses by them and the travel sheet publishes them — one source of truth. `rangeDb` reaches GATE_RANGE_FLOOR_DB, shown as "−∞" in readouts (a gate fully closed is silence).
 * @see data/kernels/gate.json
 */
export declare const GATE_LIMITS: {
  readonly thresholdDb: {
    readonly min: -80;
    readonly max: 0;
    readonly step: 1;
    readonly unit: "dB";
    readonly default: -40;
    readonly defaultFrom: "desk";
  };
  readonly rangeDb: {
    readonly min: -90;
    readonly max: 0;
    readonly step: 1;
    readonly unit: "dB";
    readonly default: -90;
    readonly defaultFrom: "desk";
  };
  readonly kneeStartDb: {
    readonly min: -80;
    readonly max: 0;
    readonly step: 1;
    readonly unit: "dB";
    readonly default: -43;
    readonly defaultFrom: "desk";
  };
  readonly kneeEndDb: {
    readonly min: -80;
    readonly max: 0;
    readonly step: 1;
    readonly unit: "dB";
    readonly default: -37;
    readonly defaultFrom: "desk";
  };
  readonly attackMs: {
    readonly min: 0;
    readonly max: 500;
    readonly step: 0.5;
    readonly unit: "ms";
    readonly default: 1;
    readonly defaultFrom: "desk";
  };
  readonly holdMs: {
    readonly min: 0;
    readonly max: 2000;
    readonly step: 5;
    readonly unit: "ms";
    readonly default: 10;
    readonly defaultFrom: "desk";
  };
  readonly releaseMs: {
    readonly min: 0;
    readonly max: 5000;
    readonly step: 10;
    readonly unit: "ms";
    readonly default: 100;
    readonly defaultFrom: "desk";
  };
  readonly hysteresisDb: {
    readonly min: 0;
    readonly max: 24;
    readonly step: 0.5;
    readonly unit: "dB";
    readonly default: 3;
    readonly defaultFrom: "desk";
  };
  readonly ratio: {
    readonly min: 1;
    readonly max: 100;
    readonly step: 1;
    readonly unit: "";
    readonly default: 16;
    readonly defaultFrom: "desk";
  };
};

/**
 * The precision limiter's travels (`2026-09-27-precision-limiter.md` §2), rendered into `omx_contract_limits.h` as `OMX_LIMITER_*` by `harness/contract-limits-gen.mjs`, so `mix_limiter.h` reads them and never restates one (R-094). The ceiling is a TRUE peak in dBFS (the ×4 detector); the look-ahead sets the declared latency; the release is the envelope's time constant on the gain depth.
 * @see data/kernels/limiter.json
 */
export declare const LIMITER_LIMITS: {
  readonly ceilingDb: {
    readonly min: -12;
    readonly max: 0;
    readonly step: 0.1;
    readonly unit: "dBFS";
    readonly default: -1;
    readonly defaultFrom: "desk";
  };
  readonly lookaheadMs: {
    readonly min: 0.5;
    readonly max: 5;
    readonly step: 0.1;
    readonly unit: "ms";
    readonly default: 1.5;
    readonly defaultFrom: "desk";
  };
  readonly releaseMs: {
    readonly min: 1;
    readonly max: 1000;
    readonly step: 1;
    readonly unit: "ms";
    readonly default: 50;
    readonly defaultFrom: "desk";
  };
};

/**
 * PITCH_LIMITS, moved from openmixer.
 * @see data/kernels/pitch.json
 */
export declare const PITCH_LIMITS: {
  readonly semitones: {
    readonly min: -12;
    readonly max: 12;
    readonly default: 0;
  };
  readonly cents: {
    readonly min: -50;
    readonly max: 50;
    readonly default: 0;
  };
  readonly mix: {
    readonly min: 0;
    readonly max: 100;
    readonly default: 100;
  };
};

/**
 * PITCH_KERNEL, moved from openmixer.
 * @see data/kernels/pitch.json
 */
export declare const PITCH_KERNEL: {
  readonly windowMs: 40;
  readonly prefilterCeilingHz: 20000;
  readonly prefilterQ: 0.7071067811865476;
};

/**
 * PLATE's tank MODULATION DEPTH, in percent of Dattorro's own excursion (±8 samples at his 29 761 Hz tuning rate, scaled to the live rate the way the tank lengths are). 100 is the depth the plate has always run at, so the come-up is bit-identical to the plate before the field; 0 brings back the unmodulated tank's ring; 400 is the wide, chorused EMT-style swing. The rate stays 1 Hz. Only PLATE reads it (`2026-09-26-native-fx-catalogue.md` §2, Reverb).
 * @see data/kernels/reverb.json
 */
export declare const REVERB_PLATE_MOD_DEPTH_RANGE: {
  readonly min: 0;
  readonly max: 400;
  readonly step: 1;
  readonly unit: "%";
  readonly default: 100;
  readonly defaultFrom: "desk";
};

/**
 * The legal range of each transient-designer field (engineering units), transient spec §3. Every kind comes up flat: no per-kind default differs. `harness/contract-limits-gen.mjs` emits each as `OMX_TRANSIENT_<FIELD>_{MIN,MAX,DEFAULT}` for `mix_transient.h`'s resolve; the row publishes them on OPTIONS when it lands (issue #921).
 * @see data/kernels/transient.json
 */
export declare const TRANSIENT_LIMITS: {
  readonly attackDb: {
    readonly min: -24;
    readonly max: 24;
    readonly step: 0.1;
    readonly unit: "dB";
    readonly default: 0;
    readonly defaultFrom: "desk";
  };
  readonly sustainDb: {
    readonly min: -24;
    readonly max: 24;
    readonly step: 0.1;
    readonly unit: "dB";
    readonly default: 0;
    readonly defaultFrom: "desk";
  };
  readonly attackTimeMs: {
    readonly min: 2;
    readonly max: 50;
    readonly step: 0.1;
    readonly unit: "ms";
    readonly default: 10;
    readonly defaultFrom: "desk";
  };
  readonly sustainTimeMs: {
    readonly min: 50;
    readonly max: 2000;
    readonly step: 1;
    readonly unit: "ms";
    readonly default: 250;
    readonly defaultFrom: "desk";
  };
  readonly outputDb: {
    readonly min: -24;
    readonly max: 12;
    readonly step: 0.1;
    readonly unit: "dB";
    readonly default: 0;
    readonly defaultFrom: "desk";
  };
};

/**
 * The fast follower's attack, ms: exactly the dynamics detector's no-oversampling line (transient spec §3, L7).
 * @see data/kernels/transient.json
 */
export declare const TRANSIENT_FAST_ATTACK_MS: 0.5;

/**
 * The fast follower's release, ms: one 50 Hz cycle held, a 180 bpm sixteenth forgotten (transient spec §3).
 * @see data/kernels/transient.json
 */
export declare const TRANSIENT_FAST_RELEASE_MS: 20;

/**
 * The contrast, dB, at which a knob reaches its full value (transient spec §2, §3).
 * @see data/kernels/transient.json
 */
export declare const TRANSIENT_REF_DB: 6;

/**
 * The detector floor, linear (−100 dBFS): below it both envelopes read the floor and the stage is unity (transient spec §3).
 * @see data/kernels/transient.json
 */
export declare const TRANSIENT_FLOOR_LIN: 0.00001;

/**
 * The delay plugin's parameters, in append-only order: DPF's parameter index is the CLAP param id and the LV2 port order (omx-plugins-dpf §3b). Moved from openmixer's packages/omx-plugins/tools/params-gen.mjs PLUGINS.delay.
 *
 * Why: mix is per instance on the desk (insert or fxReturn); a plugin racked in a foreign host is an INSERT, so it reads the input kind's default (omx-plugins-dpf §3a).
 * @see data/plugins/delay.json
 */
export declare const DELAY_PLUGIN: {
  readonly plugin: "delay";
  readonly header: "omx_delay_params.h";
  readonly prefix: "OMX_DELAY";
  readonly params: readonly [{
    readonly symbol: "timeMs";
    readonly min: 0;
    readonly max: 2000;
    readonly def: 300;
    readonly step: 1;
    readonly unit: "ms";
    readonly toggle: false;
  }, {
    readonly symbol: "feedback";
    readonly min: 0;
    readonly max: 0.99;
    readonly def: 0.3;
    readonly step: 0;
    readonly unit: "";
    readonly toggle: false;
  }, {
    readonly symbol: "mix";
    readonly min: 0;
    readonly max: 1;
    readonly def: 0.3;
    readonly step: 0;
    readonly unit: "";
    readonly toggle: false;
  }, {
    readonly symbol: "tone";
    readonly min: 0;
    readonly max: 1;
    readonly def: 0.3;
    readonly step: 0;
    readonly unit: "";
    readonly toggle: false;
  }, {
    readonly symbol: "pingpong";
    readonly min: 0;
    readonly max: 1;
    readonly def: 0;
    readonly step: 1;
    readonly unit: "";
    readonly toggle: true;
  }];
};

/**
 * The Q of a second-order Butterworth section, 1/√2 — maximally flat, the one value every Butterworth biquad in the tree designs at: the LR4 crossover section, the pitch pre-filter and the drive's tilt / band / HF sections, in TS and (as `OMX_BUTTERWORTH_Q`) in C (§7, the scalar door).
 * @see data/primitives.json
 */
export declare const BUTTERWORTH_Q: 0.7071067811865476;

/**
 * ALLPASS_LIMITS, moved from openmixer.
 * @see data/primitives.json
 */
export declare const ALLPASS_LIMITS: {
  readonly unityTolerance: 0.0001;
};

/**
 * XOVER_LIMITS, moved from openmixer.
 * @see data/primitives.json
 */
export declare const XOVER_LIMITS: {
  readonly lr2SectionQ: 0.5;
  readonly lr4SectionQ: 0.7071067811865476;
  readonly partitionTolerance: 0.00001;
};

/**
 * The order the chorus and flanger construct their lines with (four taps; the fdelay spec §1).
 * @see data/primitives.json
 */
export declare const FDELAY_MOD_READ_ORDER: 3;

/**
 * `Λ` for the chorus/flanger read — ONE value; the header and every law read this.
 * @see data/primitives.json
 */
export declare const FDELAY_READ_L1_NORM: 1.25;

/**
 * The standard sample rates (Hz) the desk recognises — the pro-audio superset. One source of truth for the clock controller's `clock.allowed-rates` seed, the force row's validation ceiling and the device-rate probe fallback. What the operator is OFFERED is always the DEVICE's own `supportedRates` (`2026-07-15-clock-rate-honest-force-rate.md`) — this is the ceiling a write is refused by, never a menu.
 * @see data/rates.json
 */
export declare const STANDARD_SAMPLE_RATES: readonly [44100, 48000, 88200, 96000, 176400, 192000];

/**
 * THE declaration: 192 kHz at quantum 128.
 * @see data/rates.json
 */
export declare const RT_HARD_TARGET: {
  readonly rate: 192000;
  readonly quantum: 128;
};

/**
 * The rate a unit-range DSP knob is quoted at (R-058): the rate this desk runs (ruling 2026-09-14). A kernel raises the knob to `REF / sr`, so at this rate the exponent is exactly 1 and the response is bit-for-bit the one cut before the law. Emitted to C as `OMX_DSP_KNOB_REFERENCE_RATE`; the reverb damping and FX-delay tone references `#define` from it.
 * @see data/rates.json
 */
export declare const DSP_KNOB_REFERENCE_RATE: 96000;
