// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com>
#ifndef OMX_CONTRACT_LIMITS_H
#define OMX_CONTRACT_LIMITS_H
#include <math.h>
/*
 * GENERATED — DO NOT EDIT BY HAND.
 * Produced by `omx-contract render --target c` from FreeMixer/omx-contract's data/, the declaration
 * as data (each item's reason is its `doc`). Change the data, never this file: a consumer builds
 * against the render of the omx-contract version it pins and commits none.
 *
 * A C contract (OMX_PRE/OMX_POST/OMX_INVARIANT) reads a limit from HERE, never a literal.
 */

/* Per-parameter numeric travel, one block per `travels` table named <PREFIX>_LIMITS:
 * OMX_<PREFIX>_<FIELD>_MIN/_MAX/_DEFAULT, float literals. */
#define OMX_COMP_THRESHOLD_DB_MIN -60.0f
#define OMX_COMP_THRESHOLD_DB_MAX 0.0f
#define OMX_COMP_THRESHOLD_DB_DEFAULT -18.0f
#define OMX_COMP_RATIO_MIN 1.0f
#define OMX_COMP_RATIO_MAX 20.0f
#define OMX_COMP_RATIO_DEFAULT 4.0f
#define OMX_COMP_KNEE_DB_MIN 0.0f
#define OMX_COMP_KNEE_DB_MAX 24.0f
#define OMX_COMP_KNEE_DB_DEFAULT 6.0f
#define OMX_COMP_ATTACK_MS_MIN 0.1f
#define OMX_COMP_ATTACK_MS_MAX 100.0f
#define OMX_COMP_ATTACK_MS_DEFAULT 5.0f
#define OMX_COMP_RELEASE_MS_MIN 5.0f
#define OMX_COMP_RELEASE_MS_MAX 3000.0f
#define OMX_COMP_RELEASE_MS_DEFAULT 200.0f
#define OMX_COMP_MAKEUP_DB_MIN 0.0f
#define OMX_COMP_MAKEUP_DB_MAX 24.0f
#define OMX_COMP_MAKEUP_DB_DEFAULT 0.0f
#define OMX_COMP_MIX_PCT_MIN 0.0f
#define OMX_COMP_MIX_PCT_MAX 100.0f
#define OMX_COMP_MIX_PCT_DEFAULT 100.0f

#define OMX_GATE_THRESHOLD_DB_MIN -80.0f
#define OMX_GATE_THRESHOLD_DB_MAX 0.0f
#define OMX_GATE_THRESHOLD_DB_DEFAULT -40.0f
#define OMX_GATE_RANGE_DB_MIN -90.0f
#define OMX_GATE_RANGE_DB_MAX 0.0f
#define OMX_GATE_RANGE_DB_DEFAULT -90.0f
#define OMX_GATE_KNEE_START_DB_MIN -80.0f
#define OMX_GATE_KNEE_START_DB_MAX 0.0f
#define OMX_GATE_KNEE_START_DB_DEFAULT -43.0f
#define OMX_GATE_KNEE_END_DB_MIN -80.0f
#define OMX_GATE_KNEE_END_DB_MAX 0.0f
#define OMX_GATE_KNEE_END_DB_DEFAULT -37.0f
#define OMX_GATE_ATTACK_MS_MIN 0.0f
#define OMX_GATE_ATTACK_MS_MAX 500.0f
#define OMX_GATE_ATTACK_MS_DEFAULT 1.0f
#define OMX_GATE_HOLD_MS_MIN 0.0f
#define OMX_GATE_HOLD_MS_MAX 2000.0f
#define OMX_GATE_HOLD_MS_DEFAULT 10.0f
#define OMX_GATE_RELEASE_MS_MIN 0.0f
#define OMX_GATE_RELEASE_MS_MAX 5000.0f
#define OMX_GATE_RELEASE_MS_DEFAULT 100.0f
#define OMX_GATE_HYSTERESIS_DB_MIN 0.0f
#define OMX_GATE_HYSTERESIS_DB_MAX 24.0f
#define OMX_GATE_HYSTERESIS_DB_DEFAULT 3.0f
#define OMX_GATE_RATIO_MIN 1.0f
#define OMX_GATE_RATIO_MAX 100.0f
#define OMX_GATE_RATIO_DEFAULT 16.0f

#define OMX_LIMITER_CEILING_DB_MIN -12.0f
#define OMX_LIMITER_CEILING_DB_MAX 0.0f
#define OMX_LIMITER_CEILING_DB_DEFAULT -1.0f
#define OMX_LIMITER_LOOKAHEAD_MS_MIN 0.5f
#define OMX_LIMITER_LOOKAHEAD_MS_MAX 5.0f
#define OMX_LIMITER_LOOKAHEAD_MS_DEFAULT 1.5f
#define OMX_LIMITER_RELEASE_MS_MIN 1.0f
#define OMX_LIMITER_RELEASE_MS_MAX 1000.0f
#define OMX_LIMITER_RELEASE_MS_DEFAULT 50.0f

#define OMX_PITCH_SEMITONES_MIN -12.0f
#define OMX_PITCH_SEMITONES_MAX 12.0f
#define OMX_PITCH_SEMITONES_DEFAULT 0.0f
#define OMX_PITCH_CENTS_MIN -50.0f
#define OMX_PITCH_CENTS_MAX 50.0f
#define OMX_PITCH_CENTS_DEFAULT 0.0f
#define OMX_PITCH_MIX_MIN 0.0f
#define OMX_PITCH_MIX_MAX 100.0f
#define OMX_PITCH_MIX_DEFAULT 100.0f

#define OMX_TRANSIENT_ATTACK_DB_MIN -24.0f
#define OMX_TRANSIENT_ATTACK_DB_MAX 24.0f
#define OMX_TRANSIENT_ATTACK_DB_DEFAULT 0.0f
#define OMX_TRANSIENT_SUSTAIN_DB_MIN -24.0f
#define OMX_TRANSIENT_SUSTAIN_DB_MAX 24.0f
#define OMX_TRANSIENT_SUSTAIN_DB_DEFAULT 0.0f
#define OMX_TRANSIENT_ATTACK_TIME_MS_MIN 2.0f
#define OMX_TRANSIENT_ATTACK_TIME_MS_MAX 50.0f
#define OMX_TRANSIENT_ATTACK_TIME_MS_DEFAULT 10.0f
#define OMX_TRANSIENT_SUSTAIN_TIME_MS_MIN 50.0f
#define OMX_TRANSIENT_SUSTAIN_TIME_MS_MAX 2000.0f
#define OMX_TRANSIENT_SUSTAIN_TIME_MS_DEFAULT 250.0f
#define OMX_TRANSIENT_OUTPUT_DB_MIN -24.0f
#define OMX_TRANSIENT_OUTPUT_DB_MAX 12.0f
#define OMX_TRANSIENT_OUTPUT_DB_DEFAULT 0.0f

/* The second C spelling of a travel, its item's `c.alias` { fact, field }:
 * OMX_<FACT>_<FIELD>_MIN/_MAX/_DEFAULT. Removed by a MAJOR release once no consumer reads it. */
#define OMX_PAN_PAN_MIN -1.0f
#define OMX_PAN_PAN_MAX 1.0f

#define OMX_DELAY_TIME_MS_MIN 0.0f
#define OMX_DELAY_TIME_MS_MAX 2000.0f
#define OMX_DELAY_TIME_MS_DEFAULT 300.0f

#define OMX_DRIVE_DRIVE_DB_MIN 0.0f
#define OMX_DRIVE_DRIVE_DB_MAX 36.0f
#define OMX_DRIVE_DRIVE_DB_DEFAULT 0.0f
#define OMX_DRIVE_CHARACTER_MIN -1.0f
#define OMX_DRIVE_CHARACTER_MAX 1.0f
#define OMX_DRIVE_CHARACTER_DEFAULT 0.0f
#define OMX_DRIVE_BAND_HZ_MIN 20.0f
#define OMX_DRIVE_BAND_HZ_MAX 20000.0f
#define OMX_DRIVE_BAND_HZ_DEFAULT 2000.0f
#define OMX_DRIVE_MIX_MIN 0.0f
#define OMX_DRIVE_MIX_MAX 100.0f
#define OMX_DRIVE_MIX_DEFAULT 100.0f
#define OMX_DRIVE_TRIM_DB_MIN -24.0f
#define OMX_DRIVE_TRIM_DB_MAX 12.0f
#define OMX_DRIVE_TRIM_DB_DEFAULT 0.0f

/* Every scalar, sheet leaf and single travel's numbers, one block sorted by macro. An integer value
 * is an integer literal, any other a float literal AND its OMX_<macro>_DOUBLE spelling. */
#define OMX_ALLPASS_UNITY_TOLERANCE 0.0001f
#define OMX_ALLPASS_UNITY_TOLERANCE_DOUBLE 0.0001
#define OMX_BAND_DYN_ATTACK_RANGE_DEFAULT 5
#define OMX_BAND_DYN_ATTACK_RANGE_MAX 100
#define OMX_BAND_DYN_ATTACK_RANGE_MIN 0.5f
#define OMX_BAND_DYN_ATTACK_RANGE_MIN_DOUBLE 0.5
#define OMX_BAND_DYN_ATTACK_RANGE_STEP 0.1f
#define OMX_BAND_DYN_ATTACK_RANGE_STEP_DOUBLE 0.1
#define OMX_BAND_DYN_KNEE_DB 6
#define OMX_BAND_DYN_MAX_BANDS 9
#define OMX_BAND_DYN_RANGE_RANGE_DEFAULT -6
#define OMX_BAND_DYN_RANGE_RANGE_MAX 12
#define OMX_BAND_DYN_RANGE_RANGE_MIN -24
#define OMX_BAND_DYN_RANGE_RANGE_STEP 0.5f
#define OMX_BAND_DYN_RANGE_RANGE_STEP_DOUBLE 0.5
#define OMX_BAND_DYN_RATIO_RANGE_DEFAULT 2
#define OMX_BAND_DYN_RATIO_RANGE_MAX 20
#define OMX_BAND_DYN_RATIO_RANGE_MIN 1
#define OMX_BAND_DYN_RATIO_RANGE_STEP 0.1f
#define OMX_BAND_DYN_RATIO_RANGE_STEP_DOUBLE 0.1
#define OMX_BAND_DYN_RELEASE_RANGE_DEFAULT 100
#define OMX_BAND_DYN_RELEASE_RANGE_MAX 3000
#define OMX_BAND_DYN_RELEASE_RANGE_MIN 5
#define OMX_BAND_DYN_RELEASE_RANGE_STEP 1
#define OMX_BAND_DYN_THRESHOLD_RANGE_DEFAULT -30
#define OMX_BAND_DYN_THRESHOLD_RANGE_MAX 0
#define OMX_BAND_DYN_THRESHOLD_RANGE_MIN -60
#define OMX_BAND_DYN_THRESHOLD_RANGE_STEP 0.5f
#define OMX_BAND_DYN_THRESHOLD_RANGE_STEP_DOUBLE 0.5
#define OMX_BUS_INPUT_CAP 128
#define OMX_BUTTERWORTH_Q 0.7071067811865476f
#define OMX_BUTTERWORTH_Q_DOUBLE 0.7071067811865476
#define OMX_CHORUS_BASE_MS 10
#define OMX_CHORUS_DEPTH_RANGE_DEFAULT 4
#define OMX_CHORUS_DEPTH_RANGE_MAX 12
#define OMX_CHORUS_DEPTH_RANGE_MIN 0
#define OMX_CHORUS_DEPTH_RANGE_STEP 0.1f
#define OMX_CHORUS_DEPTH_RANGE_STEP_DOUBLE 0.1
#define OMX_CHORUS_MAX_MS 22
#define OMX_CHORUS_MIX_RANGE_DEFAULT 35
#define OMX_CHORUS_MIX_RANGE_MAX 100
#define OMX_CHORUS_MIX_RANGE_MIN 0
#define OMX_CHORUS_MIX_RANGE_STEP 0.1f
#define OMX_CHORUS_MIX_RANGE_STEP_DOUBLE 0.1
#define OMX_CHORUS_RATE_RANGE_DEFAULT 0.6f
#define OMX_CHORUS_RATE_RANGE_DEFAULT_DOUBLE 0.6
#define OMX_CHORUS_RATE_RANGE_MAX 8
#define OMX_CHORUS_RATE_RANGE_MIN 0.05f
#define OMX_CHORUS_RATE_RANGE_MIN_DOUBLE 0.05
#define OMX_CHORUS_RATE_RANGE_STEP 0.01f
#define OMX_CHORUS_RATE_RANGE_STEP_DOUBLE 0.01
#define OMX_CHORUS_SPREAD_RANGE_DEFAULT 0
#define OMX_CHORUS_SPREAD_RANGE_MAX 0.5f
#define OMX_CHORUS_SPREAD_RANGE_MAX_DOUBLE 0.5
#define OMX_CHORUS_SPREAD_RANGE_MIN 0
#define OMX_CHORUS_SPREAD_RANGE_STEP 0.01f
#define OMX_CHORUS_SPREAD_RANGE_STEP_DOUBLE 0.01
#define OMX_CHORUS_VOICES_RANGE_DEFAULT 3
#define OMX_CHORUS_VOICES_RANGE_MAX 4
#define OMX_CHORUS_VOICES_RANGE_MIN 1
#define OMX_CHORUS_VOICES_RANGE_STEP 1
#define OMX_DEEP_PLATEAU_FRAMES 20
#define OMX_DEESS_ATTACK_RANGE_DEFAULT 1
#define OMX_DEESS_ATTACK_RANGE_MAX 50
#define OMX_DEESS_ATTACK_RANGE_MIN 0.1f
#define OMX_DEESS_ATTACK_RANGE_MIN_DOUBLE 0.1
#define OMX_DEESS_ATTACK_RANGE_STEP 0.1f
#define OMX_DEESS_ATTACK_RANGE_STEP_DOUBLE 0.1
#define OMX_DEESS_FREQ_RANGE_DEFAULT 7000
#define OMX_DEESS_FREQ_RANGE_MAX 16000
#define OMX_DEESS_FREQ_RANGE_MIN 2000
#define OMX_DEESS_FREQ_RANGE_STEP 10
#define OMX_DEESS_KNEE_DB 6
#define OMX_DEESS_RANGE_RANGE_DEFAULT -12
#define OMX_DEESS_RANGE_RANGE_MAX 0
#define OMX_DEESS_RANGE_RANGE_MIN -24
#define OMX_DEESS_RANGE_RANGE_STEP 0.5f
#define OMX_DEESS_RANGE_RANGE_STEP_DOUBLE 0.5
#define OMX_DEESS_RATIO_RANGE_DEFAULT 4
#define OMX_DEESS_RATIO_RANGE_MAX 20
#define OMX_DEESS_RATIO_RANGE_MIN 1
#define OMX_DEESS_RATIO_RANGE_STEP 0.1f
#define OMX_DEESS_RATIO_RANGE_STEP_DOUBLE 0.1
#define OMX_DEESS_RELEASE_RANGE_DEFAULT 60
#define OMX_DEESS_RELEASE_RANGE_MAX 500
#define OMX_DEESS_RELEASE_RANGE_MIN 5
#define OMX_DEESS_RELEASE_RANGE_STEP 1
#define OMX_DEESS_THRESHOLD_RANGE_DEFAULT -30
#define OMX_DEESS_THRESHOLD_RANGE_MAX 0
#define OMX_DEESS_THRESHOLD_RANGE_MIN -60
#define OMX_DEESS_THRESHOLD_RANGE_STEP 0.5f
#define OMX_DEESS_THRESHOLD_RANGE_STEP_DOUBLE 0.5
#define OMX_DEESS_WIDTH_RANGE_DEFAULT 1
#define OMX_DEESS_WIDTH_RANGE_MAX 4
#define OMX_DEESS_WIDTH_RANGE_MIN 0.25f
#define OMX_DEESS_WIDTH_RANGE_MIN_DOUBLE 0.25
#define OMX_DEESS_WIDTH_RANGE_STEP 0.05f
#define OMX_DEESS_WIDTH_RANGE_STEP_DOUBLE 0.05
#define OMX_DEFAULT_THRESHOLDS_GROWTH_CONFIRM_FRAMES 2
#define OMX_DEFAULT_THRESHOLDS_GROWTH_MAX_DIP_DB 0.5f
#define OMX_DEFAULT_THRESHOLDS_GROWTH_MAX_DIP_DB_DOUBLE 0.5
#define OMX_DEFAULT_THRESHOLDS_GROWTH_MAX_SINGLE_FRAME_SHARE 0.5f
#define OMX_DEFAULT_THRESHOLDS_GROWTH_MAX_SINGLE_FRAME_SHARE_DOUBLE 0.5
#define OMX_DEFAULT_THRESHOLDS_GROWTH_MIN_DB_PER_FRAME 0.8f
#define OMX_DEFAULT_THRESHOLDS_GROWTH_MIN_DB_PER_FRAME_DOUBLE 0.8
#define OMX_DEFAULT_THRESHOLDS_GROWTH_MIN_TOTAL_RISE_DB 6
#define OMX_DEFAULT_THRESHOLDS_PAPR_DB 18
#define OMX_DEFAULT_THRESHOLDS_PERSIST_FRAMES 5
#define OMX_DEFAULT_THRESHOLDS_PHPR_DB 9
#define OMX_DEFAULT_THRESHOLDS_PNPR_DB 12
#define OMX_DEFAULT_THRESHOLDS_PSHR_MIN_DB 10
#define OMX_DEFAULT_THRESHOLDS_SUB_CLEAN_FRAMES 5
#define OMX_DELAY_MIX_RANGE_BY_KIND_FX_RETURN 1
#define OMX_DELAY_MIX_RANGE_DEFAULT 0.3f
#define OMX_DELAY_MIX_RANGE_DEFAULT_DOUBLE 0.3
#define OMX_DELAY_MIX_RANGE_MAX 1
#define OMX_DELAY_MIX_RANGE_MIN 0
#define OMX_DELAY_MIX_RANGE_STEP 0
#define OMX_DELAY_TONE_RANGE_DEFAULT 0.3f
#define OMX_DELAY_TONE_RANGE_DEFAULT_DOUBLE 0.3
#define OMX_DELAY_TONE_RANGE_MAX 1
#define OMX_DELAY_TONE_RANGE_MIN 0
#define OMX_DELAY_TONE_RANGE_STEP 0
#define OMX_DETECTOR_OVERSAMPLE_AUTO_MS 0.5f
#define OMX_DETECTOR_OVERSAMPLE_AUTO_MS_DOUBLE 0.5
#define OMX_DRIVE_AMOUNT_RANGE_DEFAULT 0
#define OMX_DRIVE_AMOUNT_RANGE_MAX 36
#define OMX_DRIVE_AMOUNT_RANGE_MIN 0
#define OMX_DRIVE_AMOUNT_RANGE_STEP 0.1f
#define OMX_DRIVE_AMOUNT_RANGE_STEP_DOUBLE 0.1
#define OMX_DRIVE_BAND_FREQ_RANGE_DEFAULT 2000
#define OMX_DRIVE_BAND_FREQ_RANGE_MAX 20000
#define OMX_DRIVE_BAND_FREQ_RANGE_MIN 20
#define OMX_DRIVE_BAND_FREQ_RANGE_STEP 1
#define OMX_DRIVE_BIAS_MAX 0.7071067811865476f
#define OMX_DRIVE_BIAS_MAX_DOUBLE 0.7071067811865476
#define OMX_DRIVE_CHARACTER_RANGE_DEFAULT 0
#define OMX_DRIVE_CHARACTER_RANGE_MAX 1
#define OMX_DRIVE_CHARACTER_RANGE_MIN -1
#define OMX_DRIVE_CHARACTER_RANGE_STEP 0.01f
#define OMX_DRIVE_CHARACTER_RANGE_STEP_DOUBLE 0.01
#define OMX_DRIVE_MIX_RANGE_DEFAULT 100
#define OMX_DRIVE_MIX_RANGE_MAX 100
#define OMX_DRIVE_MIX_RANGE_MIN 0
#define OMX_DRIVE_MIX_RANGE_STEP 0.1f
#define OMX_DRIVE_MIX_RANGE_STEP_DOUBLE 0.1
#define OMX_DRIVE_TRIM_RANGE_DEFAULT 0
#define OMX_DRIVE_TRIM_RANGE_MAX 12
#define OMX_DRIVE_TRIM_RANGE_MIN -24
#define OMX_DRIVE_TRIM_RANGE_STEP 0.1f
#define OMX_DRIVE_TRIM_RANGE_STEP_DOUBLE 0.1
#define OMX_DSP_KNOB_REFERENCE_RATE 96000
#define OMX_EQ_BAND_COUNTS_CHANNEL_DEFAULT 4
#define OMX_EQ_BAND_COUNTS_CHANNEL_MAX 24
#define OMX_EQ_BAND_COUNTS_EQ16_DEFAULT 16
#define OMX_EQ_BAND_COUNTS_EQ16_MAX 16
#define OMX_EQ_BAND_COUNTS_EQ32_DEFAULT 32
#define OMX_EQ_BAND_COUNTS_EQ32_MAX 32
#define OMX_EQ_BAND_COUNTS_EQ8_DEFAULT 8
#define OMX_EQ_BAND_COUNTS_EQ8_MAX 8
#define OMX_EQ_BAND_COUNTS_STRIP_DEFAULT 4
#define OMX_EQ_BAND_COUNTS_STRIP_MAX 4
#define OMX_EQ_BAND_DEFAULTS_GAIN_DB 0
#define OMX_EQ_BAND_DEFAULTS_Q 1
#define OMX_EQ_FREQ_RANGE_MAX 20000
#define OMX_EQ_FREQ_RANGE_MIN 20
#define OMX_EQ_FREQ_RANGE_STEP 10
#define OMX_EQ_GAIN_RANGE_MAX 15
#define OMX_EQ_GAIN_RANGE_MIN -15
#define OMX_EQ_GAIN_RANGE_STEP 0.5f
#define OMX_EQ_GAIN_RANGE_STEP_DOUBLE 0.5
#define OMX_EQ_MAX_BANDS 24
#define OMX_EQ_NOTCH_Q_RANGE_MAX 116
#define OMX_EQ_NOTCH_Q_RANGE_MIN 0.3f
#define OMX_EQ_NOTCH_Q_RANGE_MIN_DOUBLE 0.3
#define OMX_EQ_NOTCH_Q_RANGE_STEP 1
#define OMX_EQ_PASS_FILTER_DEFAULTS_HPF_FREQ_HZ 80
#define OMX_EQ_PASS_FILTER_DEFAULTS_LPF_FREQ_HZ 18000
#define OMX_EQ_Q_RANGE_MAX 8
#define OMX_EQ_Q_RANGE_MIN 0.3f
#define OMX_EQ_Q_RANGE_MIN_DOUBLE 0.3
#define OMX_EQ_Q_RANGE_STEP 0.1f
#define OMX_EQ_Q_RANGE_STEP_DOUBLE 0.1
#define OMX_FBS_DEFAULT_MAX_AUTO_BANDS 6
#define OMX_FBS_DEFAULT_NOTCH_Q 116
#define OMX_FBS_FLOOR_LIN 1e-12f
#define OMX_FBS_FLOOR_LIN_DOUBLE 1e-12
#define OMX_FBS_MAX_NOTCH_DEPTH_DB 18
#define OMX_FBS_PAPR_GUARD_BINS 2
#define OMX_FBS_PHPR_HARMONICS 3
#define OMX_FBS_PNPR_GUARD_BINS 1
#define OMX_FBS_PNPR_RADIUS_BINS 3
#define OMX_FBS_PSHR_SELF_SKIP_BINS 3
#define OMX_FBS_TRACK_SLOTS 512
#define OMX_FDELAY_MOD_READ_ORDER 3
#define OMX_FDELAY_READ_L1_NORM 1.25f
#define OMX_FDELAY_READ_L1_NORM_DOUBLE 1.25
#define OMX_FLANGER_BASE_MS 0.5f
#define OMX_FLANGER_BASE_MS_DOUBLE 0.5
#define OMX_FLANGER_DEPTH_RANGE_DEFAULT 2
#define OMX_FLANGER_DEPTH_RANGE_MAX 5
#define OMX_FLANGER_DEPTH_RANGE_MIN 0
#define OMX_FLANGER_DEPTH_RANGE_STEP 0.1f
#define OMX_FLANGER_DEPTH_RANGE_STEP_DOUBLE 0.1
#define OMX_FLANGER_FEEDBACK_RANGE_DEFAULT 0.6f
#define OMX_FLANGER_FEEDBACK_RANGE_DEFAULT_DOUBLE 0.6
#define OMX_FLANGER_FEEDBACK_RANGE_MAX 0.95f
#define OMX_FLANGER_FEEDBACK_RANGE_MAX_DOUBLE 0.95
#define OMX_FLANGER_FEEDBACK_RANGE_MIN -0.95f
#define OMX_FLANGER_FEEDBACK_RANGE_MIN_DOUBLE -0.95
#define OMX_FLANGER_FEEDBACK_RANGE_STEP 0.01f
#define OMX_FLANGER_FEEDBACK_RANGE_STEP_DOUBLE 0.01
#define OMX_FLANGER_MAX_MS 6
#define OMX_FLANGER_MIX_RANGE_DEFAULT 50
#define OMX_FLANGER_MIX_RANGE_MAX 100
#define OMX_FLANGER_MIX_RANGE_MIN 0
#define OMX_FLANGER_MIX_RANGE_STEP 0.1f
#define OMX_FLANGER_MIX_RANGE_STEP_DOUBLE 0.1
#define OMX_FLANGER_RATE_RANGE_DEFAULT 0.25f
#define OMX_FLANGER_RATE_RANGE_DEFAULT_DOUBLE 0.25
#define OMX_FLANGER_RATE_RANGE_MAX 5
#define OMX_FLANGER_RATE_RANGE_MIN 0.05f
#define OMX_FLANGER_RATE_RANGE_MIN_DOUBLE 0.05
#define OMX_FLANGER_RATE_RANGE_STEP 0.01f
#define OMX_FLANGER_RATE_RANGE_STEP_DOUBLE 0.01
#define OMX_FX_DELAY_FEEDBACK_RANGE_DEFAULT 0.3f
#define OMX_FX_DELAY_FEEDBACK_RANGE_DEFAULT_DOUBLE 0.3
#define OMX_FX_DELAY_FEEDBACK_RANGE_MAX 0.99f
#define OMX_FX_DELAY_FEEDBACK_RANGE_MAX_DOUBLE 0.99
#define OMX_FX_DELAY_FEEDBACK_RANGE_MIN 0
#define OMX_FX_DELAY_FEEDBACK_RANGE_STEP 0
#define OMX_FX_DELAY_TIME_RANGE_DEFAULT 300
#define OMX_FX_DELAY_TIME_RANGE_MAX 2000
#define OMX_FX_DELAY_TIME_RANGE_MIN 0
#define OMX_FX_DELAY_TIME_RANGE_STEP 1
#define OMX_GEQ_BANDS 31
#define OMX_GEQ_BAND_Q 4.3f
#define OMX_GEQ_BAND_Q_DOUBLE 4.3
#define OMX_GEQ_BAND_RANGE_DEFAULT 0
#define OMX_GEQ_BAND_RANGE_MAX 15
#define OMX_GEQ_BAND_RANGE_MIN -15
#define OMX_GEQ_BAND_RANGE_STEP 0.5f
#define OMX_GEQ_BAND_RANGE_STEP_DOUBLE 0.5
#define OMX_GEQ_DESIGN_GAIN_MAX_DB 30
#define OMX_GEQ_PROTO_DB 12
#define OMX_GROWTH_CONFIRM_FRAMES 2
#define OMX_GROWTH_MAX_DIP_DB 0.5f
#define OMX_GROWTH_MAX_DIP_DB_DOUBLE 0.5
#define OMX_GROWTH_MAX_SINGLE_FRAME_SHARE 0.5f
#define OMX_GROWTH_MAX_SINGLE_FRAME_SHARE_DOUBLE 0.5
#define OMX_GROWTH_MIN_DB_PER_FRAME 0.8f
#define OMX_GROWTH_MIN_DB_PER_FRAME_DOUBLE 0.8
#define OMX_GROWTH_MIN_TOTAL_RISE_DB 6
#define OMX_GROWTH_WINDOW_FRAMES 5
#define OMX_HPF_FREQ_RANGE_MAX 1000
#define OMX_HPF_FREQ_RANGE_MIN 20
#define OMX_HPF_FREQ_RANGE_STEP 10
#define OMX_HRP_AMOUNT_RANGE_DEFAULT 0.5f
#define OMX_HRP_AMOUNT_RANGE_DEFAULT_DOUBLE 0.5
#define OMX_HRP_AMOUNT_RANGE_MAX 1
#define OMX_HRP_AMOUNT_RANGE_MIN 0
#define OMX_HRP_AMOUNT_RANGE_STEP 0
#define OMX_HRP_ATTRIBUTION_CENTS 60
#define OMX_HRP_BAND_Q 5
#define OMX_HRP_COLLISION_CENTS 100
#define OMX_HRP_DEFAULT_MAX_AUTO_BANDS 8
#define OMX_HRP_EXCESS_THRESHOLD_DB 3
#define OMX_HRP_GAIN_STEP_DB 2
#define OMX_HRP_MAX_CUT_DB 6
#define OMX_HRP_MAX_VOICES 8
#define OMX_LPF_FREQ_RANGE_MAX 20000
#define OMX_LPF_FREQ_RANGE_MIN 1000
#define OMX_LPF_FREQ_RANGE_STEP 10
#define OMX_OPERATOR_EQ_BANDS_RESERVE 9
#define OMX_PAN_RANGE_MAX 1
#define OMX_PAN_RANGE_MIN -1
#define OMX_PAN_RANGE_STEP 0
#define OMX_PHASER_BASE_RANGE_DEFAULT 200
#define OMX_PHASER_BASE_RANGE_MAX 2000
#define OMX_PHASER_BASE_RANGE_MIN 50
#define OMX_PHASER_BASE_RANGE_STEP 1
#define OMX_PHASER_DEPTH_RANGE_DEFAULT 4
#define OMX_PHASER_DEPTH_RANGE_MAX 6
#define OMX_PHASER_DEPTH_RANGE_MIN 0
#define OMX_PHASER_DEPTH_RANGE_STEP 0.1f
#define OMX_PHASER_DEPTH_RANGE_STEP_DOUBLE 0.1
#define OMX_PHASER_FEEDBACK_RANGE_DEFAULT 0.4f
#define OMX_PHASER_FEEDBACK_RANGE_DEFAULT_DOUBLE 0.4
#define OMX_PHASER_FEEDBACK_RANGE_MAX 0.9f
#define OMX_PHASER_FEEDBACK_RANGE_MAX_DOUBLE 0.9
#define OMX_PHASER_FEEDBACK_RANGE_MIN -0.9f
#define OMX_PHASER_FEEDBACK_RANGE_MIN_DOUBLE -0.9
#define OMX_PHASER_FEEDBACK_RANGE_STEP 0.01f
#define OMX_PHASER_FEEDBACK_RANGE_STEP_DOUBLE 0.01
#define OMX_PHASER_F_TOP_HZ 16000
#define OMX_PHASER_MIX_RANGE_DEFAULT 50
#define OMX_PHASER_MIX_RANGE_MAX 100
#define OMX_PHASER_MIX_RANGE_MIN 0
#define OMX_PHASER_MIX_RANGE_STEP 0.1f
#define OMX_PHASER_MIX_RANGE_STEP_DOUBLE 0.1
#define OMX_PHASER_RATE_RANGE_DEFAULT 0.5f
#define OMX_PHASER_RATE_RANGE_DEFAULT_DOUBLE 0.5
#define OMX_PHASER_RATE_RANGE_MAX 5
#define OMX_PHASER_RATE_RANGE_MIN 0.05f
#define OMX_PHASER_RATE_RANGE_MIN_DOUBLE 0.05
#define OMX_PHASER_RATE_RANGE_STEP 0.01f
#define OMX_PHASER_RATE_RANGE_STEP_DOUBLE 0.01
#define OMX_PHASER_STAGES_RANGE_DEFAULT 6
#define OMX_PHASER_STAGES_RANGE_MAX 12
#define OMX_PHASER_STAGES_RANGE_MIN 2
#define OMX_PHASER_STAGES_RANGE_STEP 2
#define OMX_PITCH_PREFILTER_CEILING_HZ 20000
#define OMX_PITCH_PREFILTER_Q 0.7071067811865476f
#define OMX_PITCH_PREFILTER_Q_DOUBLE 0.7071067811865476
#define OMX_PITCH_WINDOW_MS 40
#define OMX_PROGRAM_RELEASE_CHARGE_MS 1000
#define OMX_PROGRAM_RELEASE_DISCHARGE_MS 5000
#define OMX_PROGRAM_RELEASE_PROFILES_OPTO_FAST_MS 70
#define OMX_PROGRAM_RELEASE_PROFILES_OPTO_SHARE 0.5f
#define OMX_PROGRAM_RELEASE_PROFILES_OPTO_SHARE_DOUBLE 0.5
#define OMX_PROGRAM_RELEASE_PROFILES_OPTO_SLOW_MAX_MS 1100
#define OMX_PROGRAM_RELEASE_PROFILES_OPTO_SLOW_MIN_MS 110
#define OMX_PSHR_MIN_DB 10
#define OMX_REVERB_DAMPING_RANGE_DEFAULT 0.5f
#define OMX_REVERB_DAMPING_RANGE_DEFAULT_DOUBLE 0.5
#define OMX_REVERB_DAMPING_RANGE_MAX 1
#define OMX_REVERB_DAMPING_RANGE_MIN 0
#define OMX_REVERB_DAMPING_RANGE_STEP 0
#define OMX_REVERB_GATE_ATTACK_MS 1.5f
#define OMX_REVERB_GATE_ATTACK_MS_DOUBLE 1.5
#define OMX_REVERB_GATE_THRESHOLD_RANGE_DEFAULT -40
#define OMX_REVERB_GATE_THRESHOLD_RANGE_MAX 0
#define OMX_REVERB_GATE_THRESHOLD_RANGE_MIN -80
#define OMX_REVERB_GATE_THRESHOLD_RANGE_STEP 1
#define OMX_REVERB_HIGHCUT_RANGE_DEFAULT 20000
#define OMX_REVERB_HIGHCUT_RANGE_MAX 20000
#define OMX_REVERB_HIGHCUT_RANGE_MIN 0
#define OMX_REVERB_HIGHCUT_RANGE_STEP 10
#define OMX_REVERB_HOLD_RANGE_DEFAULT 120
#define OMX_REVERB_HOLD_RANGE_MAX 2000
#define OMX_REVERB_HOLD_RANGE_MIN 10
#define OMX_REVERB_HOLD_RANGE_STEP 10
#define OMX_REVERB_LOWCUT_RANGE_DEFAULT 0
#define OMX_REVERB_LOWCUT_RANGE_MAX 20000
#define OMX_REVERB_LOWCUT_RANGE_MIN 0
#define OMX_REVERB_LOWCUT_RANGE_STEP 10
#define OMX_REVERB_MIX_RANGE_BY_KIND_FX_RETURN 1
#define OMX_REVERB_MIX_RANGE_DEFAULT 0.3f
#define OMX_REVERB_MIX_RANGE_DEFAULT_DOUBLE 0.3
#define OMX_REVERB_MIX_RANGE_MAX 1
#define OMX_REVERB_MIX_RANGE_MIN 0
#define OMX_REVERB_MIX_RANGE_STEP 0
#define OMX_REVERB_PLATE_MOD_DEPTH_RANGE_DEFAULT 100
#define OMX_REVERB_PLATE_MOD_DEPTH_RANGE_MAX 400
#define OMX_REVERB_PLATE_MOD_DEPTH_RANGE_MIN 0
#define OMX_REVERB_PLATE_MOD_DEPTH_RANGE_STEP 1
#define OMX_REVERB_PREDELAY_RANGE_DEFAULT 0
#define OMX_REVERB_PREDELAY_RANGE_MAX 100
#define OMX_REVERB_PREDELAY_RANGE_MIN 0
#define OMX_REVERB_PREDELAY_RANGE_STEP 1
#define OMX_REVERB_RELEASE_RANGE_DEFAULT 20
#define OMX_REVERB_RELEASE_RANGE_MAX 500
#define OMX_REVERB_RELEASE_RANGE_MIN 1
#define OMX_REVERB_RELEASE_RANGE_STEP 1
#define OMX_REVERB_REVERSE_RANGE_DEFAULT 300
#define OMX_REVERB_REVERSE_RANGE_MAX 500
#define OMX_REVERB_REVERSE_RANGE_MIN 50
#define OMX_REVERB_REVERSE_RANGE_STEP 10
#define OMX_REVERB_SIZE_RANGE_DEFAULT 0.7f
#define OMX_REVERB_SIZE_RANGE_DEFAULT_DOUBLE 0.7
#define OMX_REVERB_SIZE_RANGE_MAX 1
#define OMX_REVERB_SIZE_RANGE_MIN 0
#define OMX_REVERB_SIZE_RANGE_STEP 0
#define OMX_REVERB_WIDTH_RANGE_DEFAULT 1
#define OMX_REVERB_WIDTH_RANGE_MAX 1
#define OMX_REVERB_WIDTH_RANGE_MIN 0
#define OMX_REVERB_WIDTH_RANGE_STEP 0
#define OMX_ROTARY_ACCEL_RANGE_DEFAULT 1
#define OMX_ROTARY_ACCEL_RANGE_MAX 4
#define OMX_ROTARY_ACCEL_RANGE_MIN 0.25f
#define OMX_ROTARY_ACCEL_RANGE_MIN_DOUBLE 0.25
#define OMX_ROTARY_ACCEL_RANGE_STEP 0.01f
#define OMX_ROTARY_ACCEL_RANGE_STEP_DOUBLE 0.01
#define OMX_ROTARY_BALANCE_RANGE_DEFAULT 0
#define OMX_ROTARY_BALANCE_RANGE_MAX 100
#define OMX_ROTARY_BALANCE_RANGE_MIN -100
#define OMX_ROTARY_BALANCE_RANGE_STEP 1
#define OMX_ROTARY_BASE_MS 0.1f
#define OMX_ROTARY_BASE_MS_DOUBLE 0.1
#define OMX_ROTARY_CROSSOVER_HZ 800
#define OMX_ROTARY_DRUM_ACCEL_MS 1700
#define OMX_ROTARY_DRUM_AM 0.3f
#define OMX_ROTARY_DRUM_AM_DOUBLE 0.3
#define OMX_ROTARY_DRUM_DECEL_MS 1800
#define OMX_ROTARY_DRUM_DOPPLER_MS 0.29f
#define OMX_ROTARY_DRUM_DOPPLER_MS_DOUBLE 0.29
#define OMX_ROTARY_DRUM_FAST_RANGE_DEFAULT 5.9f
#define OMX_ROTARY_DRUM_FAST_RANGE_DEFAULT_DOUBLE 5.9
#define OMX_ROTARY_DRUM_FAST_RANGE_MAX 10
#define OMX_ROTARY_DRUM_FAST_RANGE_MIN 3
#define OMX_ROTARY_DRUM_FAST_RANGE_STEP 0.01f
#define OMX_ROTARY_DRUM_FAST_RANGE_STEP_DOUBLE 0.01
#define OMX_ROTARY_DRUM_SLOW_RANGE_DEFAULT 0.7f
#define OMX_ROTARY_DRUM_SLOW_RANGE_DEFAULT_DOUBLE 0.7
#define OMX_ROTARY_DRUM_SLOW_RANGE_MAX 2
#define OMX_ROTARY_DRUM_SLOW_RANGE_MIN 0.1f
#define OMX_ROTARY_DRUM_SLOW_RANGE_MIN_DOUBLE 0.1
#define OMX_ROTARY_DRUM_SLOW_RANGE_STEP 0.01f
#define OMX_ROTARY_DRUM_SLOW_RANGE_STEP_DOUBLE 0.01
#define OMX_ROTARY_HORN_ACCEL_MS 330
#define OMX_ROTARY_HORN_AM 0.5f
#define OMX_ROTARY_HORN_AM_DOUBLE 0.5
#define OMX_ROTARY_HORN_DECEL_MS 500
#define OMX_ROTARY_HORN_DOPPLER_MS 0.44f
#define OMX_ROTARY_HORN_DOPPLER_MS_DOUBLE 0.44
#define OMX_ROTARY_HORN_FAST_RANGE_DEFAULT 6.8f
#define OMX_ROTARY_HORN_FAST_RANGE_DEFAULT_DOUBLE 6.8
#define OMX_ROTARY_HORN_FAST_RANGE_MAX 10
#define OMX_ROTARY_HORN_FAST_RANGE_MIN 3
#define OMX_ROTARY_HORN_FAST_RANGE_STEP 0.01f
#define OMX_ROTARY_HORN_FAST_RANGE_STEP_DOUBLE 0.01
#define OMX_ROTARY_HORN_SLOW_RANGE_DEFAULT 0.8f
#define OMX_ROTARY_HORN_SLOW_RANGE_DEFAULT_DOUBLE 0.8
#define OMX_ROTARY_HORN_SLOW_RANGE_MAX 2
#define OMX_ROTARY_HORN_SLOW_RANGE_MIN 0.1f
#define OMX_ROTARY_HORN_SLOW_RANGE_MIN_DOUBLE 0.1
#define OMX_ROTARY_HORN_SLOW_RANGE_STEP 0.01f
#define OMX_ROTARY_HORN_SLOW_RANGE_STEP_DOUBLE 0.01
#define OMX_ROTARY_MIX_RANGE_DEFAULT 100
#define OMX_ROTARY_MIX_RANGE_MAX 100
#define OMX_ROTARY_MIX_RANGE_MIN 0
#define OMX_ROTARY_MIX_RANGE_STEP 0.1f
#define OMX_ROTARY_MIX_RANGE_STEP_DOUBLE 0.1
#define OMX_ROTARY_RING_FLOATS 256
#define OMX_ROTARY_STOP_EPS 0.0001f
#define OMX_ROTARY_STOP_EPS_DOUBLE 0.0001
#define OMX_RTA_FFT_SIZE_MAX 32768
#define OMX_RTA_TARGET_BIN_HZ 5.9f
#define OMX_RTA_TARGET_BIN_HZ_DOUBLE 5.9
#define OMX_RT_HARD_TARGET_QUANTUM 128
#define OMX_RT_HARD_TARGET_RATE 192000
#define OMX_SUBHARMONIC_RADIUS_BINS 2
#define OMX_TRANSIENT_FAST_ATTACK_MS 0.5f
#define OMX_TRANSIENT_FAST_ATTACK_MS_DOUBLE 0.5
#define OMX_TRANSIENT_FAST_RELEASE_MS 20
#define OMX_TRANSIENT_FLOOR_LIN 0.00001f
#define OMX_TRANSIENT_FLOOR_LIN_DOUBLE 0.00001
#define OMX_TRANSIENT_REF_DB 6
#define OMX_TREMOLO_DEPTH_RANGE_DEFAULT 50
#define OMX_TREMOLO_DEPTH_RANGE_MAX 100
#define OMX_TREMOLO_DEPTH_RANGE_MIN 0
#define OMX_TREMOLO_DEPTH_RANGE_STEP 0.1f
#define OMX_TREMOLO_DEPTH_RANGE_STEP_DOUBLE 0.1
#define OMX_TREMOLO_MIX_RANGE_DEFAULT 100
#define OMX_TREMOLO_MIX_RANGE_MAX 100
#define OMX_TREMOLO_MIX_RANGE_MIN 0
#define OMX_TREMOLO_MIX_RANGE_STEP 0.1f
#define OMX_TREMOLO_MIX_RANGE_STEP_DOUBLE 0.1
#define OMX_TREMOLO_RATE_RANGE_DEFAULT 4
#define OMX_TREMOLO_RATE_RANGE_MAX 20
#define OMX_TREMOLO_RATE_RANGE_MIN 0.1f
#define OMX_TREMOLO_RATE_RANGE_MIN_DOUBLE 0.1
#define OMX_TREMOLO_RATE_RANGE_STEP 0.01f
#define OMX_TREMOLO_RATE_RANGE_STEP_DOUBLE 0.01
#define OMX_XOVER_LR2_SECTION_Q 0.5f
#define OMX_XOVER_LR2_SECTION_Q_DOUBLE 0.5
#define OMX_XOVER_LR4_SECTION_Q 0.7071067811865476f
#define OMX_XOVER_LR4_SECTION_Q_DOUBLE 0.7071067811865476
#define OMX_XOVER_PARTITION_TOLERANCE 0.00001f
#define OMX_XOVER_PARTITION_TOLERANCE_DOUBLE 0.00001

/* Every list rendered to C, sorted by list: OMX_<LIST>_COUNT and OMX_<LIST>_INIT { a, b, … }. */
#define OMX_EQ_CENTRE_SERIES_R20_HZ_COUNT 61u
#define OMX_EQ_CENTRE_SERIES_R20_HZ_INIT { 20, 22.4f, 25, 28, 31.5f, 35.5f, 40, 45, 50, 56, 63, 71, 80, 90, 100, 112, 125, 140, 160, 180, 200, 224, 250, 280, 315, 355, 400, 450, 500, 560, 630, 710, 800, 900, 1000, 1120, 1250, 1400, 1600, 1800, 2000, 2240, 2500, 2800, 3150, 3550, 4000, 4500, 5000, 5600, 6300, 7100, 8000, 9000, 10000, 11200, 12500, 14000, 16000, 18000, 20000 }
#define OMX_EQ_DEFAULT_CENTRES_FOUR_BAND_HZ_COUNT 4u
#define OMX_EQ_DEFAULT_CENTRES_FOUR_BAND_HZ_INIT { 100, 400, 2000, 8000 }
#define OMX_ISO_THIRD_OCTAVE_CENTRES_HZ_COUNT 31u
#define OMX_ISO_THIRD_OCTAVE_CENTRES_HZ_INIT { 20, 25, 31.5f, 40, 50, 63, 80, 100, 125, 160, 200, 250, 315, 400, 500, 630, 800, 1000, 1250, 1600, 2000, 2500, 3150, 4000, 5000, 6300, 8000, 10000, 12500, 16000, 20000 }
#define OMX_ORACLE_FLOOR_RATES_COUNT 4u
#define OMX_ORACLE_FLOOR_RATES_INIT { 44100, 48000, 96000, 192000 }
#define OMX_PHASER_STAGE_COUNTS_COUNT 6u
#define OMX_PHASER_STAGE_COUNTS_INIT { 2, 4, 6, 8, 10, 12 }
#define OMX_RME_RATES_COUNT 9u
#define OMX_RME_RATES_INIT { 32000, 44100, 48000, 64000, 88200, 96000, 128000, 176400, 192000 }
#define OMX_STANDARD_SAMPLE_RATES_COUNT 6u
#define OMX_STANDARD_SAMPLE_RATES_INIT { 44100, 48000, 88200, 96000, 176400, 192000 }

/* Every set rendered to C, sorted by set: an enum of the ids (a named id's position, or a numeric id's number), `OMX_<SET>_COUNT` and,
 * where the set names a default, `OMX_<SET>_DEFAULT`. */
enum omx_band_dyn_modes {
  OMX_BAND_DYN_MODES_ABOVE = 0,
  OMX_BAND_DYN_MODES_BELOW = 1,
};
#define OMX_BAND_DYN_MODES_COUNT 2u
#define OMX_BAND_DYN_MODES_DEFAULT OMX_BAND_DYN_MODES_ABOVE
enum omx_deess_modes {
  OMX_DEESS_MODES_SPLIT = 0,
  OMX_DEESS_MODES_WIDEBAND = 1,
};
#define OMX_DEESS_MODES_COUNT 2u
enum omx_delay_pingpongs {
  OMX_DELAY_PINGPONGS_OFF = 0,
  OMX_DELAY_PINGPONGS_ON = 1,
};
#define OMX_DELAY_PINGPONGS_COUNT 2u
#define OMX_DELAY_PINGPONGS_DEFAULT OMX_DELAY_PINGPONGS_OFF
enum omx_drive_auto_gains {
  OMX_DRIVE_AUTO_GAINS_OFF = 0,
  OMX_DRIVE_AUTO_GAINS_ON = 1,
};
#define OMX_DRIVE_AUTO_GAINS_COUNT 2u
#define OMX_DRIVE_AUTO_GAINS_DEFAULT OMX_DRIVE_AUTO_GAINS_ON
enum omx_drive_bands {
  OMX_DRIVE_BANDS_FULL = 0,
  OMX_DRIVE_BANDS_LOW = 1,
  OMX_DRIVE_BANDS_HIGH = 2,
  OMX_DRIVE_BANDS_TILT = 3,
};
#define OMX_DRIVE_BANDS_COUNT 4u
enum omx_drive_curves {
  OMX_DRIVE_CURVES_SOFT = 0,
  OMX_DRIVE_CURVES_TAPE = 1,
  OMX_DRIVE_CURVES_TUBE = 2,
  OMX_DRIVE_CURVES_EXCITER = 3,
};
#define OMX_DRIVE_CURVES_COUNT 4u
enum omx_drive_hf_rolloffs {
  OMX_DRIVE_HF_ROLLOFFS_0 = 0,
  OMX_DRIVE_HF_ROLLOFFS_12000 = 12000,
  OMX_DRIVE_HF_ROLLOFFS_16000 = 16000,
};
#define OMX_DRIVE_HF_ROLLOFFS_COUNT 3u
#define OMX_DRIVE_HF_ROLLOFFS_DEFAULT OMX_DRIVE_HF_ROLLOFFS_0
enum omx_drive_stereo_links {
  OMX_DRIVE_STEREO_LINKS_OFF = 0,
  OMX_DRIVE_STEREO_LINKS_ON = 1,
};
#define OMX_DRIVE_STEREO_LINKS_COUNT 2u
#define OMX_DRIVE_STEREO_LINKS_DEFAULT OMX_DRIVE_STEREO_LINKS_ON
enum omx_eq_band_ons {
  OMX_EQ_BAND_ONS_OFF = 0,
  OMX_EQ_BAND_ONS_ON = 1,
};
#define OMX_EQ_BAND_ONS_COUNT 2u
enum omx_eq_band_types {
  OMX_EQ_BAND_TYPES_BELL = 0,
  OMX_EQ_BAND_TYPES_LOW_SHELF = 1,
  OMX_EQ_BAND_TYPES_HIGH_SHELF = 2,
  OMX_EQ_BAND_TYPES_NOTCH = 3,
  OMX_EQ_BAND_TYPES_ALLPASS1 = 4,
  OMX_EQ_BAND_TYPES_ALLPASS2 = 5,
};
#define OMX_EQ_BAND_TYPES_COUNT 6u
#define OMX_EQ_BAND_TYPES_DEFAULT OMX_EQ_BAND_TYPES_BELL
enum omx_eq_hpf_ons {
  OMX_EQ_HPF_ONS_OFF = 0,
  OMX_EQ_HPF_ONS_ON = 1,
};
#define OMX_EQ_HPF_ONS_COUNT 2u
#define OMX_EQ_HPF_ONS_DEFAULT OMX_EQ_HPF_ONS_OFF
enum omx_eq_lpf_ons {
  OMX_EQ_LPF_ONS_OFF = 0,
  OMX_EQ_LPF_ONS_ON = 1,
};
#define OMX_EQ_LPF_ONS_COUNT 2u
#define OMX_EQ_LPF_ONS_DEFAULT OMX_EQ_LPF_ONS_OFF
enum omx_filter_slopes {
  OMX_FILTER_SLOPES_12 = 12,
  OMX_FILTER_SLOPES_24 = 24,
};
#define OMX_FILTER_SLOPES_COUNT 2u
#define OMX_FILTER_SLOPES_DEFAULT OMX_FILTER_SLOPES_12
enum omx_gate_key_sources {
  OMX_GATE_KEY_SOURCES_SELF = 0,
  OMX_GATE_KEY_SOURCES_SIDECHAIN = 1,
};
#define OMX_GATE_KEY_SOURCES_COUNT 2u
enum omx_param_scales {
  OMX_PARAM_SCALES_LINEAR = 0,
  OMX_PARAM_SCALES_LOG = 1,
  OMX_PARAM_SCALES_STEPPED = 2,
};
#define OMX_PARAM_SCALES_COUNT 3u
#define OMX_PARAM_SCALES_DEFAULT OMX_PARAM_SCALES_LINEAR
enum omx_reverb_algorithms {
  OMX_REVERB_ALGORITHMS_ROOM = 0,
  OMX_REVERB_ALGORITHMS_PLATE = 1,
  OMX_REVERB_ALGORITHMS_HALL = 2,
  OMX_REVERB_ALGORITHMS_REVERSE = 3,
  OMX_REVERB_ALGORITHMS_GATED = 4,
};
#define OMX_REVERB_ALGORITHMS_COUNT 5u
enum omx_rotary_speeds {
  OMX_ROTARY_SPEEDS_STOP = 0,
  OMX_ROTARY_SPEEDS_SLOW = 1,
  OMX_ROTARY_SPEEDS_FAST = 2,
};
#define OMX_ROTARY_SPEEDS_COUNT 3u
enum omx_tremolo_modes {
  OMX_TREMOLO_MODES_TREMOLO = 0,
  OMX_TREMOLO_MODES_PAN = 1,
};
#define OMX_TREMOLO_MODES_COUNT 2u
#define OMX_TREMOLO_MODES_DEFAULT OMX_TREMOLO_MODES_TREMOLO

/* The default bands of an EQ with `count` bands: THE one rule, for every strip, host and count (omx-contract's
 * lib/eq-defaults.mjs; the ts render exports the same as eqDefaultCentres and eqDefaultTypes). Needs -lm. */
static inline unsigned omx_eq_default_centres(unsigned count, float *out) {
  static const double r10[] = OMX_ISO_THIRD_OCTAVE_CENTRES_HZ_INIT;
  static const double r20[] = OMX_EQ_CENTRE_SERIES_R20_HZ_INIT;
  static const double four[] = OMX_EQ_DEFAULT_CENTRES_FOUR_BAND_HZ_INIT;
  if (count == 0) return 0;
  if (count == 4) {
    for (unsigned i = 0; i < 4; i++) out[i] = (float)four[i];
    return 4;
  }
  const double lo = log((double)OMX_EQ_FREQ_RANGE_MIN);
  const double span = log((double)OMX_EQ_FREQ_RANGE_MAX / (double)OMX_EQ_FREQ_RANGE_MIN);
  for (unsigned s = 0; s < 2; s++) {
    const double *series = s ? r20 : r10;
    const unsigned n = s ? OMX_EQ_CENTRE_SERIES_R20_HZ_COUNT : OMX_ISO_THIRD_OCTAVE_CENTRES_HZ_COUNT;
    int distinct = count <= n;
    for (unsigned i = 0; distinct && i < count; i++) {
      const double t = lo + span * ((double)i + 0.5) / (double)count;
      unsigned best = 0;
      double best_d = 1e300;
      for (unsigned k = 0; k < n; k++) {
        const double d = fabs(log(series[k]) - t);
        if (d < best_d) { best_d = d; best = k; }
      }
      out[i] = (float)series[best];
      if (i > 0 && out[i] == out[i - 1]) distinct = 0;
    }
    if (distinct) return count;
  }
  return 0;
}

/* The default type of band `index` of an EQ with `count` bands: a low shelf first, a high shelf last, bells
 * between (a single band is a bell). An OMX_EQ_BAND_TYPES_* member. */
static inline int omx_eq_default_type(unsigned index, unsigned count) {
  if (count < 2) return OMX_EQ_BAND_TYPES_BELL;
  return index == 0 ? OMX_EQ_BAND_TYPES_LOW_SHELF : index == count - 1 ? OMX_EQ_BAND_TYPES_HIGH_SHELF : OMX_EQ_BAND_TYPES_BELL;
}

#endif /* OMX_CONTRACT_LIMITS_H */

/* The sample rates the console declares (core's STANDARD_SAMPLE_RATES, row-codecs.ts): the set a
 * contract's rate-is-declared precondition accepts, through omx_rate_is_declared(), and the grid a
 * native tool iterates. Guarded on its own so a tool built against a pinned copy of this header
 * (lv2-inprocess-pin.sh) can include this tree's copy after it and gain the rates without mixing
 * the pin's limits. */
#ifndef OMX_DECLARED_RATE_COUNT
#define OMX_DECLARED_RATE_COUNT 6u
static const float OMX_DECLARED_RATES[OMX_DECLARED_RATE_COUNT] = { 44100.0f, 48000.0f, 88200.0f, 96000.0f, 176400.0f, 192000.0f };
/* The declared rates that are whole multiples of `base` (a tool's default grid: the 48 kHz family),
 * in declaration order, at most `cap` of them; returns how many were written to `out`. */
static inline int omx_declared_rates_multiple_of(unsigned base, int *out, int cap) {
  int n = 0;
  for (unsigned k = 0; k < OMX_DECLARED_RATE_COUNT && n < cap; k++)
    if ((unsigned)OMX_DECLARED_RATES[k] % base == 0) out[n++] = (int)OMX_DECLARED_RATES[k];
  return n;
}
#endif
