// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com>
/**
 * The `ts` target: one ESM module and its type declarations, every item exported under its own
 * name with its literal type (`as const`), so a re-export in openmixer keeps names, values and types.
 */

/** The value a TypeScript reader sees for one resolved item. */
export function tsValue(r) {
  if (r.kind !== 'plugin') return r.value;
  return { plugin: r.plugin, header: r.header, prefix: r.prefix, params: r.value };
}

/** The literal type of a JSON value, every member readonly. */
export function tsType(v, indent = '') {
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  if (typeof v === 'string') return JSON.stringify(v);
  const inner = `${indent}  `;
  if (Array.isArray(v)) return v.length ? `readonly [${v.map((x) => tsType(x, indent)).join(', ')}]` : 'readonly []';
  const keys = Object.keys(v);
  if (!keys.length) return '{}';
  const key = (k) => (/^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k));
  return `{\n${keys.map((k) => `${inner}readonly ${key(k)}: ${tsType(v[k], inner)};`).join('\n')}\n${indent}}`;
}

const docComment = (r) => {
  const text = [r.doc, r.why && `Why: ${r.why}`].filter(Boolean).join('\n\n').replace(/\*\//g, '*\\/');
  return `/**\n${text.split('\n').map((l) => (l ? ` * ${l}` : ' *')).join('\n')}\n * @see ${r.rel}\n */`;
};

const BANNER = `// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com>
// GENERATED by \`omx-contract render --target ts\` from FreeMixer/omx-contract's data/ — do not edit.
`;

/** Every file of the `ts` target: `[{ path, text }]`. */
export function renderTs(resolved) {
  const items = [...resolved.values()];
  const js = BANNER + items.map((r) => `\n${docComment(r)}\nexport const ${r.name} = ${JSON.stringify(tsValue(r), null, 2)};\n`).join('');
  const dts = BANNER + items.map((r) => `\n${docComment(r)}\nexport declare const ${r.name}: ${tsType(tsValue(r))};\n`).join('');
  return [{ path: 'omx-contract.js', text: js }, { path: 'omx-contract.d.ts', text: dts }];
}
