// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com>
import { eqDefaultBands, eqDefaultCentres, eqDefaultParams, eqDefaultTypes } from '../lib/eq-defaults.mjs';

/**
 * The `ts` target: one ESM module and its type declarations, every item exported under its own
 * name with its literal type (`as const`), so a re-export in openmixer keeps names, values and types.
 */

/** The value a TypeScript reader sees for one resolved item. */
export function tsValue(r) {
  return r.value;
}

/** The literal type of a JSON value, every member readonly. */
export function tsType(v, indent = '') {
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  if (typeof v === 'string') return JSON.stringify(v);
  const inner = `${indent}  `;
  if (Array.isArray(v)) return v.length ? `readonly [${v.map((x) => tsType(x, indent)).join(', ')}]` : 'readonly []';
  const keys = Object.keys(v);
  if (!keys.length) return '{}';
  const key = (k) => (/^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k));
  return `{\n${keys.map((k) => `${inner}readonly ${key(k)}: ${tsType(v[k], inner)};`).join('\n')}\n${indent}}`;
}

const docComment = (r) => {
  const text = [r.doc, r.why && `Why: ${r.why}`].filter(Boolean).join('\n\n').replace(/\*\//g, '*\\/');
  return `/**\n${text.split('\n').map((l) => (l ? ` * ${l}` : ' *')).join('\n')}\n * @see ${r.rel}\n */`;
};

const BANNER = `// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com>
// GENERATED by \`omx-contract render --target ts\` from FreeMixer/omx-contract's data/ — do not edit.
`;

/**
 * The default EQ rule (lib/eq-defaults.mjs) as functions of the module: the library's own source,
 * with the declared parameters bound, so the ts reader runs the code the tests hold equal to the c one.
 */
function eqRule(resolved) {
  if (!resolved.has('EQ_DEFAULT_CENTRES_FOUR_BAND_HZ')) return { js: '', dts: '' };
  const bound = JSON.stringify(eqDefaultParams(resolved), null, 2);
  const fn = (f, as) => f.toString().replace(`function ${f.name}(`, `function ${as}(`);
  const js = `
/** The declared parameters of the default EQ rule: the four-band set, the preferred series, the band frequency travel, the band gain and Q. */
const EQ_DEFAULT_RULE = ${bound};
${fn(eqDefaultCentres, 'centres')}
${fn(eqDefaultTypes, 'types')}
${fn(eqDefaultBands, 'bands')}

/** The default band centres (Hz) of an EQ with \`count\` bands: THE one rule, for every strip, host and count. */
export function eqDefaultCentres(count) { return centres(count, EQ_DEFAULT_RULE); }

/** The default band types, by EQ_BAND_TYPES id: a low shelf, bells, a high shelf (a single band is a bell). */
export function eqDefaultTypes(count) { return types(count); }

/** Every default band of an EQ with \`count\` bands: type, centre, gain and Q. */
export function eqDefaultBands(count) { return bands(count, EQ_DEFAULT_RULE); }
`;
  const dts = `
/** The default band centres (Hz) of an EQ with \`count\` bands: THE one rule, for every strip, host and count. */
export declare function eqDefaultCentres(count: number): number[];
/** The default band types, by EQ_BAND_TYPES id: a low shelf, bells, a high shelf (a single band is a bell). */
export declare function eqDefaultTypes(count: number): string[];
/** Every default band of an EQ with \`count\` bands: type, centre, gain and Q. */
export declare function eqDefaultBands(count: number): { type: string; freqHz: number; gainDb: number; q: number }[];
`;
  return { js, dts };
}

/** Every file of the `ts` target: `[{ path, text }]`. */
export function renderTs(resolved) {
  const items = [...resolved.values()];
  const rule = eqRule(resolved);
  const js = BANNER + items.map((r) => `\n${docComment(r)}\nexport const ${r.name} = ${JSON.stringify(tsValue(r), null, 2)};\n`).join('') + rule.js;
  const dts = BANNER + items.map((r) => `\n${docComment(r)}\nexport declare const ${r.name}: ${tsType(tsValue(r))};\n`).join('') + rule.dts;
  return [{ path: 'omx-contract.js', text: js }, { path: 'omx-contract.d.ts', text: dts }];
}
